vkbo/novelWriter

- nw/gui/doceditor.py
- nw/gui/dochighlight.py
- nw/gui/winmain.py
- nw/project/project.py
Replaces the context menu for spell check suggestions from the example code with an improved version. I guess the hack used in the old one to get the word under a right click was a problem of Qt4. In Qt5 it's trivial.
This PR also removes the native context menu, and only allows for a spell suggestion one. It also adds the keyboard shortcut `Ctrl+.` to pop open the spell check menu when the cursor is on a word.
> Improved SpellCheck Context

- .gitignore
- nw/__init__.py
- nw/config.py
- nw/gui/docdetails.py
- nw/gui/doctree.py
- nw/gui/winmain.py
- nw/project/project.py
- tests/nwdummy.py
- tests/nwtools.py
- tests/reference/new_nwProject.nwx
- tests/reference/novelwriter.conf
- tests/reference/roots_nwProject.nwx
- tests/test_config.py
- tests/test_project.py
Adds a unit test framework for pytest tests.
This required a better separation of project classes and GUI classes in novelWriter. Some things have been moved around to achieve this.
Currently added basic tests for opening and closing the config file and the main project file. Also added tests for adding root objects to a project.
> Unit Tests

- nw/common.py
- nw/gui/doceditor.py
- nw/gui/dochighlight.py
- nw/gui/mainmenu.py
- nw/gui/winmain.py
- nw/project/item.py
- nw/project/project.py
- tests/reference/new_nwProject.nwx
- tests/reference/roots_nwProject.nwx
Added menu option to toggle spell check on and off, and the state is saved to the project file, not app settings. There is also a menu option for re-running the spell checker on the current document.
> Spellcheck updates

- nw/enum.py
- nw/gui/doctree.py
- nw/project/project.py
- sample/sampleNovel/nwProject.nwx
A few minor improvements.
Loading a project where the item entries in the project file is in the wrong order is now possible. An iterator function has been added that will move items to the end of the tree order list if the parent item comes after the item itself.
Fixed a minor bug where a root item could not be added if another item was not selected. There is no need to select an item in the tree to add a root item, as they are, well, root items.
> Improvements

- nw/gui/docviewer.py
- nw/gui/winmain.py
* Remember scroll bar position when pressing Ctrl+R on a document already being viewed.
* Remove version number from windows title.
> Minor Changes

- nw/gui/docdetails.py
- nw/gui/projecteditor.py
* The text boxes in project settings are no longer editable when no items to edit are selected.
* The document details pane would stack labels instead of replace the text when a new item was selected.
> Fixes to details pane and project settings dialog

- nw/common.py
- nw/config.py
- nw/gui/doceditor.py
- nw/gui/winmain.py
Addresses issue #44 
For non-essential features (currently custom tab stop length) using the later versions of Qt5, a version check has been added before the PyQt5 command is executed.
Testing novelWriter with Qt 5.5.1 works, although the above mentioned feature requires 5.10.
> Added version checking for Qt5 and PyQt5 dependencies

- nw/config.py
- nw/tools/spellenchant.py
Fixes an issue with the spell language setting being "none" triggering a fatal error on next load. Added a try/except to the loading itself.
> Bugfixes, dictionary fatal error

- nw/enum.py
- nw/gui/docdetails.py
- nw/gui/doceditor.py
- nw/gui/mainmenu.py
- nw/gui/searchbar.py
- nw/gui/winmain.py
This PR adds a simple search function, requested in issue #48, implemented using the default find method in QTextEdit.
It provides a plain find, next, previous set of features. It will be extended to include replace, case sensitivity (it is currently not case sensitive) and possibly with regex support.
> Simple Search Function

- nw/enum.py
- nw/gui/doceditor.py
- nw/gui/mainmenu.py
- nw/gui/searchbar.py
- nw/gui/winmain.py
Search/replace now fully implemented, although only for currently edited document
This completes issue/feature #48
> Extend search feature to allow replace as well

- nw/gui/doceditor.py
- nw/gui/searchbar.py
Some further improvements to the replace feature
> Replace Updates

- nw/constants.py
- nw/gui/mainmenu.py
- nw/gui/sessionlog.py
- nw/gui/timelineview.py
- nw/gui/winmain.py
- nw/project/project.py
For a while now, the length of each writing session has been logged to a file in the project meta folder. This PR adds a GUI to display this log, and the sum total time.
The dialog can be opened from the menu under Project > Session Log.
> Session Log

- nw/config.py
- nw/constants.py
- nw/gui/doceditor.py
- nw/gui/doctree.py
- nw/gui/itemeditor.py
- nw/gui/mainmenu.py
- nw/gui/winmain.py
- sample/sampleNovel/data_b/a8a28a246524_main.nwd
- sample/sampleNovel/nwProject.nwx
- tests/reference/novelwriter.conf
- tests/test_config.py
This partially addresses request #63 
This change makes it possible to fill an open document file with content loaded from a text file. The option is accessible from the menu under Document > Import from File, or by pressing `Ctrl+Shift+I`. This will open a file dialog box allowing the user to select a text file to import. A document in the editor must be open beforehand, and the content will be replaced. A dialog box will check that it is OK to replace the text in the case the document is not empty.
Trying to load a binary file will cause an error. The file read must be readable by Python3 as a text file. and convertible to plain text.
> Import Text File

- nw/convert/file/latex.py
- nw/convert/text/tolatex.py
- nw/gui/export.py
- requirements.txt
Adds encoding of unicode characters to LaTeX escapes using the package `latexcodec`.
If the package is missing, or otherwise doesn't work, the export still proceeds, but a warning is issued that the file may not build.
Also, in the same PR, wrapping of LaTeX source has been removed.
This should resolve issue #78.
> LaTeX unicode fix

- nw/config.py
- nw/convert/file/concat.py
- nw/convert/file/html.py
- nw/convert/file/latex.py
- nw/convert/file/markdown.py
- nw/convert/file/text.py
- nw/gui/doceditor.py
- nw/gui/sessionlog.py
- nw/gui/winmain.py
- nw/project/document.py
- nw/project/index.py
- nw/project/project.py
- nw/theme.py
- nw/tools/optlaststate.py
- tests/nwtools.py
This PR fixes three issues with running novelWriter on Windows, and one of the issues is general to all OSes.
* Generating the initial config file now works also on Windows. It previously failed since the config location required two directories to be created, but the code assumed only one was needed.
* On Windows, the Python `open()` command does not default to utf8, so all open statements now have encoding specified.
* Failing to open a file that exists, caused novelWriter to report an error, but still internally tagged the file buffer as open and ready. This is what it usually does for files that do not exist (i.e. new file), so the open statement in that case returns an empty string from the file load function. However, since the file load function did not distinguish between new file …
> Windows fixes

- nw/convert/file/latex.py
- nw/convert/file/text.py
- nw/convert/text/tohtml.py
- nw/convert/text/tolatex.py
- nw/convert/text/tomarkdown.py
- nw/convert/text/totext.py
- nw/convert/tokenizer.py
- nw/gui/export.py
This PR adds a new tab to the export dialog for Pandoc support.
When selecting Pandoc in the Settings tab, the project is first exported to either markdown or html, depending on what final format is requested from the Pandoc tab. Open Office and Word documents are converted from html, and epub and zimwiki files are exported from markdown.
A few additional options have been added to the main GUI to. Since Pandoc seems to ignore alignement settings in the html, the option to just skip scene and section headings have been added. 
More settings need to be added to the Pandoc tab for epub export, but it seems to work fine for office documents.
> Pandoc Export

- nw/convert/text/tohtml.py
- nw/convert/text/tolatex.py
- nw/convert/text/totext.py
- nw/convert/tokenizer.py
- nw/gui/doceditor.py
- nw/gui/dochighlight.py
- sample/sampleNovel/data_b/a8a28a246524_main.nwd
- sample/sampleNovel/nwProject.nwx
Added the markdown feature of two or more spaces at the end of a line for hard line breaks. Now supported by html and LaTeX export as well, which includes html preview.
The editor will highlight two or more trailing spaces at the end of a line so that the hard line break is visible. In addition, a hard line break can be inserted by pressing `Ctrl+Enter`.
> Hard line breaks

- README.md
- nw/common.py
- nw/config.py
- nw/constants.py
- nw/gui/export.py
- nw/gui/mainmenu.py
- requirements.txt
- tests/reference/novelwriter.conf
This PR includes:
* Updates to package warnings, adding clickable links. This addresses issue #85.
* Modified some of the initial configuration settings for the editor. Fixed width and justified text is now off by default.
* Removed numbers from the recent projects menu entry. They served no purpose beyond debugging.
* Updated readme.
> GUI Tweaks

- nw/convert/text/tohtml.py
- nw/gui/elements/docviewer.py
- nw/gui/elements/viewdetails.py
- nw/gui/statusbar.py
- nw/gui/winmain.py
- nw/project/index.py
This PR adds a panel at the bottom of a viewed document with all the documents referencing it. If there are no backlinks, the panel is not visible.
In addition, all references set in a document with the `@` keywords are now converted to clickable links in the document viewer.
This PR is related to issue #76.
> Docview Meta Data

- nw/convert/text/tohtml.py
- nw/convert/text/totext.py
- nw/convert/tokenizer.py
- nw/gui/elements/docviewer.py
- sample/sampleNovel/data_5/3b69b83cdafc_main.nwd
- sample/sampleNovel/data_b/a8a28a246524_main.nwd
- sample/sampleNovel/nwProject.nwx
This fixes a few issues with the export:
* Make sure tabs are exported as four spaces to text and `&emsp;` to html.
* Make sure tabs are visible as 8 non-breaking spaces in the document view panel.
* Make sure hard line breaks are exported to text files.
* Fix a bug for title and partition pages where the page break was overwriting the last line of the page rather than be appended to it. Issue #112
> Export Fixes

- nw/gui/elements/viewdetails.py
- nw/gui/winmain.py
- nw/project/index.py
Further updates to the indexing and displaying of tags and references.
* The reference pane is  now in a scroll area, so it no longer grows vertically.
* Source code cleanup and comments.
* At the top of the panel a show/hide arrow button has been added next to the label.
* A sticky checkbox has been added on the right hand side to prevent the panel from being updated when a link is followed. If the panel is then un-stickied, the panel is updated. This addresses issue #111
> Meta Data Updates

- nw/gui/elements/docdetails.py
- nw/guimain.py
This lets the label wrap when it grows too long, and if it is larger than 100 characters, it is truncated.
This addresses issue #120
> Fix growing tree details panel on long labels

- nw/gui/elements/doceditor.py
- nw/guimain.py
This adresses issue #148 
This import feature is anyway a temporary solution, as it offers no way to revert the process if an existing file was overwritten.
> Fixed a minor issue when insert from file was cancelled.

- nw/gui/elements/doceditor.py
- nw/guimain.py
This PR adresses issue #150.
Resizing the window triggers a full re-highlighting of the entire document on each step, due to a change of the document root frame triggering a contentsChange signal to be emitted for **the entire document**. That is completely unnecessary, so this fix blocks the signal emission for the document object when the frame margins are altered.
The PR also disables opaque slider movement for the main splitters. The text reflow is performed after the new slider position is dropped.
> Prevent re-highlight on resize

- nw/config.py
- nw/gui/dialogs/configeditor.py
- nw/gui/elements/doceditor.py
- nw/gui/mainmenu.py
- nw/gui/tools/dochighlight.py
- tests/reference/novelwriter.conf
This PR attempts to boost the performance of the syntax highlighter and spell checker.
First of all, an option to set a limit of how large documents are spell checked on load can now be set in preferences. The default size is 800 kb. That should only take a couple of seconds with spell enchant. When the document is larger than the set limit, the initial check is skipped, and the user has to press F7 manually to run the spell checker on the whole document.
When "big document mode" is active, spell check as you type is still active, and a paragraph or line is spell checked when it is altered.
In addition, the syntax highlighting performance has been improved by a factor 2. The highlighting of a 820000 word test document was reduced from ~800 ms to ~400 ms. Both by skipping empty text …
> Highlighter Improvements

- nw/gui/elements/doceditor.py
- nw/gui/mainmenu.py
This PR switches the cursor to a wait cursor when loading a document or running the spell checker on the whole document.
The issue with the current implementation is that it resets the undo stack for big documents. This is because for a large document, the text is reloaded when the spell checker is run on the full text. This takes about 9 seconds on the 820k words test document. Any other method I've tried takes about 4 minutes. I still don't understand this difference.
> Spinning cursor when loading and spell checking

- nw/gui/dialogs/docmerge.py
- nw/gui/dialogs/docsplit.py
- nw/gui/elements/doctree.py
- nw/gui/mainmenu.py
This addresses some points from issue #161.
* Changed the wording on the dropdown box in the Split Document dialog to clarify its meaning.
* Added a menu option to empty the trash folder.
* Added a check to catch when the user tries to move an item to the Orphaned Items folder.
> Tweaks to file split, trash and drag'n'drop

- nw/__init__.py
- nw/config.py
- nw/guimain.py
If the command line parser have any remaining, unparsed arguments, the first one is treated as the project path the user wants to open. When the GUI is constructed, a call is sent to the openProject function with this argument. The project class will handle any garbage that may end up here if this is not intended.
> Open project from command line

- nw/constants/constants.py
- nw/guimain.py
- nw/project/document.py
- nw/project/project.py
- nw/tools/__init__.py
- nw/tools/legacy.py
- tests/test_gui.py
This PR changes the following:
* Remove the cache folder and 10 copies of the project file.
* Saving the project and a document is written to a temp file, which is then renamed to the final file.
* Before the renaming of the temp file, the old file is renamed to .bak for backup.
* If the main project file cannot be opened, the backup file is opened instead.
> File saving and opening

- README.md
- docs/source/started.txt
- novelWriter.py
- nw/config.py
- nw/constants/constants.py
- requirements.txt
- setup.py
The Python package `appdirs` is only needed for extracting the user's config path on various operating systems. This feature is available in Qt5 via `QStandardPaths`, so the package can be dropped.
> Drop appdirs dependency

- install.py
Update install.py with correct joined paths for the `themes` folder and the `graphics` folder. This bug prevented pyInstaller from building successfully under Windows.
> Update install.py with correct paths

- nw/constants/constants.py
- nw/gui/dialogs/docsplit.py
- nw/gui/dialogs/export.py
- nw/gui/dialogs/sessionlog.py
- nw/gui/dialogs/timelineview.py
- nw/project/project.py
- nw/tools/__init__.py
- nw/tools/legacy.py
- nw/tools/optionstate.py
- nw/tools/optlaststate.py
- sample/sampleNovel/nwProject.nwx
Changing the way the various dialog options are saved on a per project basis. They are no longer saved as separate files per dialog, but as a single file.
This change should not affect the user, aside from all options being reset to the default value the first time a project is opened after updating to this version of the code.
> Saving of Dialog Options

- nw/__init__.py
- nw/common.py
- nw/config.py
- nw/constants/constants.py
- nw/gui/__init__.py
- nw/gui/dialogs/__init__.py
- nw/gui/dialogs/projectload.py
- nw/gui/icons.py
- nw/gui/mainmenu.py
- nw/guimain.py
- nw/project/project.py
- tests/reference/novelwriter.conf
- tests/test_config.py
- tests/test_gui.py
- tests/test_project.py
This is the first step of the project load screen that replaces the recent projects menu with a dialog box. The dialog box is opened when the app is launched (unless a project path is specified via command line) and a cache of recently opened projects is listed. This list has more info than the previous meny list.
If a project isn't listed, the user can clisk a browse button that pops the regular open project dialog.
> Project Load Screen

- nw/config.py
- nw/constants/constants.py
- nw/guimain.py
- nw/project/backup.py
- nw/project/project.py
- tests/reference/proj/2_nwProject.nwx
- tests/test_project.py
This PR adds a project lock file to prevent opening the same project twice. A user may, for instance, have the project open on two computers synced via a file sync tool, or on a network drive. The user will now be alerted if the lock file exists, but can override the lock if they wish.
This PR solves issue #7.
> Project Lockfile

- nw/gui/elements/outline.py
- sample/sampleNovel/data_6/a2d6d5f4f401_main.nwd
- sample/sampleNovel/nwProject.nwx
This PR fixes a bug where the Outline column header settings from last session were restored when the Outline was updated. This was due to the header being rebuilt every time the tree was updated. This is only necessary when on first build after a project is opened.
> Outline Fixes

- nw/tools/spellenchant.py
This bug is back. Since the __init__ file lists everything, the enchant class fails to load when enchant isn't installed. Adding an extra try/except on the import fixes this.
> Fixed bug in loading of dictionary without enchant installed

- nw/constants/constants.py
- nw/constants/enum.py
- nw/gui/elements/doceditor.py
- nw/gui/elements/outline.py
- nw/gui/tools/dochighlight.py
- nw/guimain.py
- nw/project/index.py
- sample/sampleNovel/data_6/a2d6d5f4f401_main.nwd
- sample/sampleNovel/nwProject.nwx
This PR adds the following features:
* Double-clicking a title in the outline view will open that document for editing. If the title selected is not the first title in the document, the cursor will be moved to the correct position in the document. (See also Issue #187)
* The marker for synopsis comments has been changed a bit so that it is a bit more relaxed in identifying a comment that should be considered a synopsis. As long as the word "synopsis:" (with the following colon) is the fist word in the comment, not case sensitive, the comment is flagged as the synopsis for the file. (See also Issue #186)
> Outline Feature - Step 2

- nw/additions/__init__.py
- nw/additions/qconfiglayout.py
- nw/additions/qswitch.py
- nw/constants/constants.py
- nw/gui/dialogs/configeditor.py
- nw/gui/elements/doctitlebar.py
- nw/gui/theme.py
This PR completely rewrites the Preferences dialog.
Changes include:
* A new form layout that provides more helpful (I hope) text to the user. Design inspired by Gnome Tweak tool. One option per row in a two column layout.
* The checkbox has been replaced by an Android style switch.
* Connected the previous unreachable option to enable/disable full path in document header.
* Split all options over more tabs.
> New Preferences Dialog

- nw/core/document.py
- nw/core/project.py
- nw/gui/elements/doceditor.py
- sample/sampleNovel/data_1/4298de4d9524_main.nwd
- sample/sampleNovel/data_5/3b69b83cdafc_main.nwd
- sample/sampleNovel/data_5/eaea4e8cdee8_main.nwd
- sample/sampleNovel/data_6/36b6aa9b697b_main.nwd
- sample/sampleNovel/data_6/a2d6d5f4f401_main.nwd
- sample/sampleNovel/data_8/8706ddc78b1b_main.nwd
- sample/sampleNovel/data_9/6b68994dfa3d_main.nwd
- sample/sampleNovel/data_a/e7339df26ded_main.nwd
- sample/sampleNovel/data_b/3e74dbc1f584_main.nwd
- sample/sampleNovel/data_b/8136a5a774a0_main.nwd
- sample/sampleNovel/data_b/a8a28a246524_main.nwd
- sample/sampleNovel/data_b/b2c23b3c42cc_main.nwd
- sample/sampleNovel/data_b/c0cbd2a407f3_main.nwd
- sample/sampleNovel/data_f/1471bef9f2ae_main.nwd
- sample/sampleNovel/nwProject.nwx
- tests/reference/gui/1_1489056e0916_main.nwd
- tests/reference/gui/1_8010bd9270f9_main.nwd
- tests/reference/gui/1_a6562590ef19_main.nwd
- tests/reference/gui/1_e17daca5f3e1_main.nwd
This PR adds a single line of meta data at the top of document files. The document class itself handles this internally, and it is stripped before any text is returned. None of the rest of the code will ever see this line. It is buffered in the docMeta variable.
Currently it isn't used for anything, but it can be used for recovering orphaned files. Mainly, it is useful to see where a file inside the project folder belongs in the project tree if one were to browse those files.
This PR also fixes a minor bug with recognising the trash folder that was introduced in one of the recent PRs, and a GUI bug with dynamic margins being ignored when a file is loaded. Neither were critical bugs.
> Document Meta Data

- nw/core/project.py
- nw/gui/dialogs/configeditor.py
- nw/gui/dialogs/itemeditor.py
- nw/gui/dialogs/projecteditor.py
- nw/gui/elements/doceditor.py
This PR fixes a bug where only a part of a text file would render in the document editor if the document frame itself changed during loading of the text. The text was still in the buffer, and no damage was done to the file, it just looked truncated.
> Bugfix: Text of large document not always visible in editor

- README.md
- novelWriter.py
- nw/__init__.py
- nw/assets/icons/fallback/status_stats-dark.svg
- nw/assets/icons/fallback/status_stats.svg
- nw/config.py
- nw/core/document.py
- nw/core/project.py
- nw/gui/dialogs/projecteditor.py
- nw/gui/elements/doceditor.py
- nw/gui/icons.py
- nw/gui/statusbar.py
- nw/gui/tools/dochighlight.py
- nw/guimain.py
This PR makes a few minor changes:
* A few of the checks for versions of Qt, PyQt, and Python3, as well as key dependencies, is now done in the main function so we can pop a message box to the user instead of relying on terminal output.
* Made a few minor changes so we can run on older versions of Qt and Python3. Now successfully tested with Python 3.4.3 and Qt 5.2.1.
* Redesigned the status LEDs on the statusbar, and moved some of the information around a bit.
> Minor Improvements

- nw/config.py
- nw/gui/dialogs/configeditor.py
- nw/gui/elements/doctree.py
- nw/gui/tools/dochighlight.py
- tests/reference/novelwriter.conf
Two minor changes:
* Clicking the document header selects the file in the project tree, but now it also makes sure the selected item is visible. If the folder it's in is collapsed, it's expanded, and scrolled into view.
* It is now possible to disable syntax highlighting of text in quotes  from the Preferences > General tab.
> Minor Fixes

- CHANGELOG.md
- nw/core/tohtml.py
- nw/core/tokenizer.py
- nw/gui/build.py
- sample/sampleNovel/data_e/dca4be2fcaf8_main.nwd
- sample/sampleNovel/nwProject.nwx
This PR makes a few improvements to the build project tool. Some speedup, and some regarding consistent formatting between preview, print, and saved files. It also cleans up the rules for page breaks, and shifts the novel headers to conform to standards that will later be needed for making epub exports.
In the generated HTML, chapter headers are now H1, scenes H2, etc. Note files follow the internal novelWriter format still. A chapter header has a forced page break before it, notes do not, but each new note category (root folder) now has a header with a forced page break.
> Build Project Updates

- nw/config.py
- nw/gui/dialogs/projectload.py
- nw/guimain.py
Some minor improvements to the Load project dialog:
* Entries in the recent projects list can be deleted with the delete key.
* The browse button now sits after the path box, and is run locally in the dialog, not in the main GUI. The benefit is only that if the cancel button is pressed in the browse dialog, we return to the Project Load dialog, not the main window.
* The selected path box is now a QLineEdit, not a QLabel. It looks more reasonable, and we avoid having to consider word wrapping.
> Project Load Dialog Updates

- nw/core/index.py
- nw/gui/elements/outline.py
- tests/test_project.py
With multiple headings in a file, the structure of the file sent to the Outline panel would be sorted with the text value of line numbers, like: "1", "10", "2", "21", etc. The simple fix is to just format these line keys with leading zeroes.
> Fixed sorting bug for line numbers in index

- nw/gui/elements/doceditor.py
- nw/gui/elements/docviewer.py
The text of the document editor and viewer flows underneath the document title bar, but the margin is always kept larger than the bar, so it generally isn't a problem, but when the text is scrolled by code, it doesn't considered this hidden area. This PR adjusts the viewport margin to accomodate the title bar, meaning no part of the document is behind the title bar.
> Document Margins and DocTitle Bar

- nw/config.py
- nw/core/project.py
Regarding Issue #240.
If the backup folder is the same, or under, the project folder to be backed up, the `make_archive` command in Python `shutil` will run an infinite loop of backing up the archive within the archive.
This PR adds a check on the two paths before calling the command.
> Backup Infinite Loop

- CHANGELOG.md
- nw/gui/build.py
QAction must have a parent set before Qt 5.7. This PR fixes this so we're again compatible with Ubuntu 16.04 LTS. This fixes Issue #243.
> Fix Qt 5.5 Support

- nw/assets/icons/fallback/check-dark.svg
- nw/assets/icons/fallback/check.svg
- nw/assets/icons/fallback/cross-dark.svg
- nw/assets/icons/fallback/cross.svg
- nw/assets/icons/typicons_colour_dark/icons.conf
- nw/assets/icons/typicons_colour_dark/tick.svg
- nw/assets/icons/typicons_colour_light/icons.conf
- nw/assets/icons/typicons_colour_light/tick.svg
- nw/assets/icons/typicons_grey_dark/icons.conf
- nw/assets/icons/typicons_grey_dark/tick.svg
- nw/assets/icons/typicons_grey_light/icons.conf
- nw/assets/icons/typicons_grey_light/tick.svg
- nw/gui/elements/docdetails.py
- nw/gui/elements/doctitlebar.py
- nw/gui/elements/doctree.py
- nw/gui/icons.py
- nw/gui/statusbar.py
- nw/gui/theme.py
Removed the project tree checkmark for exported items and instead added a new third column that displays an icon for this. The icon renders more uniformly on different platforms.
In the process, I added a bunch of font metrics calculations to ensure icons and graphic elements scale with GUI font size. Also gave the main data columns in the project tree details panel a minimum size so they don't rescale every time you switch item in the tree view.
> Export Icon Column

- nw/config.py
- nw/gui/dialogs/preferences.py
- nw/gui/theme.py
- tests/reference/novelwriter.conf
Added the option to change the font size of the GUI font.
I've noticed that for instance Ubuntu 16.04 renders the GUI with a very large font, and Windows 10 with a very small one, by default. It now defaults to 12 points on all platforms, but can be changed in Preferences between 8 and 60.
> GUI Font Size Settings

- nw/gui/elements/doctree.py
Fix project tree text font and size not following the gui settings on some systems. This forces the tree rows and header to the gui font. Issue #273.
> GUI Font Size Issue

- nw/core/tohtml.py
- nw/gui/build.py
This PR adds a setting to the HTML converter and a switch to the Build Novel Project tool to disable CSS styles on the generated HTML. This applies to both the preview, and therefore PDF/Print, and to the HTML that goes to htm or json file.
> Export w/o Styling

- nw/core/document.py
- nw/gui/__init__.py
- nw/gui/docbars.py
- nw/gui/doceditor.py
- nw/guimain.py
Currently, documents in Trash folder are read only. This is enforced artificially, and there really is no point to it. This PR removes this feature, and also removes the GuiNoticeBar class used for alerting the user to this. It was always an inelegant implementation.
> Drop Read Only

- nw/__init__.py
- nw/core/tohtml.py
- nw/gui/build.py
- nw/gui/docviewer.py
The HTML converter did not expect a `@tag:` command with no tags. The tag keyword itself is element 0 in the returned array, and the following elements are the actual tags. The converter checked for length 0, in which case it ignores the line, but in the length 1 case, it still tried to convert the tags to html anchor points. This works fine for other keywords, as `array[1:] is safe for out of bounds calls, but since tags have only one entry, it uses `array[1]`, causing an out of bounds error.
This PR adds an `if len(array) > 1` check before even entering this part of the converter. In addition, the call to the converter is wrapped in a `try/except` construct both in the document viewer and build tool to prevent parsing errors from crashing novelWriter.
This fixes Issue #298.
> Markdown to HTML Converter Bug

- nw/gui/itemdetails.py
- nw/gui/outline.py
- nw/gui/projload.py
- nw/gui/projsettings.py
- nw/gui/statusbar.py
- nw/gui/theme.py
Deleting a recent projects entry should open a dialog box first.
This PR also drops the duplicate icon size variable. Only one is needed, and the same should always be used for consistency.
> Project Load Updates (++)

- nw/config.py
- nw/core/tohtml.py
- nw/gui/docviewer.py
- nw/gui/mainmenu.py
- nw/gui/preferences.py
- tests/reference/novelwriter.conf
- tests/test_config.py
This adds the option to also render synopsis comments in the document view panel.
In addition, the view comments and view synopsis options are now set in the "Text Layout" tab in the "Preferences" dialog.
> Comment Rendering in Document Viewer

- nw/constants/constants.py
- nw/gui/custom.py
- nw/gui/preferences.py
- nw/gui/projsettings.py
- tests/test_gui.py
This PR adds a selection dialog for quote symbols. It selects from a list of predefined symbols, with a large font preview, and a description for each symbol.
The dialog must now be used to select the different quote marks in the Preferences dialog, and will also be added to Project Settings later on.
> Quote Symbols Dialog

- nw/__init__.py
- nw/constants/__init__.py
- nw/constants/constants.py
- nw/constants/enum.py
- nw/core/tohtml.py
- nw/gui/doceditor.py
- nw/gui/dochighlight.py
- nw/gui/mainmenu.py
- nw/guimain.py
- sample/content/636b6aa9b697b.nwd
- sample/nwProject.nwx
This PR adds support for thin space and thin non-breaking space, and adds an Insert menu with the following options:
* Insert > Short Dash
* Insert > Long Dask
* Insert > Ellipsis
* Insert > Hard Line Break
* Insert > Non-Breaking Space
* Insert > Thin Space
* Insert > Thin Non-Breaking Space
They all have a double keybinding sequence, starting with `Ctrl+K` and then a second set for the selected character or symbol. This also changes the keybinding for the current hard line break and non-breaking space features.
> Document Insert Feature

- nw/constants/constants.py
- nw/constants/enum.py
- nw/gui/doceditor.py
- nw/gui/mainmenu.py
This PR addresses Issue #312 by adding a function in the doc editor class that will replace all straight quotes on a selected piece of text.
It also addresses Issue #320. The solution here was in part to capture the internal undo action before it could trigger the actual undo, and redirect it around into the `docAction` function which temporarily disables auto-replace when performing these actions. It then calls the undo() programmatically, preventing the loop reported in the issue.
In addition, the PR now adds multiple places where auto-replace is temporarily blocked, and it also only calls the auto-replace function when a single new character is added. Any valid key combination for auto-replace is only one character.
> Replace Quotes and Undo History Behaviour

- nw/gui/docviewer.py
- nw/guimain.py
Pressing `Ctrl+R` while editing a document (editor has focus) should trigger a preview of that document. The selected document in the project tree should be second choice, or when the editor does not have focus.
This PR changes that order, and also triggers a `saveDocument` call before updating the view, meaning it can effectively be used to refresh the view at any time. The view is generated from the saved file, not the editor content.
This resolves Issue #143.
> Preview Edit Doc Before Selected Doc

- nw/gui/doceditor.py
- nw/gui/docviewer.py
- nw/gui/projtree.py
- tests/reference/gui/3_nwProject.nwx
Don't scroll project tree every time a document is opened. This feature is only needed for when the user clicks the document tile bar.
> Don't Auto-Scroll Project Tree

- nw/gui/docmerge.py
- nw/gui/outline.py
- nw/gui/projtree.py
- nw/guimain.py
Different policy for scrolling to reveal tree item for different ways of opening a document. For instance, clicking or hitting the enter key to open an item does not scroll the item to the centre of the project tree, but continuing a search in the next file does.
This addresses Issue #332.
> Scroll to Reveal in Tree Settings

- nw/gui/projtree.py
This PR solves some issues with how word count accounting is done in the tree.
The points from Issue #333 are resolved:
* When a file is moved to Trash, the word count is moved along with it.
* When a file is permanently deleted, the word count is first zeroed, forcing it to be subtracted from the Trash folder count.
In addition, this PR fixes some issues with word counts being subtracted and added incorrectly when a file is dragged from one folder to another.
> Word Counts

- nw/common.py
- nw/gui/build.py
This PR adds a header label on top of the document preview in the Build Novel project tool to make it clear when the document was generated. It includes a fuzzy time string as well so the user doesn't have to spend too much time figuring out how old it is.
This addresses Issue #331.
> Age of Project Build

- nw/common.py
- nw/gui/build.py
The document header should say something even when there is no build cache,
Also, add weeks and months to the fuzzy time converter and let it end in counting full years.
> Built Time – A Few Tweaks

- nw/core/project.py
- sample/nwProject.nwx
- tests/reference/gui/2_nwProject.nwx
This PR alters the way the auto-replace settings ares stored in the XML from:
```
<autoReplace>
<A>D</A>
<B>E</B>
<C>F</C>
</autoReplace>
```
to:
```
<autoReplace>
<entry key="A">D</entry>
<entry key="B">E</entry>
<entry key="C">F</entry>
</autoReplace>
```
The open project function supports both formats.
> Auto-Replace XML Format

- CHANGELOG.md
- nw/core/project.py
- nw/gui/sessionlog.py
- sample/nwProject.nwx
This PR fixes a couple of minor things with the Session Log dialog. The first line will now no longer show negative counts if you filter out novel or note files, and will properly remove the first line if hide zeros is enabled and the line has 0 word diff.
In addition, the project XML has been given a version bump to 1.2. This means that if a project is opened and saved after this point, it cannot be opened by an older version of novelWriter without losing the auto-replace settings.
If needed, the user can bypass this check by changing the fileVersion setting on line 2 of the project XML file `nwProject.nwx` from `1.2` to `1.1`. However, any auto-replace setting will be lost. No other settings will be affected.
> Session Log Fixes and Project File Version Bump

- README.md
- docs/source/interface.rst
- nw/constants/enum.py
- nw/gui/doceditor.py
- nw/gui/mainmenu.py
- nw/guimain.py
- tests/test_gui.py
This PR changes the wording to the more accurate name for emphasised text according to Markdown and HTML5. It doesn't change how it's renderred.
> Emphasis instead of Italic, Bold, etc

- nw/config.py
- nw/gui/preferences.py
- nw/guimain.py
- tests/reference/novelwriter.conf
Added the Preferences option to hide the document footer bar when in distraction free mode.
This partially addresses issue #301.
> Hide docFooter in Zen Mode

- nw/config.py
- nw/gui/dochighlight.py
- nw/gui/preferences.py
- tests/reference/novelwriter.conf
Added an option in Preferences to enable/disable the colour added to emphasised text. The emphasis itself is still show, so italicised text is still italicised, etc. The delimiters still receive the theme colour for "hidden" text. In the context of novelWriter, it means text that isn't part of the body text, so either markup or comments.
> Optional Colour Highlighting of Emphasised Text

- nw/gui/doceditor.py
The find feature in the QTextEdit, the core Qt widget of the document editor window, supports regular expression search objects from Qt 5.3 and up. But it only supports the older QRegExp class. From Qt 5.13 the QRegularExpression class is also supported. This PR switches to QRegularExpression if that requirement is met. To my knowledge, the only relevant improvement is the matching of unicode characters with the `\w` switch in the regex.
See: https://doc.qt.io/qt-5/qtextedit.html#find-2
> Search/Replace Regular Expression Update

- docs/source/export.rst
- nw/core/__init__.py
- nw/core/tokenizer.py
- nw/core/tools.py
- nw/gui/build.py
This PR adds the support of generating chapter numbers as upper or lower case Roman numbers.
The key to add them into the title format is `%chI%` or `%chi%`, respectively.
> Roman Numbers in Build Tool

- nw/__init__.py
- nw/error.py
- nw/gui/build.py
- nw/guimain.py
Add a hook for global exception handling, and pipe all exceptions there. This also prevents novelWriter from closing on non-critical errors. Ideally, errors should not reach this function, but be handled in-place. The error handler pops up a dialof box with information to copy/paste to an issues ticket.
> Exception Handling

- tests/conftest.py
A convenient fix I made in a different project after copying the test config code from novelWriter.
> Added project root path to sys.path for test suite

- README.md
Updated README for the change of default branch to `main`.
> Switch default branch

- docs/source/interface.rst
- nw/config.py
- nw/gui/mainmenu.py
- nw/guimain.py
The online documentation is still better than the local copy, so this PR ensures that the Help menu entry for online documentation is always available, even when the local one is as well. The online one is connected to `Shift+F1`. If the local is available, the `F1` key defaults to the local one, otherwise it too direct to the online version.
> Help Menu Improvements

- docs/source/projects.rst
- nw/core/options.py
- nw/gui/writingstats.py
A settings box to cap the histogram for the Writing Stats dialog has been added. If large chunks of text have been added or removed to the project, the histogram is dominated by these numbers. Capping the word count that maximises the bar will now filter out these. The default value is 2000 words, but the range is 100 to 100 000.
> Writing Stats Histogram Cap

- nw/gui/build.py
- nw/gui/docmerge.py
- nw/gui/docsplit.py
- nw/gui/mainmenu.py
- nw/gui/preferences.py
- nw/guimain.py
Fix a few issues with modality of dialogs.
These are now non-modal:
* Writing Stats
* Build Novel Project
These are now modal
* Split Document
* Merge Folder
* About novelWriter
* About Qt
* Preferences
* Project Settings
> Dialog Modality

- nw/gui/doceditor.py
Modify the paragraph selection behaviour of Qt to not include the preceding paragraph separator in the selection.
> Issue #396: Select Paragraph Fix

- docs/source/interface.rst
- nw/gui/doceditor.py
This PR fixes a few clumsy issues with how the tab and enter keys work in the editor panel.
The Qt widget itself disables the tab key as a focus changing key, which makes sense since you want to be able to type tabs. However, since the search box sits on top of the editor, the tab key would still write to the text editor even if the search box had focus.
Previously, this was solved by blocking the tab key entirely when the search box was in focus, but not the replace box. This has now been changed to block the focus change event itself when the editor is in focus, and alternate between focus and replace when it's not.
The return AND enter keys are now properly captured to move the search forward, and only those keys are blocked.
* The alternative key sequence `Ctrl+Shift+Z` to redo last …
> Editor Focus and Enter Key Behaviour

- docs/source/interface.rst
- docs/source/projects.rst
- nw/assets/icons/typicons_colour_dark/icons.conf
- nw/assets/icons/typicons_colour_light/icons.conf
- nw/assets/icons/typicons_grey_dark/icons.conf
- nw/assets/icons/typicons_grey_light/icons.conf
- nw/constants/constants.py
- nw/constants/enum.py
- nw/core/index.py
- nw/core/tree.py
- nw/gui/build.py
- nw/gui/mainmenu.py
- nw/gui/projtree.py
- nw/gui/theme.py
- sample/ToC.json
- sample/ToC.txt
- sample/content/8a5deb88c0e97.nwd
- sample/nwProject.nwx
This PR adds a new special root folder named "Outtakes". It is similar to the Trash folder in that any file can be moved there and they are all excluded from the index and builds.
In addition, this PR fixes or improves a few other things:
* Files can now be dragged and dropped into the Trash folder, as opposed to before this was only possible via the Delete Item function.
* Files that are moved to Outtakes and Trash will now have their index entry automatically deleted.
* Any file moved anywhere that isn't Trash or Outtakes, will have its index rebuilt automatically.
* A bug in the root item record meant that deleting a root folder during a session still didn't enable the option to create that root folder from the menu. One had to close and re-open the project to reactivate the menu …
> Outtakes (Archive) Feature

- docs/source/interface.rst
- docs/source/projects.rst
- nw/constants/constants.py
- nw/core/document.py
- nw/core/index.py
- nw/core/tree.py
- nw/gui/projtree.py
- sample/nwProject.nwx
Fixes and improvements to PR #415.
* Indexer should still count words for trash and archived files. This was generally not the case before for files in Trash either, but it makes sense to maintain a word count here too.
* Allow creation of subfolders in the Outtakes root folder. As long as the folders have the same item class as the Outtakes folder itself, all the logic for validating drags and drops should work just fine.
* A number of loops on the project tree have a maximum cap of 200 iterations, setting a de facto cap on folder depth. That is, folders can be created, but things stop working, like word counters etc. This PR also adds a hard cap that blocks folder creation beyond max - 1, leaving room for files in the innermost folder. The hard cap is now set to 30. Folder creation cap …
> Outtake/Archive Fixes

- README.md
- nw/core/tohtml.py
- nw/gui/build.py
- nw/gui/doceditor.py
- nw/gui/docviewer.py
The document viewer panel uses a QTextBrowser to display the generated HTML from the novelWriter makrdown. However, the Qt HTML function strips away all tabs when setting the QTextBrowser content, which means the tabs become spaces.
This PR leaves the tabs in the generated HTML, but before setting the text in the QTextBrowser, replaces tabs with `!!tab!!`, and when the text is loaded, uses the document find function to find them and set them back to actual tabs. This is the only way I've found to get tabs through the `setHtml` function.
This is a bit hacky, but it works. The only issue is that for large documents, the replace is called while the Qt thread is still rendering the text on the screen, causing some of the text to become invisible. This is an issue I've encountered before. To …
> Tab Stop in Document Viewer and Build

- nw/gui/doceditor.py
Fix the error message about the lookup of a None handle. It was caused by the function that clears the document editor footer bar that shows the document status and word count. Passing a handle = None to it was used to clear it, but the function always made a lookup for the corresponding item even with a None handle. This works just fine, but the search for a None item emits an error message in the lookup function nonetheless.
> Issue #418: Error printout in the logger

- nw/gui/outlinedetails.py
- tests/lipsum/nwProject.nwx
- tests/test_gui.py
This PR adds tests for:
* The Open Project dialog,
* The Outline View.
It also fixes the following issues:
* The count values for word and paragraph counts were swapped in the details panel of the Outline View.
> Adding Tests for Project Load and Outline View

- nw/gui/docmerge.py
- nw/gui/docsplit.py
This PR adds a dialog box asking for permission to generate N number of files when splitting. No such box is presented with the merge tool as only a single file is generated. Thus there is less to clean up in case the user made a mistake.
Both tools now set the item status of each file generated to the that of the source item.
> Split and Merge improvements

- .github/workflows/pytest_cov.yml
- nw/core/project.py
- nw/gui/doceditor.py
- nw/gui/projsettings.py
- nw/guimain.py
- sample/nwProject.nwx
- tests/reference/gui/0_nwProject.nwx
- tests/reference/gui/1_nwProject.nwx
- tests/reference/gui/2_nwProject.nwx
- tests/reference/gui/3_nwProject.nwx
- tests/reference/proj/1_nwProject.nwx
- tests/reference/proj/2_nwProject.nwx
- tests/reference/proj/3_nwProject.nwx
- tests/reference/proj/4_nwProject.nwx
This PR adds a project language setting that can be used to override the spell check language setting in preferences for a specific project. The override setting is in the Project Settings dialog.
> Issue #368: Project language setting

- nw/constants/constants.py
- nw/gui/doceditor.py
- nw/gui/docviewer.py
- tests/test_gui.py
This PR adds:
**Document Editor**
* Cut and Copy to the context menu when a user has made a selection.
* Paste, Select All, Select Word and Select Paragraph to the context menu.
* Spell checking is added to the same menu if any suggestions are available.
* Select Word and Paragraph selects the word/paragraph under the pointer, not the cursor as the equivalent main menu entries do.
**Document Viewer**
* Removes the built-in context menu and replaces it with the Paste, Select All, Select Word and Select Paragraph features from the document editor context menu.
These changes makes them consistent (the built-in menu looks different than the other menus) and the editor and viewer are now consistent in features and functionality with each other.
Tests have been added to check that the selection …
> Issue #438: Editor cut/copy/paste

- docs/source/int_interface.rst
- nw/assets/icons/fallback/backward-dark.svg
- nw/assets/icons/fallback/backward.svg
- nw/assets/icons/fallback/forward-dark.svg
- nw/assets/icons/fallback/forward.svg
- nw/assets/icons/typicons_colour_dark/chevron-left.svg
- nw/assets/icons/typicons_colour_dark/chevron-right.svg
- nw/assets/icons/typicons_colour_dark/icons.conf
- nw/assets/icons/typicons_colour_light/chevron-left.svg
- nw/assets/icons/typicons_colour_light/chevron-right.svg
- nw/assets/icons/typicons_colour_light/icons.conf
- nw/assets/icons/typicons_grey_dark/chevron-left.svg
- nw/assets/icons/typicons_grey_dark/chevron-right.svg
- nw/assets/icons/typicons_grey_dark/icons.conf
- nw/assets/icons/typicons_grey_light/chevron-left.svg
- nw/assets/icons/typicons_grey_light/chevron-right.svg
- nw/assets/icons/typicons_grey_light/icons.conf
- nw/core/tohtml.py
- nw/gui/docviewer.py
- nw/gui/mainmenu.py
- nw/gui/theme.py
- nw/guimain.py
- tests/test_gui.py
This PR adds a 20 page history to the document viewer where the user can navigate backwards and forwards in the last opened documents. The forward history is reset if the user opens a document explicitly instead of navigating back and forth. Same as a browser does, and the undo/redo stack.
The user can interact with the navigation in the following ways:
* Backward and forward navigation in the `View` menu.
* Keyboard shortcuts `Alt+Left` and `Alt+Right`.
* Navigation buttons in the top, left corner of the document view window.
* Backward and forward nav buttons on the mouse, if available.
If novelWriter is started with the `--verbose` flag, the entire history is dumped to the terminal window each time a navigation occurs. This can be used for debugging, although it is definitely verbose …
> Issue #441: Document Viewer History Navigation

- nw/gui/projtree.py
The middle mouse button will now open a document in the view panel.
> Middle Mouse Button

- nw/assets/icons/fallback/bullet-off-dark.svg
- nw/assets/icons/fallback/bullet-off.svg
- nw/assets/icons/fallback/bullet-on-dark.svg
- nw/assets/icons/fallback/bullet-on.svg
- nw/assets/icons/typicons_colour_dark/icons.conf
- nw/assets/icons/typicons_colour_dark/media-record-outline.svg
- nw/assets/icons/typicons_colour_dark/media-record.svg
- nw/assets/icons/typicons_colour_light/icons.conf
- nw/assets/icons/typicons_colour_light/media-record-outline.svg
- nw/assets/icons/typicons_colour_light/media-record.svg
- nw/assets/icons/typicons_grey_dark/icons.conf
- nw/assets/icons/typicons_grey_dark/media-record-outline.svg
- nw/assets/icons/typicons_grey_dark/media-record.svg
- nw/assets/icons/typicons_grey_light/icons.conf
- nw/assets/icons/typicons_grey_light/media-record-outline.svg
- nw/assets/icons/typicons_grey_light/media-record.svg
- nw/config.py
- nw/gui/doceditor.py
- nw/gui/docviewer.py
- nw/gui/preferences.py
- nw/gui/projtree.py
- nw/gui/theme.py
- nw/guimain.py
This PR changes:
* Search and Edit buttons in the editor header.
* Show/hide comments and synopsis in the viewer footer.
* Removes the show comments and synopsis form the Layouts tab in Preferences.
> Header and Footer Buttons (Edit, Search, Comments, Synopsis)

- .gitignore
- nw/core/project.py
- nw/gui/docmerge.py
- nw/gui/mainmenu.py
This PR fixes three bugs:
* Selecting edit item from the main menu fails because the selection event sends out a dummy boolean variable that is always set to `False`. This value overrides the handle variable of the function to open the edit dialog, making the dialog trying to look up an item "False". The menu action now wraps the call in a lambda function that passes `None` to be sure. The bug was caused by the recent addition of an optional parameter to the function that opens the dialog, which the dummy variable would set.
* Due to the above, all menu actions are now wrapped in lambda functions, in addition to all those that already were.
* The merge tool, when used on a file, would alert the user that a single file cannot be merged. The tool still let the user click the merge button, …
> Bug Fixes: Edit Item, Merge Tool, Orphaned Files

- codecov.yml
- nw/common.py
- nw/gui/projload.py
- nw/gui/projtree.py
- nw/gui/theme.py
- nw/gui/writingstats.py
- tests/test_common.py
This PR does the following:
* Changes the Last Opened column of the Project Load dialog to a fixed with font, and adds a thin space between the word count and the multiplier unit in the Words column.
* Fixes a bug in the filtering of options in the Project Tree context menu. When the user right-clicks an item, the available options for that item is turned visible, and the other become invisible. However, the options that are filtered out on the Trash folders were accidentally applied to other folders if there was no Trask folder present. This is because when the Trash folder is not present, the lookup of its handle returns a None, which accidentally matches on Root folders who have a parent folder handle set to None (they are root folders without parents). The filter therefor thought they …
> Tree Context Menu Fix and Project Load Improvement

- nw/common.py
- nw/constants/constants.py
- nw/core/index.py
- nw/core/tokenizer.py
- nw/core/tools.py
- nw/gui/build.py
- nw/gui/doceditor.py
- nw/gui/dochighlight.py
- nw/gui/projload.py
- nw/gui/writingstats.py
- nw/guimain.py
- tests/test_dialogs.py
This PR makes a few improvements to the document editor that mostly affects large and very large documents.
* The syntax highlighter now remembers what type of line each line in a document is. Whether it is empty, a title, text or a meta keyword/value set. This information is then used when the index is manually updated to rehighlight the lines containing meta keywords only. Previously, this was handled by reloading the entire document. This not only resets the undo stack, which is annoying, it is also quite slow for large documents in the megabyte range.
* When preferences were changed, the document editor would also previously reload in order to update the text formats and other layout options. This again resets the undo stack, and is slow for large documents. This has now been replaced …
> Editor Performance Improvements

- nw/assets/icons/fallback/status_lines-dark.svg
- nw/assets/icons/fallback/status_lines.svg
- nw/gui/doceditor.py
- nw/gui/theme.py
This PR adds a small line counter next to the word counter at the bottom of the document editor. It is sometimes convenient when comparing files between the novelWriter editor and other plain text editors.
> Line Counter

- nw/config.py
- nw/gui/build.py
- nw/gui/doceditor.py
- nw/gui/docviewer.py
- nw/gui/outline.py
- nw/gui/outlinedetails.py
- nw/gui/preferences.py
- nw/gui/projtree.py
- nw/guimain.py
- tests/reference/novelwriter.conf
- tests/reference/novelwriter_prefs.conf
- tests/test_dialogs.py
This PR adds 4 new settings:
* Hide vertical scroll bars on the main GUI and the Build Novel Project tool. Scrolling can still be done with keys and mouse wheel.
* Hide horizontal scroll bars, like above, but doesn't scroll with wheel.
* Scroll past end of document. That is, allows scrolling until the last line of the document is at the top of the editor window.
* Typewriter scrolling when typing. Meaning that when a the cursor moves to a new line while typing, the editor will try to keep the cursor at the same vertical position as before and instead scroll the document. This keeps the cursor vertically stationary, like on a typewriter. The effect only applies to the vertical axis.
This fulfils feature request #467 This PR also fixes issue #465
> Scrolling Options

- README.md
- docs/source/int_introduction.rst
- install.py
- nw/__init__.py
- setup.cfg
- setup.py
Since novelWriter is no longer compatible with Python 3.4 and 3.5, it is best to force a minimal Python version of 3.6.0. This PR ensures that, and updates the documentation.
This PR also alters the `setup.py` script to not import the main `nw` package to populate various variables. The version number is instead extracted via the `setup.cfg` file as described in the Python packaging documentation.
> Change Python minimal version to 3.6

- nw/gui/build.py
This fixes issue #471
This bug is unfortunately not caught by tests as the tests run on newer versions from the pip installer. One of the test jobs should probably run on an older set of Qt libraries.
> Fix a bug in build tool for lower Qt versions

- nw/gui/custom.py
- nw/gui/doceditor.py
- tests/test_gui.py
This PR makes a few minor changes to the document editor.
* The line counter in the footer now shows how many percent through the document you are. This is convenient for large documents.
* The follow cursor feature (typewriter mode) now animates the scrolling over 150 to 650 milliseconds, depending on the distance to move. This smooths the otherwise sudden jumps this feature would make when the scroll bar value was changed.
* The context menu now shows a "Follow Tag" menu entry when the menu is opened on a word on a meta keyword/value line. The spell checker is also disabled for these lines also on the context menu level. Previously, it was just blocked on the highlighter.
> Document Editor Tweaks

- nw/config.py
- nw/gui/doceditor.py
This is related to issue #451. This PR changes the behaviour of the formatting functions to only apply the format to the first of the selected paragraphs.
> Formatting with mulitple paragraphs selected

- nw/config.py
- nw/core/index.py
- nw/core/options.py
- nw/core/project.py
- nw/core/tree.py
- nw/gui/writingstats.py
- tests/test_dialogs.py
- tests/test_index.py
Related to issues discussed in #383.
All JSON files are now indented with two spaces. Previously, the index file was only indented when running in debug mode. Indented files are easier to version control, although there isn't really any point in tracking any of the JSON files in a novelWriter project.
This PR also skips using an intermediate variable when loading and saving JSON files.
> JSON File Changes

- nw/gui/doceditor.py
- nw/gui/docviewer.py
This PR adds callable function to update the colours on document headers and footers, as well as the document background and text. This allows the user to switch syntax theme without having to restart novelWriter.
> Fix Syntax Theme Switching

- nw/core/project.py
- nw/gui/doceditor.py
- nw/gui/projtree.py
- nw/guimain.py
- tests/nwdummy.py
This PR fixes a few minor issues and inconsistencies when triggering menu or keyboard shortcut actions with no project or document open. Some actions were triggering even when there is no project, like the split and merge tools, the backup tool, and a few other functions. In addition, all the insert menu entries still worked even with no document open. The inserts were written to the read only dummy document that is always present.
None of these actions caused any issues. All of them were managed by other parts of the logic, but with these changes they're blocked at the very root of the action and doesn't progress to the first steps before realising there is no project or document to apply the tools or features to.
In some cases, they were handled at the root, but now they also all print …
> Action fixes for no project or document open

- nw/gui/custom.py
- nw/gui/doceditor.py
- nw/gui/docviewer.py
- nw/gui/itemeditor.py
This PR is a fix to issue #499, where the headers and footers in the editor and viewer were clipped on high-DPI monitors. This was caused by the size hint of the underlying widget not scaling with the monitor. A minimum height requirement is now calculated based on the height of the label and a fixed margin that is manually scaled by the UI scale factor. This forces a minimum size that is big enough to always show the content.
In the same PR, a few scaling issues with margins on high-DPI screens in the form layouts have been fixed as well.
> High DPI Header & Footer Scaling

- nw/__init__.py
- nw/gui/mainmenu.py
A few minor updates to the main menu:
* Rename "Keywords and Tags" to "Tags and References"
* Add menu entry to open the GitHub releases page
> Menu Updates

- nw/gui/projtree.py
The context menu for the project tree did not have the "New File" option for the "Outtakes" folder, although a new file could be created from the main menu or through keyboard shortcut. This was inconsistent. The "New File" option has now been enabled in the context menu as well. Although there shouldn't be a reason to make a new file in Outtakes if the folder is used only for actual outtakes, the user may want to use this special folder differently.
This PR closes #517.
> Allow creating files in the 'Outtakes' root folder

- nw/gui/mainmenu.py
- nw/guimain.py
- sample/nwProject.nwx
This fixes a minor issue with the checkbox next to the "Distraction free Mode" entry in the menu. The checkbox would toggle when the menu entry was clicked, but not when the document header button was used. The toggle is now handled manually by the function that handles the two modes, and the toggling of the check mark by the Qt library is bypassed.
> Fix the Focus Mode checkbox not updating in the menu

- CONTRIBUTING.md
This PR fixes some minor typo/wrong word errors I observed while reading the contributing guidelines.
Thank you Veronica for sharing novelWriter as Free Software.  :-)
> Fix minor typos in Contributing guidelines

- docs/source/int_interface.rst
- docs/source/int_started.rst
- docs/source/write_export.rst
- docs/source/write_notes.rst
- docs/source/write_projects.rst
- docs/source/write_structure.rst
This MR includes a number of fixes for minor typos and grammar errors.  Some of these tend towards being very nit-picky.  Some are hard to see, such as the addition of a period, or change of a single character.  Please feel free to incorporate some, all, or none of these suggested changes.
I was pleasantly surprised to find user documention which describes the novel structure with suggestions on how to use it when writing a novel.  I also appreciate reading the reasons for some of the design choices.  Because I was reading the documentation anyway, I thought I'd try to contribute some minor improvements at the same time.
Overall I like what you are doing with _novelWriter_.
I like that simple Markdown is used and that each layout type (chapter, plot, characters, etc.) is treated in a …
> Fix minor grammar and typo issues in documentation

- nw/constants/__init__.py
- nw/constants/constants.py
- nw/gui/itemeditor.py
- nw/gui/projtree.py
- nw/guimain.py
This PR makes a few changes to the Item Editor, and related code.
* The Archive root folder is now equal to the Novel root folder in terms of setting status and importance flags.
* Resizing the Item Editor dialog will expand the input boxes, as a user would expect, instead of increasing the empty space between label and input box.
* Some minor cleanup and removal of redundant variables in the Item Editor dialog itself, and the function that applies the changes in the Project Tree class.
> Item Editor fixes

- nw/core/project.py
- nw/gui/doceditor.py
- nw/gui/statusbar.py
- nw/guimain.py
This PR fixes a couple of minor issues:
* Changing the size of the document editor, whether it is by changing the window or one of the splitters, flags the document itself as changed. This is now handled. In addition, opening the last viewed document automatically when opening a project also triggered the document changed flag. This is now reset at the end of the open project function.
* When loading a project, the last project word count is loaded, however the current word count remains 0 until the first timed count is run. This value is now also set when the project is opened, and updated on the status bar. This both prevents the project changed flag from being flipped on first word count, and properly sets the word count on the status bar from the start.
> Doc and Project Modified Status

- docs/source/int_interface.rst
- docs/source/int_introduction.rst
- docs/source/int_started.rst
- docs/source/int_typography.rst
- docs/source/tech_technical.rst
- docs/source/write_export.rst
- docs/source/write_notes.rst
- docs/source/write_projects.rst
- docs/source/write_structure.rst
This PR fixes some typos, spelling and rewords parts of the documentation. It also extends the technical doc to describe the meta and cache content of the project folder.
> Spelling, typo, and wording update of the docs

- nw/core/index.py
When a document is indexed by the indexer class, the meta data is either saved to a novel index or a note index based on the layout of the document. However, if a document has its layout changed from one of the novel layouts to a note, or vice versa, the indexer will not clear the old data in the previous internal index.
This PR adds a clearing command to make sure the entry does not exist in the opposite index when the new entry is created in the new index.
> Duplicate index entry issue

- nw/gui/itemdetails.py
- nw/guimain.py
The details panel below the project tree is not cleared when a project is closed. This is just a cosmetic issue, but it is inconsistent with the rest of the GUi were all information is cleared.
> Backport from 1.1: clear project tree meta panel on close

- .github/workflows/test_mac.yml
- README.md
- docs/source/int_started.rst
This PR clarifies the install instructions, as discussed in #570.
> Issue #570: Clarify install instructions

- nw/core/index.py
- nw/core/options.py
- nw/gui/projdetails.py
- nw/guimain.py
- tests/test_core/test_core_index.py
- tests/test_gui/test_gui_projdetails.py
This PR makes a few improvements to the Contents tab on the Project Details dialog:
* Remove indentation of chapter titles, and instead make non-chapter titles stand out by using bold, italic and underline.
* Allow the user to select which page is the first page to start counting from. The preceding pages are then counted with roman numbers as is customary in front matter, and the story progress column ignores these pages.
> Improve Project Details

- .github/workflows/syntax.yml
- docs/source/int_interface.rst
- nw/gui/mainmenu.py
- nw/gui/projdetails.py
- nw/guimain.py
This adds `Alt+4` as a shortcut to change focus to the Outline view, and also switches the main window tab when required by focus shift.
This resolves issues #609 and #612.
> Issue #612: Change Focus

- nw/gui/doceditor.py
This resolves #608 which describes an issue with opening a blank document and no cursor being visible when the editor has focus.
I did not manage to find out why this happens. Presumably, some action by novelWriter causes the cursor to not show. I added a simple hack that will add a line break and remove it again if the opened document is empty. This brings back the cursor. However, it doesn't work if the blank document is opened automatically when the application is launched. The latter is why I expect it is caused by a conflict with some other internal feature. Still, fixing it for when the user manually opens a blank document solves it in 99% of cases, and it's probably good enough.
If I figure out exactly what is causing this, I'll make a better fix.
> Issue #608: Missing Cursor

- nw/gui/projload.py
This PR fixes an old issue that I've seen before, but never quite managed to catch and track down.
Essentially, if you have one project open, and then open another project from the "Open Project" dialog, and then open that dialog again, the last opened project will replace the entry for the one before. The underlying data is correct, but the record of recent projects is updated both when you open and close a project. The sorting algorithm uses the timestamp of these events to sort the list. The resolution of these timestamps is 1 second, so the closing of one, and opening of the next, will have the same timestamp as they happen within milliseconds of each other -- provided the "ask before backup" option isn't on. The last one in the recent list would then occupy both slots, as the lookup …
> Fix "Open Project" list sorting issue

- nw/gui/doceditor.py
- nw/gui/projtree.py
This PR makes the following changes:
* Adds the document layout and class to the left of the document editor footer bar.
* Adds the feature from #530, where a newly created file is populated with a header of a level appropriate for the file layout and a header text from the item label.
> Various Improvements

- nw/gui/projtree.py
- tests/test_gui_doceditor.py
- tests/test_gui_projtree.py
Block `Ctrl` + `Del` when project tree does not have focus.
> Issue #629: ctrl del action

- nw/constants/constants.py
- nw/core/index.py
- nw/gui/doceditor.py
- nw/gui/noveltree.py
- tests/conftest.py
- tests/dummy.py
- tests/test_core/test_core_index.py
- tests/tools.py
This PR adds the following:
* An index function to get word counts for all headers in a file.
* An index function to get all headers from a file.
* A headers record in the document editor that is set when loading, and updated when saving.
* A function in the editor that checks if the header levels have changed and pushes a refresh of the novel tab tree if it has.
* A function in the novel tab tree that updates word counts for headers of a specific file.
The headers record in the document editor can also be used to display an outline for the open file. This may be useful to add at some point. Even as a simple dropdown box with all headers listed.
This PR resolves #636.
> Issue #636: Novel Tab Word Count

- nw/gui/writingstats.py
- tests/test_gui/test_gui_writingstats.py
The session log file actually logs the total word count for each entry, not the change in words. The writing stats dialog calculates the difference and list the change in word count per row. However, when the negative word counts are filtered out, the difference displayed in the next positive word count row is calculated from the difference from before the skipped row, so the total count may no longer actually be positive.
Example:
Day 1: +2000 words
Day 2: -500 words
Day 3: +1500 words
Filtering out the negative would then show:
Day 1: +2000 words
Day 3: +1000 words
With this change, it instead shows:
Day 1: +2000 words
Day 3: +1500 words
This makes more sense, but it also means that the sum of rows no longer matches the total word count if negative counts are excluded. But that is sort …
> Make writing stats word calculation more intuitive

- nw/assets/icons/fallback/status_idle-dark.svg
- nw/assets/icons/fallback/status_idle.svg
- nw/config.py
- nw/core/options.py
- nw/core/project.py
- nw/gui/doceditor.py
- nw/gui/preferences.py
- nw/gui/statusbar.py
- nw/gui/theme.py
- nw/gui/writingstats.py
- nw/guimain.py
- tests/reference/baseConfig_novelwriter.conf
- tests/reference/guiPreferences_novelwriter.conf
- tests/test_core/test_core_project.py
- tests/test_gui/test_gui_writingstats.py
This PR adds code to keep track of idle time during a writing session. The idle time is recorded as a seventh column in the session log file and displayed as a new column in the Writing Stats dialog.
> Session Idle Time

- nw/gui/writingstats.py
- tests/test_gui/test_gui_writingstats.py
The total idle time when grouping writing statistics by day was summed up wrong. This fixes the calculation and updates the test to check these values correctly.
> Fix idle Time in Writing Stats

- nw/constants/__init__.py
- nw/constants/constants.py
- nw/core/options.py
- nw/core/tohtml.py
- nw/core/tokenizer.py
- nw/core/toodt.py
- nw/gui/build.py
- nw/gui/docviewer.py
- tests/reference/guiBuild_Tool_Step1_Lorem_Ipsum.htm
- tests/reference/guiBuild_Tool_Step2_Lorem_Ipsum.htm
- tests/reference/guiBuild_Tool_Step3_Lorem_Ipsum.htm
- tests/reference/guiBuild_Tool_Step4H_Lorem_Ipsum.json
- tests/reference/guiBuild_Tool_Step4_Lorem_Ipsum.htm
- tests/test_core/test_core_tohtml.py
- tests/test_core/test_core_tokenizer.py
- tests/test_gui/test_gui_build.py
This PR:
* Updates and cleans up the Build Novel Project tool.
* Adds controls for new features, like line height and replacing Unicode characters with HTML entities.
* Removes the markdown export code from the `ToHtml` class as it now belongs in `ToMarkdown`.
* Applies line height and text margins to the HTML format as well. These were added for the ODT export.
* Rewrites the way replacing characters, mainly for HTML export, is handled. This includes a new Unicode to HTML map in the constants module.
> Build Tool Updates

- nw/core/spellcheck.py
- tests/test_core/test_core_spell.py
It turns out the difflib that is used for simple spell checking can accept any hashable, iterable object as the check list. This PR changes the loaded dictionary from a list to a set, which is pre-hashed, making lookups significantly faster. Spell checking a large file with the simple checker is now an order of magnitude faster.
> Simple Spell Check Speedup

- nw/core/index.py
- nw/core/project.py
- tests/test_core/test_core_project.py
There is no point logging a writing session where the user just opened the project and closed it again without making any changes.
This PR adds a check to the session entry code skip appending a line if the session was shorter than 5 minutes and no word count difference was recorded. Both conditions must be true.
> Drop short sessions from the log file

- nw/common.py
- nw/config.py
- nw/gui/custom.py
- nw/gui/preferences.py
- nw/gui/projsettings.py
- tests/reference/baseConfig_novelwriter.conf
- tests/reference/guiPreferences_novelwriter.conf
- tests/test_gui/test_gui_projsettings.py
This PR tries to improve the layouts used for preferences dialogs to be more responsive to labels and texts of various lengths due to translations. The help labels on these forms now wrap, and various aspects of the form layout expands and tries to fit the content better. When there is no room, the text is clipped, but the dialogs can generally be resized.
> Make settings layouts more responsive

- nw/core/index.py
This PR prevents the note reference parser of the index to save misspelled keywords into the index dictionary. The indexer function was checking a few things, but not that the keyword is allowed. The wrongly indexed keyword would then be written to file.
For the 1.1.1 version, this isn't an issue as the index is not checked that closely on loading, and the wrroneus keyword is filtered out. Although in 1.1 it would cause a crash.
For 1.2 and the current `dev` branch, the extended index validator would pick up this when the index was loaded, and deem the index broken and rebuild it. However, this would happen every time the project was launched.
This resolves #688.
> Issue #688: Indexing of invalid keywords

- i18n/nw_en_US.ts
- i18n/nw_fr.ts
- i18n/nw_nb_NO.ts
- i18n/nw_pt.ts
- nw/__init__.py
- nw/gui/about.py
The main point of this PR is to add translation credit to the About novelWriter dialog, but at the same time it reformats the entire Credits section and wraps the entries in html tables. The column order of the tables are fixed, but generated by a single function, so if this needs to be modified for localisation, it can be handled there.
> About dialog updates

- docs/source/usage_interface.rst
- nw/constants/enum.py
- nw/gui/doceditor.py
- nw/gui/mainmenu.py
- nw/guimain.py
- tests/test_gui/test_gui_doceditor.py
Resolves #708 
The hasFocus check for document actions was blocking search action from the search bar when the search bar had focus. This PR bypasses the whole docAction pipeline and lets the menu hook directly into the four search and replace related functions. The search bar does the same.
The remaining docAction calls still require that the editor has focus, but the focus check has been moved to the main GUI wrapper function that decides whether a document action from the menu is sent to the viewer or editor. It makes more sense to keep them in one place.
> Issue #708: Search bar focus

- docs/source/setup_linux.rst
- docs/source/setup_mac.rst
This PR clarifies the setup instructions for Linux. The instructions now meantion that `setuptools` must be installed in order to run the optional step `./setup.py install` and clarifies the difference between user space install and system wide install.
The macOS instructions have been updated to match.
This hopefully resolves #714.
> Issue #714: Linux Setup

- nw/constants/__init__.py
- nw/constants/enum.py
- nw/gui/doceditor.py
- nw/gui/mainmenu.py
- nw/guimain.py
- tests/test_gui/test_gui_doceditor.py
- tests/test_gui/test_gui_mainmenu.py
This PR resolves #716, both in terms of the original request for the Search menu shortcuts to work in Focus Mode and in the mentioned bug discovered when closing a document while in Focus Mode.
The PR changes the following:
* All menu actions with shortcuts in the Search menu now also work in Focus Mode,
* The `setFocus` function in the main GUI class has been renamed to `switchFocus` as it overloads another function otherwise.
* The Edit/Search/Close buttons in the document header are no longer hidden when entering Focus Mode from the header button. They were not hidden when Focus Mode was activated from the main menu. The behaviour was thus inconsitent.
* Closing the document while in Focus Mode now automatically disables Focus Mode.
* The document header Focus Mode button now switches …
> Issue #716: Focus Mode Improvement and Bugfix

- .gitignore
- setup.py
Make sure the novelWriter.pyw file exists on win-install from a source package.
Resolves #727
> Fix Win-Install from Source

- nw/core/spellcheck.py
This PR fixes an issue where the project dictionary variable was not set in the spell checker class when the file didn't already exist. The variable *must* be set, otherwise the words aren't saved, only added to the current session.
This resolves #733.
> Fix failed initial project dictionary

- i18n/nw_en_US.ts
- i18n/nw_fr.ts
- i18n/nw_nb_NO.ts
- i18n/nw_pt.ts
- nw/core/document.py
- nw/core/index.py
- nw/core/project.py
- nw/core/tohtml.py
- nw/core/tokenizer.py
- nw/core/tomd.py
- nw/core/toodt.py
- nw/dialogs/docmerge.py
- nw/dialogs/docsplit.py
- nw/dialogs/itemeditor.py
- nw/dialogs/preferences.py
- nw/dialogs/projsettings.py
- nw/dialogs/quotes.py
- nw/dialogs/wordlist.py
- nw/gui/doceditor.py
- nw/gui/docviewer.py
- nw/gui/projdetails.py
- nw/gui/projtree.py
- nw/guimain.py
- nw/tools/build.py
- nw/tools/writingstats.py
- tests/test_core/test_core_document.py
- tests/test_core/test_core_index.py
- tests/test_core/test_core_tohtml.py
- tests/test_core/test_core_tokenizer.py
- tests/test_core/test_core_toodt.py
This PR:
* Makes class initialisation consistent. Since the `GuiMain` and `NWProject` classes have a reference to each other, none of the other classes need a reference to both. Some classes extracted one from the other, but this has now been made consistent such that all data classes only get the `NWProject` reference and all GUI classes only get the `GuiMain` reference.
* The duplicate error message generated in `NWIndex` has been removed. It was also not translated.
* The status bar message written from the `NWDoc` class on document open and save are now generated from the `GuiDocEditor` class instead since the `showStatus` flag that disables it was used on every other call to the open function. The flag has now been removed as well.
* The `NWDoc` functions `openDocument` and …
> Class Cleanup

- nw/core/index.py
If the index cache file was broken, novelWriter would generate two alert boxes telling the user the index is broken. One from within the index class and one from the main gui. The former has been removed. It was also not included in the translation files.
> Remove duplicate error message in index class

- .github/workflows/test_linux.yml
- docs/source/int_started.rst
- i18n/README.md
- nw/config.py
- setup.py
The function called was only added in Qt 5.15: https://doc.qt.io/qt-5/qtranslator.html#filePath
~~Also add a GitHub action to run the tests under minimum package dependencies to try to detect such bugs early.~~
The old package setup doesn't really work because the test environment isn't designed for outdated packages. Need to run a virtualbox locally instead.
Resolves #773
> Issue #773: Fix QTranslate() filePath issue

- nw/core/tree.py
- nw/guimain.py
- tests/test_core/test_core_tree.py
This PR fixes a minor issue with the new prorject generator asking for new file handles so fast that the clock resolution becomes a problem when on Windows. Collisions of handles is handled, but it causes a warning. This is solved by adding a counter to the time stamp used for generating handles.
This PR also removes an error message printed when generating a new project.
This resolves #769.
> Issue #769: Generating handles on Windows

- setup.py
We're no longer making a desktop icon on Linux when running the xdg-install command, but we should still remove the old icon if it exists as it may no longer work after an update.
This may relate to issue #778
> Add entry in xdg-install to remove old desktop icon

- docs/source/usage_interface.rst
- nw/gui/mainmenu.py
The keyboard shortcuts for switching focus widget on Windows should be changed from `Alt+1` etc to `Ctrl+Alt+1` etc. The former interferes with Windows alt codes.
This relates to issue #740.
> Focus keys

- nw/core/item.py
- tests/test_core/test_core_item.py
Loading a project file from another version could potentially cause all items to be orphaned because the XML entry for an item contains an unknown tag. This is unnecessary, Unknown tags should just be silently ignored.
> Make XML parser for items less picky

- nw/core/tohtml.py
- nw/core/tokenizer.py
- tests/test_core/test_core_tohtml.py
- tests/test_core/test_core_tokenizer.py
**Summary:**
Move the replacement of `<` and `>` brackets for HTML to after the tokenizer step has been run. This avoids the need to parse formatting codes for HTML replacements in addition to regular brackets.
This is likely to be slower for HTML export and preview. In the former case, it doesn't really matter, and in the latter case the difference is trivial for regular sized documents.
None
**Checklist:**
> Html encoding

- .github/pull_request_template.md
- .github/workflows/syntax.yml
- .github/workflows/test_linux.yml
- .github/workflows/test_mac.yml
- .github/workflows/test_win.yml
- CONTRIBUTING.md
- README.md
- requirements-dev.txt
**Summary:**
The GitFlow-based branching model used in this repo is a bit clunky, so I've decided to change it to the OneFlow model. Due to this, some minor changes have to be made to the repo and a few of the readmes.
**Checklist:**
> Change the branching model

- nw/gui/custom.py
- nw/guimain.py
**Summary:**
At some point it seems there has been a change in when a widget's contents margin values are defined because the PagedDialog class suddenly started setting all margins to 0. These are now forced to use the QLayout default margins.
> Fix layout margins on paged dialogs

- nw/guimain.py
- tests/test_base/test_base_error.py
**Summary:**
Adds a dialog box warning the user to be careful when using novelWriter alpha versions to work on a live project.
> Add a warning when opening novelWriter alpha version

- requirements.txt
- setup.cfg
**Summary:**
The minimum required version for PyQt5 is stated in requirements.txt and setup.cfg to be 5.2.1, but the code itself checks that it's at least 5.3.
> PyQt5 minimum version requirement consistency

- nw/guimain.py
**Summary:**
Rebuilding the index should also update the document icons.
> Fix issue with icons not updating when index is rebuilt

- CHANGELOG.md
- docs/source/index.rst
- docs/source/usage_fileformat.rst
- docs/source/usage_projectformat.rst
- nw/core/project.py
**Summary:**
This PR adds a chapter in the documentation about the file format changes for project files. This is only really necessary for 1.3 as this requires some minor attention by the user. An info box has also been added to the project class to alert the user to check the documentation when first upgrading a project to 1.3 format.
> Add project format documentation and popup box

- .gitignore
- docs/source/int_started.rst
- nw/config.py
- nw/gui/mainmenu.py
- nw/guimain.py
- setup.py
- tests/test_base/test_base_config.py
**Summary:**
This PR changes how the local copy of the documentation is built and handled. The build for the Qt Assistant has been dropped in favour of a local copy of the HTML documentation. Opening the docs from the Help menu will first check if it can access the online documentation. If it cannot, ir will try to open the local copy instead.
> Include HTML docs in minimal installs

- nw/__init__.py
- tests/test_base/test_base_init.py
**Summary:**
This patch sets a unique app id for the Python process hosting novelWriter on Windows such that the correct icon will show up on the Windows taskbar, not the Python icon.
Resolves #860
> Taskbar icon on windows

- nw/gui/mainmenu.py
**Summary:**
The help menu entry for opening documentation should point to "stable" for stable release, and otherwise to "latest".
> Make Help select correct version of docs

- README.md
- docs/source/index.rst
- docs/source/setup_linux.rst
- docs/source/setup_other.rst
- setup.py
- setup/debian/control
- setup/debian/copyright
- setup/make_pip.sh
- setup/make_release.sh
**Summary:**
This PR primarily adds support for making `.deb` packages for [launchpad.net](https://launchpad.net/). This makes installing and updating novelWriter on Ubuntu and Debian significantly easier.
> Add PPA support

- novelwriter/common.py
- novelwriter/core/document.py
- novelwriter/gui/doceditor.py
- novelwriter/guimain.py
- tests/test_base/test_base_common.py
- tests/test_core/test_core_document.py
**Summary:**
This PR adds a hash check when opening and saving document files. This is used to check that the file has not been altered on disk since it was last saved. If it has, a dialog box pops up to ask if the user wants to overwrite the file.
Resolves #878
> Hash check on documents

- novelwriter/gui/doceditor.py
- tests/test_gui/test_gui_doceditor.py
- tests/test_gui/test_gui_guimain.py
**Summary:**
This PR adds a second word counter in the document editor that is activated when there is an active text selection. It is deactivated when there is no selection. When it is active, the word counter in the document footer changes from counting the whole document to only counting the selected text. The label changes from something like "Words: 100 (+50)" to "Words: 25 selected".
This resolves #896
> Selected words counter

- docs/source/setup_linux.rst
**Summary:**
Fixes an erroneous path in the list of commands to run to set up the Launchpad PPA on Debian.
> Fix error in Debian setup instructions

- i18n/pylupdate6/README.md
- i18n/pylupdate6/__init__.py
- i18n/pylupdate6/lupdate.py
- i18n/pylupdate6/python_source.py
- i18n/pylupdate6/source_file.py
- i18n/pylupdate6/translation_file.py
- i18n/pylupdate6/translations.py
- i18n/pylupdate6/user.py
- setup.py
- setup/debian/copyright
**Summary:**
The `pylupdate5` tool used to generate translation files is stuck on an older TS file format. The equivalent tool in PyQt6 is up to date, but has not been backported. This PR adds the necessary source code to the `i18n` folder, which the setup script will pull when updating the TS files.
Issue discussed in #911
> Add pylupdate6 tool to i18n

- .readthedocs.yml
- docs/source/requirements.txt
**Summary:**
Fixes docs build error, but solution is unsatisfactory as it requires pinning the version of `docutils`.
See https://github.com/sphinx-doc/sphinx/issues/9777
> Fix docs build issues

- i18n/nw_en_US.ts
- i18n/nw_fr.ts
- i18n/nw_nb_NO.ts
- i18n/nw_pt.ts
- i18n/nw_zh_CN.ts
- novelwriter/__init__.py
- novelwriter/common.py
- novelwriter/config.py
- novelwriter/core/document.py
- novelwriter/core/options.py
- novelwriter/core/project.py
- novelwriter/dialogs/preferences.py
- novelwriter/error.py
- novelwriter/gui/mainmenu.py
- novelwriter/guimain.py
- novelwriter/tools/build.py
- novelwriter/tools/writingstats.py
- setup.py
- tests/mock.py
- tests/test_base/test_base_common.py
- tests/test_core/test_core_options.py
- tests/test_tools/test_tools_projwizard.py
- tests/tools.py
**Summary:**
Various code and GUI cleanups:
* Move some int checking functions to the common module.
* Change how runtime errors are reported and printed.
* Some minor changes to initialisation.
* Add a `skipif` entry for the wizard test on macOS (segfaults in Qt).
* Fix a typo on the Preferences dialog.
* Drop descriptions of menu path in various help texts.
* Improve the help text in the Format menu.
* Minor rewording of a few dialogs.
Closes #923
> Code and GUI text cleanup

- novelwriter/core/tohtml.py
- tests/test_core/test_core_tohtml.py
**Summary:**
When the greater than or lesser than symbols are used before a formatted piece of text, the html converter places the html tags in the wrong location due to the expansion of `<` to `&lt;` and `>` to `&gt;`, which shifts the rest of the string three characters.
The previous plain replace function is here replaced by a for loop that also shifts the formatting positions calculated by the Tokenizer class. Unfortunately, this is likely to be a bit slower, but it can't really be helped.
Test coverage has been added for these special cases.
Resolves #929 
> Fix greater/lesser symbol bug

- novelwriter/config.py
- novelwriter/core/document.py
- novelwriter/core/index.py
- novelwriter/core/options.py
- novelwriter/core/project.py
- novelwriter/core/spellcheck.py
- novelwriter/core/tree.py
- novelwriter/dialogs/wordlist.py
- novelwriter/error.py
- novelwriter/gui/docviewer.py
- novelwriter/gui/theme.py
- novelwriter/tools/build.py
- novelwriter/tools/writingstats.py
- tests/mock.py
- tests/test_core/test_core_document.py
**Summary:**
This PR updates how errors are logged, and fixes two cases of mutable iterables as default values in function parameters. The latter is not safe as these are initialised on first call and will not be recreated on further calls, potentially causing unintende behaviour.
> Error logging and mutables as function defaults

- novelwriter/core/index.py
- novelwriter/core/item.py
- novelwriter/core/project.py
- novelwriter/core/tokenizer.py
- novelwriter/core/tree.py
- novelwriter/gui/docviewer.py
- novelwriter/gui/projtree.py
- novelwriter/guimain.py
- tests/test_core/test_core_index.py
- tests/test_core/test_core_item.py
- tests/test_core/test_core_tree.py
- tests/test_dialogs/test_dlg_itemeditor.py
- tests/test_gui/test_gui_doceditor.py
- tests/test_gui/test_gui_projtree.py
**Summary:**
Make the interface of the NWItem class tighter such that accidental changes to the project items are harder to make. Also add some more convenience functions to the NWTree class.
> Tighten up the item class

- novelwriter/config.py
- novelwriter/dialogs/preferences.py
- novelwriter/gui/doceditor.py
- novelwriter/gui/docviewer.py
- tests/reference/baseConfig_novelwriter.conf
- tests/reference/guiPreferences_novelwriter.conf
- tests/test_base/test_base_config.py
- tests/test_dialogs/test_dlg_preferences.py
**Summary:**
Remove the switch to enable/disable fixed text width in editor and instead allow the user to set the value to 0 to disable it. Also apply the max width setting to the document viewer.
Resolves #924
> Text width

- novelwriter/gui/noveltree.py
- novelwriter/gui/outline.py
- novelwriter/guimain.py
- tests/test_gui/test_gui_guimain.py
- tests/test_gui/test_gui_mainmenu.py
- tests/test_gui/test_gui_noveltree.py
- tests/test_gui/test_gui_outline.py
**Summary:**
This PR alters how the Enter, Return and Ctrl+O shortcuts work. They will now open the selected document in the Project Tree, Novel Tree, or Project Outline, depending on which of these trees have focus.
Resolves #913
> Apply open document shortcuts to the tree that has focus

- novelwriter/gui/doceditor.py
**Summary:**
PR #946 was missing a line that ensured that the document footer's line counter was updated when the user skips through the document with the search tool.
Also in this PR is a bunch of corrections and updates to various docstrings.
> Fix line number update when searching

- novelwriter/core/tohtml.py
- novelwriter/gui/docviewer.py
- tests/test_core/test_core_tohtml.py
- tests/test_gui/test_gui_docviewer.py
**Summary:**
The HTML rendering fails if a text line that is not a plain text paragraph contains a < or > symbol. It tries to iterate over a None object instead of a list of formats.
Resolves #950
> Resolve HTML render bug

- docs/source/project_overview.rst
- docs/source/project_structure.rst
- docs/source/usage_interface.rst
- i18n/nw_base.ts
- novelwriter/constants.py
- novelwriter/core/project.py
- novelwriter/dialogs/preferences.py
- novelwriter/dialogs/projdetails.py
- novelwriter/dialogs/projsettings.py
- novelwriter/dialogs/wordlist.py
- novelwriter/gui/doceditor.py
- novelwriter/gui/mainmenu.py
- novelwriter/gui/projtree.py
- novelwriter/guimain.py
- novelwriter/tools/build.py
- novelwriter/tools/projwizard.py
- sample/content/8a5deb88c0e97.nwd
- sample/nwProject.nwx
- tests/reference/coreProject_NewCustomA_nwProject.nwx
- tests/reference/coreProject_NewCustomB_nwProject.nwx
- tests/test_core/test_core_index.py
**Summary:**
This PR removes a lot of GUI text. There were a number of redundant tooltips. That is, tooltips that say exactly the same as the GUI element says. That includes every status bar message from hovering over menu entries. Some dialog boxes have been removed or merged with other boxes. In addition, the class name labels have been split into singular and plurals.
> Clean up GUI text

- novelwriter/core/index.py
- novelwriter/core/project.py
- novelwriter/guimain.py
- tests/test_core/test_core_index.py
- tests/test_gui/test_gui_docviewer.py
- tests/test_gui/test_gui_noveltree.py
**Summary:**
This PR adds an automatic rebuild of the project index if not all files in the project's content folder are present in the index when the index is opened. The list of files is registered in the project class when the scan is performed.
Resolves #957
> Add automatic index rebuild

- docs/source/index.rst
- docs/source/int_introduction.rst
- docs/source/setup_linux.rst
**Summary:**
Adds a new section on the introduction page of the documentation with a couple of paragraphs on how projects are stored. This includes a warning about not editing the content of the project folder, and a note on volatile file systems related to issue #960.
Also adds a note about using the Launchpad repos on Debian. Only the Ubuntu 20.04 and earlier `.deb` files work do to a change in compression format in more resent Ubuntu releases that Debian does not (currently) support.
Resolves #956
Resolves #960
> Update docs on install and project storage

- sample/nwProject.nwx
- setup.py
**Summary:**
Launchpad no longer accepts Ubuntu 21.04 packages,
> Remove Ubuntu 21.04 release and add 22.04

- novelwriter/error.py
**Summary:**
The critical error dialog window was missing a window title, so why not make it a Discworld reference for PR #1000!
> Add Out of Cheese Error

- .github/workflows/test_linux.yml
- .github/workflows/test_mac.yml
- .github/workflows/test_win.yml
- README.md
- docs/source/int_started.rst
- novelwriter/__init__.py
- novelwriter/common.py
- novelwriter/core/toodt.py
- novelwriter/tools/writingstats.py
- setup.cfg
- setup/debian/control
- setup/description_pypi.md
- tests/test_base/test_base_common.py
**Summary:**
Python 3.6 reached end of life on December 23rd, 2021. This PR removes all mentions of Python 3.6 support and drops testing against a 3.6 environment. Since 3.6 is dropped, the couple of places were custom code was used to avoid using 3.7 features have been updated.
> Drop support for Python 3.6

- .github/workflows/syntax.yml
- setup.cfg
- setup.py
**Summary:**
* Updates linting to ignore E133 in favour of the mutually exclusive E123, and W503 in favour of W504.
* Drop making releases for Ubuntu 18.04, which only comes with Python 3.6.
Resolves #1005
> Update linting settings, and drop Ubuntu 18.04 releases

- .github/workflows/syntax.yml
- .github/workflows/test_linux.yml
- .github/workflows/test_mac.yml
- .github/workflows/test_win.yml
- novelwriter/gui/doceditor.py
- tests/test_gui/test_gui_doceditor.py
**Summary:**
This issue fixes a case where a search triggers an infinite loop. It is caused by the QTextEdit returning True that a search was made, but does not select a text result. This causes an infinite loop in the search result counter. The loop will now break in such a case, and a cap has also been set on the number of search results to 1000. More results will in any case make the GUI sluggish on slower systems.
Resolves #1015
> Fix infinite search loop bug

- novelwriter/core/index.py
**Summary:**
Empty files were not covered by the rebuild index feature, so they would trigger the auto-rebuild every time the project was opened.
Resolves #1020
> Make sure empty files are indexed

- novelwriter/core/document.py
**Summary:**
When a new file is created the shasum function reports an error as it tries to compute the shasum of a file that not yet exists. This PR moves the call into the if-check for file existence to avoid the error message,
Resolves #1021
> Only compute shasum of file if it exists

- novelwriter/core/item.py
- novelwriter/core/project.py
- tests/reference/guiProjSettings_Dialog_nwProject.nwx
- tests/test_core/test_core_item.py
**Summary:**
Since XML doesn't handle multiple spaces in text in a predictable manner, the item labels should use the new `simplified` function on all text labels. The same should apply to other user-defined strings in the project.
> Simplify text labels in XML

- novelwriter/dialogs/preferences.py
**Summary:**
The text on the Preferences panel on highlighting multiple or trailing spaces was incomplete.
Resolves #1043
> Fix the redundant spaces highlight option text in Preferences

- novelwriter/gui/projtree.py
- tests/test_gui/test_gui_projtree.py
**Summary:**
Since PR #1047 allows moving whole folders to Trash, we may as well allow deleting folders with content.
> Allow deleting non-empty folders

- novelwriter/core/item.py
**Summary:**
This PR adds some checks to the loading of project items from XML to check that certain settings are consistent.
> Force consistency of item settings

- novelwriter/gui/projtree.py
- tests/test_gui/test_gui_projtree.py
**Summary:**
Deleting an empty folder should not go through Trash. It can be deleted directly.
Resolves #1052
> Quick delete empty folders

- novelwriter/tools/projwizard.py
- tests/test_tools/test_tools_projwizard.py
**Summary:**
This PR adds a simple check for valid path to the New Project Wizard. It isn't perfect, but it will eliminate most cases where the Wizard is completed but the new project not created due to issues with the path.
This PR also rewrites the tests for the wizard.
Resolves #1058
> Add valid path check to new project wizard

- novelwriter/core/project.py
- novelwriter/gui/projtree.py
- novelwriter/guimain.py
- novelwriter/tools/projwizard.py
- tests/reference/coreProject_NewCustomA_nwProject.nwx
- tests/reference/coreProject_NewCustomB_nwProject.nwx
- tests/reference/coreProject_NewFile_nwProject.nwx
- tests/reference/coreProject_NewMinimal_nwProject.nwx
- tests/reference/coreProject_NewRoot_nwProject.nwx
- tests/reference/guiEditor_Main_Final_nwProject.nwx
- tests/reference/guiEditor_Main_Initial_nwProject.nwx
- tests/reference/guiProjSettings_Dialog_nwProject.nwx
- tests/test_core/test_core_index.py
- tests/test_core/test_core_project.py
- tests/test_dialogs/test_dlg_docmerge.py
- tests/test_dialogs/test_dlg_docsplit.py
- tests/test_dialogs/test_dlg_itemeditor.py
- tests/test_dialogs/test_dlg_projsettings.py
- tests/test_gui/test_gui_guimain.py
- tests/test_gui/test_gui_mainmenu.py
- tests/test_gui/test_gui_projtree.py
- tests/test_gui/test_gui_statusbar.py
- tests/test_tools/test_tools_lipsum.py
- tests/test_tools/test_tools_projwizard.py
- tests/test_tools/test_tools_writingstats.py
- tests/tools.py
**Summary:**
This PR updates how new projects are created after most of the restrictions on project structure have been removed. The changes include:
* Rename the "Working Title" label on the Project Wizard to "Project Name", which is more accurate.
* Update the detailed options page of the wizard to reduce the number of root folders listed, add an option to generate sample note files, and remove the option to generate chapter folders.
* Update the final page of the wizard to show a summary of all choices made.
* Update the new project generator method to reflect the changes made on the Project Wizard.
* Drop the creation of a chapter folder for a "Minimal Project".
* Automatically add the Archive folder to all new projects, and also the trash folder for custom projects.
* Update tests to …
> Update new project creation

- setup/data/x-novelwriter-project.xml
Adds the icon name to the mimetype XML, but it still doesn't seem to load on newer versions of Nautilus. Works in other file explorer tools.
> Add icon name to xdg mime type just in case

- novelwriter/tools/build.py
**Summary:**
Fix build language not being forwarded to the ODT document class.
Closes #1073
> Set build language for Open Document files

- novelwriter/core/project.py
- tests/test_core/test_core_project.py
**Summary:**
This PR reduces the complexity of the old converter from version 1.0 to 1.1 project data structure. It still converts, but it doesn't do all the complicated cleanup logic and all the translated detailed messages have been replaced with a single error.
> Simplify the conversion of very old project data

- setup.py
- setup/data/novelwriter.desktop
- setup/description_short.txt
- setup/novelwriter.appdata.xml
**Summary:**
Adds a `build-appimage` command to the setup.py that builds off the existing `build-debian` command to package the source and then writes the appropriate metadata files to a `dist_appimage` directory.
requires `python-appimage` package to be installed via pip to succeed.
#1091 
> Appimage Distribution

- .github/workflows/test_linux.yml
- novelwriter/config.py
- novelwriter/core/spellcheck.py
- novelwriter/gui/doceditor.py
- tests/test_core/test_core_spellcheck.py
- tests/test_gui/test_gui_guimain.py
**Summary:**
The pyenchant package will accept an empty string as a language tag when requesting a dictionary, but the returned object will raise errors. See issue #1096.
This PR fixes this issue, and cleans up the way the dictionary object is set up. Test coverage is also improved.
Closes #1096
> Fix handling of empty spellcheck language string

- novelwriter/gui/doceditor.py
- tests/test_gui/test_gui_doceditor.py
**Summary:**
The feature used for some languages, like French and Spanish, to automatically add spaces before some characters, should not run for colon when the colon is used for a meta data tag or in the synopsis keyword.
This PR adds a check for that. The check is only run in the cases were the feature is triggered on a keypress.
Closes #1090
> Block adding spaces before colon in certain meta data cases

- CHANGELOG.md
- sample/nwProject.nwx
- setup.py
- setup/make_release.sh
**Summary:**
Various improvements to the build pipelines in `setup.py`:
* A command has been added to clear all previously built assets.
* Instead of building assets for each repeated build, it is just required that they exist. This prevents failed assets build from resulting in missing assets in the packages.
* Explicitly clear and rebuild assets in the main build script. This ensures that the files put into the packages are fresh.
* Rename the setup.exe installer for Windows to also include the version of the embedded Python.
> Improve the build scripts

- novelwriter/core/index.py
- novelwriter/core/item.py
- novelwriter/core/project.py
- novelwriter/core/tree.py
- novelwriter/dialogs/docmerge.py
- novelwriter/dialogs/docsplit.py
- novelwriter/gui/itemdetails.py
- novelwriter/gui/projtree.py
- novelwriter/tools/build.py
- tests/test_core/test_core_item.py
**Summary:**
This PR rewrites the logic that determines if a new item added from the new item menu in the project tree is added as a child or a sibling to the selected item. The rules are as follows:
* If the new item is a plain document, it is added as a child to folders or a document that already has child items.
* If the new item is a chapter, it is added as a child to folders, or partition level documents that already have child items.
* If the new item is a scene, it is added as a child to folders, or chapter or partition level documents that already have child items.
* If the new item is a note, it is added as a child to folders, or any note or document that already have child items.
* If the new item is a folder, it is only added as a child to other folders.
Some conditions are …
> Make adding new docs smarter

- novelwriter/gui/projtree.py
**Summary:**
This PR makes the following changes:
* The delete item menu entry for empty folders now correctly says "Delete Permanently" instead of "Move to Trash". Issue #1105.
* The menu entries for changing document layout now stays "Convert to" instead of "Change to". It is technically just a change of a setting, but to the user it makes more sense to say convert.
* The menu entries for status and importance now says "Set Status to ..." and "Set Importance to ..." instead of "Change [...] to" which is technically incorrect in the case where the user selects the same value as was previously set.
Closes #1105
> Update context menu entries in project tree

- novelwriter/gui/doceditor.py
**Summary:**
The editor has the document margin set to 0, but the cursor requires at least one cursor width of margin in order to be visible when it reaches the right hand edge of the document.
This PR reduces the user-defined margin by the width of the cursor, which is used for the viewport, and sets the document margin to the subtracted width.
Resolves #1112
> Fix clipping of cursor due to no document margin

- novelwriter/gui/projtree.py
- tests/test_gui/test_gui_projtree.py
**Summary:**
This PR adds a couple of entries to the context menu for the project tree to convert a folder to either a note or a document.
Resolves #1071
> Convert folder to document or note

- novelwriter/gui/projtree.py
- tests/test_gui/test_gui_projtree.py
**Summary:**
Add context menu and project tree menu entries to expand/collapse all items below the selected item. If none are selected, the action is performed on the whole tree.
Resolves #1122
> Add Expand/Collapse All functionality to project tree

- novelwriter/gui/doceditor.py
- tests/reference/guiEditor_Main_Final_000000000000f.nwd
- tests/reference/guiEditor_Main_Final_nwProject.nwx
- tests/test_gui/test_gui_guimain.py
**Summary:**
This PR adds a simple look-back check to see if the character before the one that triggered the insertion of a non-breaking space was also a space character. If so, that character is removed before the new space is inserted.
Resolves #1061
> Remove existing space when auto-inserting space

- novelwriter/core/__init__.py
- novelwriter/core/doctools.py
- novelwriter/core/item.py
- novelwriter/core/project.py
- novelwriter/dialogs/docmerge.py
- novelwriter/gui/custom.py
- novelwriter/gui/mainmenu.py
- novelwriter/gui/outline.py
- novelwriter/gui/projtree.py
- novelwriter/guimain.py
- tests/conftest.py
- tests/reference/coreDocTools_DocMerger_0000000000010.nwd
- tests/reference/coreDocTools_DocMerger_0000000000014.nwd
- tests/reference/coreProject_NewFileFolder_nwProject.nwx
- tests/reference/coreProject_NewRoot_nwProject.nwx
- tests/test_core/test_core_doctools.py
- tests/test_core/test_core_project.py
- tests/test_dialogs/test_dlg_docmerge.py
- tests/test_gui/test_gui_guimain.py
- tests/test_gui/test_gui_mainmenu.py
- tests/test_gui/test_gui_noveltree.py
- tests/test_gui/test_gui_projtree.py
- tests/test_gui/test_gui_statusbar.py
- tests/test_tools/test_tools_lipsum.py
- tests/tools.py
**Summary:**
This PR completely rewrites the document merge tool. The new implementation uses a simple merge settings dialog, where the choices are made, and the merging itself is handled in the Project Tree class using a `DocMerger` tool in the core sub package. All methods are now accessed via the Project Tree context menu.
This PR also splits up the Project Tree `deleteItem` method into a `moveItemToTrassh` and a `permanentlyDeleteItem` method, with a `requestDeleteItem` function to interact with the main menu. The reason for this being that the old method assumed that a request to delete an item already in the Trash folder meant that it was to be permanently deleted. This meant that calling the method programmatically (as is done by the merge tool) could cause an item to be …
> Rewrite Merge Tool

- novelwriter/gui/doceditor.py
- sample/nwProject.nwx
- tests/reference/guiEditor_Main_Final_000000000000f.nwd
- tests/reference/guiEditor_Main_Final_nwProject.nwx
- tests/test_gui/test_gui_guimain.py
**Summary:**
Add the unicode line separator (u2028) to the auto-replace function of the editor, and convert it to a paragraph separator (u2029).
Resolves #1150
> Add Shift+Enter to auto-replace

- novelwriter/dialogs/projdetails.py
- novelwriter/gui/doceditor.py
- novelwriter/gui/mainmenu.py
- novelwriter/gui/viewsbar.py
- novelwriter/guimain.py
**Summary:**
This PR changes a few minor details on the GUI, mostly related to tooltips and menu actions. It also makes the Project Details dropdown box always visible.
Closes #1106 as it is no longer relevant.
> Make some minor GUI tweaks

- novelwriter/core/options.py
- novelwriter/tools/build.py
**Summary:**
This PR adds a simple filter list of switches to the Build Tool so the user can filter out root folders. This is needed now that it's possible to have multiple root folders. This is only a simple implementation since the whole tool will be redesigned for 2.1.
Closes #1138
> Add a root folder filter to the build tool

- novelwriter/common.py
- novelwriter/config.py
- novelwriter/gui/theme.py
- tests/test_base/test_base_common.py
- tests/test_base/test_base_config.py
**Summary:**
The folder for custom GUI and syntax themes were attempted created before the data folder for novelWriter was created. This printed four error messages the first tome novelWriter was run on a new system. The problem resolved itself on the second run.
The error was handled, and the folders in question are read-only, so the error was trivial.
In the same PR, the functions to set dataPath and confPath in the main config object have been removed. They are not in use, neither by the app nor the test suite. A new common function to both check for and create folders at the same time, has been added. This is useful also elsewhere in the code.
Resolves #1180
> Fix missing data path issue when creating themes folders

- novelwriter/common.py
- novelwriter/core/index.py
- novelwriter/core/options.py
- novelwriter/core/project.py
- novelwriter/core/tokenizer.py
- novelwriter/tools/writingstats.py
- tests/test_base/test_base_common.py
**Summary:**
This PR:
* Removes the `allowNone` feature of `checkInt`, `checkFloat` and `checkBool`.
* Splits the `checkString` function into one that does and one that does not allow `None`.
* Removes the `checkIntRange` function as it can use the `minmax` function instead.
* Fixes a type bug in the `writeNewFile` method in the project class.
* Fixes a few weird dictionary lookups in the index class. They were technically safe, but could be made clearer and simpler.
Resolves #1185
> Clean up common module, and fix a few typing issues

- docs/source/usage_shortcuts.rst
- novelwriter/dialogs/preferences.py
- novelwriter/enum.py
- novelwriter/gui/doceditor.py
- novelwriter/gui/mainmenu.py
- tests/test_gui/test_gui_doceditor.py
- tests/test_gui/test_gui_mainmenu.py
**Summary:**
This PR:
* Removes the restriction on formatting lines that they must not be empty.
* Adds an Insert menu entry for synopsis comments, with a shortcut.
* Updates documentation and tests accordingly.
Resolves #1177
Resolves #1178
> Add format and insert features

- novelwriter/core/doctools.py
- novelwriter/dialogs/docsplit.py
- novelwriter/gui/outline.py
- novelwriter/gui/projtree.py
- tests/test_core/test_core_doctools.py
- tests/test_gui/test_gui_projtree.py
**Summary:**
This PR adds the move to trash option also for the Split Document dialog,
In addition, the PR fixes the following issues:
* Icons not being initially loaded in the Outline view
* Item importance and status not being preserved when documents are split.
Resolves #1179
> Allow moving split document to trash

- setup.py
**Summary:**
The file name of the AppImage build now contains the version number, the Python version, and info about the build image.
Resolves #1182
> Add version and build info to AppImage build

- novelwriter/gui/itemdetails.py
- novelwriter/guimain.py
**Summary:**
If no last document was recorded, or the project is new, open the first available document if any exist.
This PR also fixes the active/inactive icon in the item details panel.
Resolves #1219
> Auto-open first document

- novelwriter/__init__.py
- novelwriter/common.py
- novelwriter/config.py
- novelwriter/dialogs/preferences.py
- novelwriter/dialogs/projload.py
- novelwriter/gui/docviewer.py
- novelwriter/gui/outline.py
- novelwriter/gui/theme.py
- novelwriter/guimain.py
- tests/conftest.py
- tests/mock.py
- tests/reference/baseConfig_novelwriter.conf
- tests/reference/guiPreferences_novelwriter.conf
- tests/test_base/test_base_common.py
- tests/test_base/test_base_config.py
- tests/test_base/test_base_init.py
- tests/test_dialogs/test_dlg_preferences.py
- tests/test_gui/test_gui_guimain.py
- tests/test_gui/test_gui_theme.py
**Summary:**
PR #1228 added a recent cache class that did not have its path updated when the config init was run, which is were the data path is overloaded. This caused the tests to pollute the list of recently opened projects. It also implies that if the user sets the `--data` argument when launching, this would also not redirect the recent cache file.
This PR also makes further cleanup of the Config class, and renames a few settings. It also removes the "Backup" and "Path" sections of the file. It also fixes an issue when loading themes from invalid (or no longer valid) settings.
> Further config updates

- novelwriter/dialogs/projload.py
- novelwriter/gui/noveltree.py
- novelwriter/gui/outline.py
- novelwriter/gui/projtree.py
- novelwriter/guimain.py
**Summary:**
Block the toolbars when there are no projects open.
Resolves #1220
> Block toolbars when there is no project

- novelwriter/config.py
- novelwriter/core/item.py
- novelwriter/dialogs/preferences.py
- novelwriter/gui/doceditor.py
- novelwriter/gui/dochighlight.py
- tests/reference/baseConfig_novelwriter.conf
- tests/reference/guiPreferences_novelwriter.conf
- tests/test_base/test_base_config.py
- tests/test_core/test_core_item.py
- tests/test_gui/test_gui_guimain.py
- tests/test_gui/test_gui_mainmenu.py
**Summary:**
A small PR that changes a couple of things:
* The quote symbol settings in Config are now 4 variables instead of two lists. This means the string list feature can be removed from the custom config parser when the backwards compatibility is removed.
* The editor now caches all formatting settings in the class. This gives a minimal performance boost, but was mostly done for consistency. Other performance improvements were tested, but none were very significant.
* The attributes of the NWItem class are now all slots. There is no need for dynamic entries in this class. This should give a small performance boost. This class is both instantiated a lot, and accessed a lot. The other bonus is that making it non-dynamic will make it a bit more resilient against errors.
**Related …
> Update Config and NWItem class

- novelwriter/common.py
- novelwriter/constants.py
- novelwriter/core/index.py
- novelwriter/gui/doceditor.py
- novelwriter/gui/noveltree.py
- novelwriter/gui/outline.py
- novelwriter/gui/projtree.py
- novelwriter/guimain.py
- tests/reference/coreIndex_LoadSave_tagsIndex.json
- tests/test_base/test_base_common.py
- tests/test_core/test_core_index.py
- tests/test_gui/test_gui_doceditor.py
- tests/test_gui/test_gui_guimain.py
- tests/test_gui/test_gui_noveltree.py
- tests/test_gui/test_gui_outline.py
**Summary:**
This PR redesigns how the novel tree is updated. As long as the number of headings in a document don't change, the meta data for a document is refreshed each time the document is saved. Previously, this required a full rebuild of the tree, which is somewhat expensive. The tree is now rebuilt only when there are headings added or removed.
In order to better detect this, the index handling of headers has been changed. Each heading is now saved with a key that simply corresponds to its order in the document. Previously, the key represented the line number, which means it changed much more often. The line number is rarely needed, but is now recorded as a separate value in the heading index for those cases.
This change also simplified a number of different pieces of code tracking …
> Novel view meta

- novelwriter/gui/doceditor.py
- novelwriter/gui/docviewer.py
- novelwriter/gui/noveltree.py
- novelwriter/gui/outline.py
- novelwriter/gui/projtree.py
- novelwriter/guimain.py
- tests/reference/guiEditor_Main_Final_nwProject.nwx
- tests/test_gui/test_gui_doceditor.py
- tests/test_gui/test_gui_docviewer.py
- tests/test_gui/test_gui_guimain.py
**Summary:**
This PR makes the following changes:
* When the editor moves to a specific line, the editor now scrolls that line to within 10% of the top.
* When a document is requested opened, but it is already open, the document is no longer closed and re-opened. Instead, the move to line call is made in case the user requested a specific header.
* The set cursor position and line methods in the document viewer have been removed as they were not used. Navigation in the viewer is done through HTML anchors.
Closes #1239
Closes #1242
> Improve document navigation

- novelwriter/core/index.py
- novelwriter/core/tree.py
- novelwriter/gui/noveltree.py
- novelwriter/gui/outline.py
- novelwriter/guimain.py
- tests/test_gui/test_gui_noveltree.py
**Summary:**
This PR makes a few changes to the optional extra column in the novel view:
* The column will now only show the first of the references in the list returned from the index. The full data is still shown in the tooltip.
* The column will still shrink to content, but if the content grows larger than 25% of the width of the widget, the text will be elided using the QFontMetric class.
In addition, this PR improves how project items are iterated through in the project tree class. It now uses yield instead of index, and checks the type before yielding an item. This means a None will never be returned here.
Closes #1238
> Set a max column width for novel tree extra column

- novelwriter/enum.py
- novelwriter/gui/doceditor.py
- novelwriter/gui/statusbar.py
- novelwriter/guimain.py
- tests/test_gui/test_gui_statusbar.py
**Summary:**
This PR:
* Makes some changes to how project status saved/unsaved is handled.
* Changes the go to line behaviour of the editor to work similarly to the auto-scrolling feature, and uses the same setting.
Closes #1237
> Update closing project procedure, and editor scrolling

- novelwriter/gui/components.py
- novelwriter/gui/noveltree.py
- novelwriter/gui/outline.py
- novelwriter/gui/statusbar.py
**Summary:**
This PR adds a NovelSelector class that can be used to select the novel folder to be viewed in the relevant tool. It is added to the Outline View and the Novel View.
In the Novel View it replaces the label at the top of the tree, which becomes a dropdown box if there are more than one novel folder. If there is only one, it acts like a label.
Closes #1250
> Add a novel selector class

- i18n/nw_base.ts
- novelwriter/dialogs/projdetails.py
- novelwriter/gui/components.py
- novelwriter/gui/noveltree.py
- novelwriter/gui/outline.py
- tests/test_dialogs/test_dlg_projdetails.py
**Summary:**
This PR fixes the following minor issues:
* The Project Outline was still manually populating the combo box of novel root folders. Switch to use the NovelSelector component.
* The novel tree now shows the previously selected item in the details panel when the novel tree receives focus.
* The novel icon button has been added back into the novel tree, but now just pops open the combo box. It is only visible if there are multiple novel root folders.
* The main translation file has been updated.
> Fix minor GUI issues

- docs/source/int_customise.rst
- novelwriter/gui/theme.py
**Summary:**
If the user has made a custom theme, and not added the new icontheme setting, the theme class should fall back to using the typicons_light icon theme. Otherwise it doesn't load any icons.
Closes #1263
> Add a icon theme fallback value

- novelwriter/core/__init__.py
- novelwriter/dialogs/__init__.py
- novelwriter/gui/__init__.py
- novelwriter/tools/__init__.py
**Summary:**
The `__init__.py` files were removed in #1262, but empty ones are still needed for the build tool.
> Add empty init files to subdirs of main package

- .github/workflows/test_linux.yml
- novelwriter/dialogs/preferences.py
**Summary:**
Changing the Preferences settings on the Highlighting tab did not trigger a reinitialisation of the editor and highlighter. This PR fixes that.
Closes #1274
> Fix updating highlighting prefs not updating editor

- i18n/nw_base.ts
- novelwriter/core/project.py
- novelwriter/core/storage.py
- tests/test_core/test_core_storage.py
**Summary:**
The NWStorage class did not actually check that a project folder exists before trying to open a project. Unless it is a new project, the folder should already exists, and if it doesn't, an error returned. This PR fixes this issue.
Closes #1300
> Add a check that a non-new project actually exists

- novelwriter/gui/projtree.py
- novelwriter/guimain.py
**Summary:**
This PR fixes two issues:
* The convert to document/note menu entries in the project tree were still trying to convert files even if it was applied to a folder. They now properly call the convert folder function when used on folders.
* Trying to open a document from outline view should switch focus even if the document is already open.
Closes #1291
Closes #1305
> Fix convert folders and open from outline

- novelwriter/dialogs/projsettings.py
**Summary:**
This PR updates the code that handles status and importance label settings. The edit label form is now active whenever a label is selected, and inactive when none are selected. The code has also been updated a bit. This was quite old code.
Resolves #1290
> Update status/import label form code

- novelwriter/gui/projtree.py
- tests/test_gui/test_gui_projtree.py
**Summary:**
This PR fixes an issue where a project item with a parent that cannot be loaded would crash the app. The parent item would pass the first check during loading, because it does exist, but would not be added to the tree in the app due to having incomplete or wrong data. The subsequent adding of the child item would thus fail in the same function as there was no check that the parent item was there before the child item was added (resulting in a KeyError).
The issue was discovered with #1283, where a project file from an unreleased version of novelWriter triggered this issue. The issue can be triggered by taking the type of a root item and set its type value to an invalid one.
Closes #1283
> Fix handling of item with missing parent item

- docs/source/int_source.rst
**Summary:**
Add a note in the docs about the Qt SVG library sometimes needing to be installed manually.
Related to #1319
> Mention Qt SVG dependency for Arch Linux in the docs (#1319)

- novelwriter/__init__.py
- novelwriter/common.py
- novelwriter/config.py
- novelwriter/error.py
- novelwriter/gui/doceditor.py
- novelwriter/guimain.py
- tests/test_base/test_base_common.py
- tests/test_base/test_base_init.py
**Summary:**
Seems `QT_VERSION_STR` has been imported from a different location than what's listed in the PyQt5 documentation. It may have moved at some point, or the import from `PyQt5.Qt` may have been a bleed through that is no longer there.
This PR imports it from `PyQt5.QtCore` instead, as the PyQt5 docs state. The PR also replaces the 10 base integer version with the hex version provided by PyQt5. There is only one version check left in the main code anyway.
Resolves #1324
> Fix PyQt5 version check

- novelwriter/core/storage.py
- tests/test_core/test_core_tree.py
**Summary:**
This adds a check to the storage class that verifies that the storage path for project content still exists when saving a document. It solves #1317 for now, but the process needs to be handled better in general in a proper feature change not suitable for a patch.
Closes #1317
> Add project content path check

- novelwriter/gui/doceditor.py
**Summary:**
Don't insert line breaks when applying block formats to empty lines.
Closes #1349
Closes #1350
> Fix block formatting issues

- i18n/nw_base.ts
- novelwriter/core/options.py
- novelwriter/gui/noveltree.py
- tests/test_gui/test_gui_noveltree.py
**Summary:**
This PR changes the following in the novel tree:
* Allows the third column to show more than one item.
* Allows the user to change the maximum column size in percentages from 15% to 75%. Default value is still 25%.
Closes #1351
> Fix issues with novel tree last column

- novelwriter/gui/docviewer.py
- novelwriter/gui/projtree.py
- tests/test_gui/test_gui_docviewer.py
**Summary:**
This PR fixes three bugs:
* The Reference Panel link would no longer recognise the new, shorter links after the 2.0 project index change. The explicit check has been made more lenient and will now accept any link that is at least 13 characters long (the length of a document handle).
* Test coverage has been added for handling Reference Panel links.
* When new items are created in the project tree via shortcuts, the project tree receives focus. Since these actions can be accessed when the project tree does not have focus, a user would have to manually switch focus to be able to open new items if they were in the editor when activating them.
* The `setSelectedItem` method of the project tree class had a `setFocus()` call. It should not do this as global focus is handled by the …
> Fix GUI bugs and broken reference links

- novelwriter/guimain.py
**Summary:**
This is a small change that modifies the behaviour of the main splitter, between the project tree are and the document area, so that when the window resizes, the project tree area remains fixed.
> Change resize behaviour of main splitter

- docs/source/_static/custom.css
- docs/source/_templates/sidebar-title.html
- docs/source/conf.py
- docs/source/index.rst
- docs/source/int_introduction.rst
- docs/source/requirements.txt
**Summary:**
This PR switches the main docs theme to use Sphinx Book Theme instead. It is a child theme of the PyData theme that the website now uses, so the source is compatible with the website where the docs are also included.
> Switch docs theme to Sphinx Book Theme

- i18n/nw_base.ts
- novelwriter/__init__.py
- novelwriter/gui/projtree.py
**Summary:**
This PR:
* Fixes an issue with the application name not showing up properly on Gnome 43 (at least) and novelWriter is instead listed as "io.novelwriter.python3". Apparently it has been guessing the name to some extent, but setting the `QApplication.desktopFileName` value to "novelWriter" seems to clear it up.
* Resolve an issue where the context menu entry for renaming a project item says "Change Label" while the main menu entry says "Rename Item". The context menu now says "Rename", which is more consistent and logical.
Closes #1403
> Minor GUI Fixes

- novelwriter/gui/projtree.py
**Summary:**
This PR adds a small check when item selection in the project tree changes whether the selected item can have a document added to it. If it cannot, the corresponding options in the new items menu are hidden.
Closes #1404
> Apply new item rules in project tree

- .github/workflows/build.yml
**Summary:**
This PR converts the Linux Build action into a matrix build that also supports older glibc versions.
Closes #1391
> Build AppImage for older Linux distros

- novelwriter/gui/dochighlight.py
**Summary:**
Since underscores are considered word characters in regex, the spell checker has issues dealing with them when they are used for italics markup. This fix is a temporary solution until new spell checking code can be added, but it essentially just replaces all underscores with spaces before processing the word splitter regex used for spell checking.
The solution is simple, but carries a small overhead. Still, it is not an issue on normal sized documents.
Closes #1415
> Replace underscores with spaces when running spell checker

- novelwriter/core/tohtml.py
- novelwriter/core/tokenizer.py
- novelwriter/core/toodt.py
- novelwriter/gui/docviewer.py
- novelwriter/tools/build.py
- tests/test_core/test_core_tohtml.py
- tests/test_core/test_core_tokenizer.py
- tests/test_core/test_core_toodt.py
**Summary:**
This PR changes how escaped markdown characters are handled. Previously, they were handled in a post processing step that only actually worked for the document viewer.
The new implementation runs a utility function on each piece of text that goes into an HTML or ODT paragraph during the processing loop. This is now format-dependant and the post processing function itself has been removed.
Closes #1412
> Fix escaped markdown not being cleaned up for HTML and ODT

- novelwriter/gui/mainmenu.py
**Summary:**
This PR fixes the documentation URL in the Help menu. It was pointing to the correct domain, but the wrong path.
Closes #1445
> Fix docs URL

- novelwriter/assets/themes/default.conf
- novelwriter/assets/themes/default_dark.conf
- novelwriter/assets/themes/default_light.conf
- novelwriter/assets/themes/solarized_dark.conf
- novelwriter/assets/themes/solarized_light.conf
- novelwriter/extensions/pagedsidebar.py
- novelwriter/gui/theme.py
- tests/test_gui/test_gui_theme.py
**Summary:**
This PR:
* Adds a proper light theme, but leaves the default theme as whatever Qt chooses.
* Selects default icon theme based on the lightness of the window colour.
* Adds the help text colour to the theme config file and sets it for the existing themes.
Closes #1472
Closes #1473
> Theme updates

- novelwriter/config.py
**Summary:**
This PR changes the default font on macOS to Helvetica
Related to #1463
> Change default font on macOS

- novelwriter/core/coretools.py
- novelwriter/core/document.py
- novelwriter/core/item.py
- novelwriter/core/tree.py
- novelwriter/gui/projtree.py
- tests/reference/coreTools_DocDuplicator_nwProject.nwx
- tests/test_core/test_core_coretools.py
- tests/test_core/test_core_document.py
- tests/test_core/test_core_item.py
- tests/test_core/test_core_tree.py
- tests/test_gui/test_gui_projtree.py
**Summary:**
This PR adds functionality to duplicate either individual files, or whole hierarchies up to and including root folders.
In addition, this PR:
* Adds annotations to a bunch of core classes, and bits here and there.
* Improves the function that adds tree widget items to the project tree so that it also allows controlling where root folders appear. This is needed for #1259 as well, but here it is used to ensure that a duplicated root folder appears next to the folder it duplicates.
Closes #1469
> Add duplication of files and folders

- novelwriter/core/buildsettings.py
- novelwriter/core/coretools.py
- novelwriter/core/docbuild.py
- novelwriter/core/document.py
- novelwriter/core/index.py
- novelwriter/core/item.py
- novelwriter/core/options.py
- novelwriter/core/project.py
- novelwriter/core/storage.py
- novelwriter/core/tree.py
- novelwriter/gui/projtree.py
- tests/test_core/test_core_buildsettings.py
- tests/test_core/test_core_docbuild.py
- tests/test_core/test_core_index.py
- tests/test_core/test_core_item.py
- tests/test_core/test_core_project.py
- tests/test_core/test_core_projectxml.py
- tests/test_core/test_core_storage.py
- tests/test_core/test_core_tree.py
**Summary:**
This is a refactoring PR, and changes the following:
* The handle for a project item (NWItem class) can no longer be set to None, and is always a string. There is no longer a need to check if the handle is not None in the code, which simplifies a lot of things.
* Only the tree class (NWTree) is allowed to create new items, and a new create function has been added to it to handle the creation of new items in the project class.
* The tree class is thus alone responsible for not letting any item into the project tree that does not have a valid handle. The append function is the only place where items are added, and it explicitly checks the handle.
* Due to the above, the project class is no longer allowed to handle the recovery of orphaned files. This is now handled by the tree …
> Improve project item and tree classes

- novelwriter/common.py
- novelwriter/core/project.py
- tests/test_core/test_core_project.py
**Summary:**
This PR makes two small changes to the backup feature:
* The file name now contains the project name again.
* The archive size is printed to the dialog together with the file name.
Closes #1453
Closes #1476
> Improve backup feature

- docs/source/usage_shortcuts.rst
- novelwriter/core/index.py
- novelwriter/gui/projtree.py
- tests/test_gui/test_gui_projtree.py
**Summary:**
This PR adds the following keyboard shortcuts for the project tree:
* `Shift+Up` and `Shift+Down` navigates up and down the project tree between sibling elements under the same node. Navigation stops at the boundaries. This is different from normal `Up` and `Down` navigation, which moves between rows and ignores the tree structure. The new functionality is mostly useful on the higher levels as you can skip all expanded child items.
* `Shift+ Left` navigates to the immediate parent of the selected item, stopping when reaching a root item. This is only marginally different than the `Left` key which will alternate between closing an item and moving to the parent, depending on the item's state.
* `Shift+Right` navigates to the first child of the item, expanding it in the process. …
> Add project tree navigation shortcuts

- docs/source/usage_shortcuts.rst
- novelwriter/gui/projtree.py
**Summary:**
* Change the modifier for the special navigation of the project tree to use Alt instead of Shift
* Restructure the keyboard shortcuts documentation
See #1348
> Change tree nav shortcut modifier and update docs

- docs/source/int_source.rst
- novelwriter/__init__.py
- novelwriter/guimain.py
- novelwriter/tools/lipsum.py
- novelwriter/tools/manusbuild.py
- novelwriter/tools/manuscript.py
- novelwriter/tools/manussettings.py
- novelwriter/tools/writingstats.py
- pkgutils.py
- setup/macos/build.sh
**Summary:**
This PR fixes two issues:
* An issue with dialog windows being hidden behind the main window in certain circumstances, like opening a file system dialog. These dialogs have now been marked as a "Tool", i.e. a Panel as far as MacOS is concerned. This is only applied for Mac.
* The version number for the beta release is not allowed in the MacOS plist file, so it now just uses the numerical part.
A new DMG image for release 2.1-beta1 has been uploaded with these changes. The file is versioned as 2.1b1-post1.
Closes #1494 
> Fix MacOS release for 2.1b1

- novelwriter/config.py
- novelwriter/guimain.py
- tests/reference/baseConfig_novelwriter.conf
- tests/reference/guiPreferences_novelwriter.conf
- tests/test_dialogs/test_dlg_about.py
- tests/test_gui/test_gui_guimain.py
**Summary:**
This PR removes the caching of the full screen state to the config file. This never worked properly anyway since the full screen flag internally in Qt doesn't necessarily match the window manager.
This PR also adds annotations to the main GUI class.
> Drop saving fullscreen flag

- novelwriter/core/project.py
- novelwriter/core/spellcheck.py
- novelwriter/core/tree.py
- novelwriter/dialogs/preferences.py
- novelwriter/dialogs/projsettings.py
- novelwriter/gui/doceditor.py
- novelwriter/gui/dochighlight.py
- novelwriter/gui/mainmenu.py
- novelwriter/gui/projtree.py
- novelwriter/gui/statusbar.py
- novelwriter/guimain.py
- novelwriter/shared.py
- tests/test_base/test_base_shared.py
- tests/test_core/test_core_spellcheck.py
- tests/test_core/test_core_tree.py
- tests/test_dialogs/test_dlg_preferences.py
- tests/test_dialogs/test_dlg_projsettings.py
- tests/test_gui/test_gui_guimain.py
- tests/test_gui/test_gui_projtree.py
**Summary:**
This PR:
* Moves the spell check instance to the new shared data class, so that the object can be destroyed and re-created with the project.
* Cleans up loading of the user's own custom dictionary, which is per-project and must be handled correctly to prevent bleed-through between projects.
* Adds a way to change spell check language from the Tools menu.
Also:
* The project class is no longer a subclass of QObject.
* Various attributes of core classes have been converted to properties.
* The syntax highlighter class has received a cleanup.
Closes #1260
> Refactor handling of spell checking

- novelwriter/extensions/wheeleventfilter.py
- novelwriter/gui/doceditor.py
- novelwriter/gui/docviewer.py
- novelwriter/shared.py
- tests/test_ext/test_ext_wheeleventfilter.py
**Summary:**
This PR adds an event filter that will capture any mouse wheel scroll event on a widget and forward the event to the wheelEvent handler of the root widget. This solves the issue that scroll events in widget margins are ignored.
Closes #1425
Duplicate #1474
> Forward all scroll events in text area widgets to parent

- .github/workflows/test_linux.yml
- .github/workflows/test_mac.yml
- .github/workflows/test_win.yml
- README.md
- docs/source/int_started.rst
- novelwriter/__init__.py
- novelwriter/core/document.py
- setup.cfg
- setup/debian/control
- setup/description_pypi.md
- setup/macos/build.sh
**Summary:**
This PR bumps minimum Python version to 3.7. MacOS and Windows tests now run on 3.11, and 3.12-dev has been added to Linux tests.
> Remove Python 3.7 support

- i18n/nw_base.ts
- novelwriter/core/buildsettings.py
- novelwriter/core/options.py
- novelwriter/core/project.py
- novelwriter/core/tokenizer.py
- novelwriter/tools/manuscript.py
- tests/test_core/test_core_buildsettings.py
**Summary:**
This PR adds a display widget to the Manuscript tool window that shows more details about the currently selected build.
> Display build details in Manuscript tool

- novelwriter/gui/doceditor.py
- novelwriter/gui/dochighlight.py
- novelwriter/gui/sidebar.py
- novelwriter/guimain.py
- tests/test_gui/test_gui_guimain.py
**Summary:**
This PR:
* Fixes a few minor issues in the code.
* Changes the spell checker to only spell check words with only letters in them (Python `str.isalpha()`).
* Removes the text labels in the side bar and converts it to a layout box with tool buttons. The tool buttons have the same style sheets as other tool buttons in the app.
* Takes control over the popup location of the menu on the Settings button. It will now always pop up to the right of the button, growing upwards from the bottom of the button.
> Sidebar cleanup and minor fixes

- novelwriter/config.py
- novelwriter/constants.py
- novelwriter/core/tokenizer.py
- novelwriter/dialogs/preferences.py
- novelwriter/gui/doceditor.py
- novelwriter/guimain.py
- tests/reference/baseConfig_novelwriter.conf
- tests/reference/guiPreferences_novelwriter.conf
- tests/test_core/test_core_tokenizer.py
- tests/test_dialogs/test_dlg_preferences.py
- tests/test_gui/test_gui_doceditor.py
- tests/test_gui/test_gui_mainmenu.py
**Summary:**
This PR makes the text editor in novelWriter actually plain text. So far, it's been a rich text editor with rich text editing disabled. At some point, there was a reason for this. There are still some drawbacks, but the benefits outweigh them.
**Pros**
* It loads a lot faster since it doesn't have to take into account special text content like lists, images and tables. Which we don't support anyway.
* The syntax highlighter works a lot more smoothly since it is designed and optimised for the plain text view.
* Re-running the highlighter is no longer a performance bottleneck, so we can now rerun it for spell checking purposes even for large documents.
* Scrolling past the end of the document is supported out of the box.
* Centring the cursor when skipping to a specific line is …
> Make the editor actually Plain Text

- docs/source/usage_breakdown.rst
**Summary:**
Fix two simple typos in the docs usage_breakdown.
> Fix two typos in usage docs

- novelwriter/core/index.py
- novelwriter/extensions/novelselector.py
- novelwriter/gui/outline.py
- tests/reference/coreIndex_LoadSave_tagsIndex.json
- tests/test_core/test_core_index.py
**Summary:**
This PR changes the logic of the index class to capture the name of the tag with case preserved and save it as a "name" value in the tags index, and then converts it to lower case for usage in the references index itself. When a request is made to list all references in a document, the name is looked up in the tags index, and the original display name restored.
The extra lookup could be a small delay in very large and complex projects, but it's the only way to achieve this.
The changes to support this feature is kept entirely inside the index class, but it does require an index rebuild since the old index will be invalidated by the changes.
This PR also cleans up annotations in the Outline module.
Closes #1313
> Case insensitive tags

- novelwriter/tools/manussettings.py
**Summary:**
This PR:
* Sets the minimum column width for the icon columns on the Build Settings tool. On Windows, the default value is far too wide.
* Assigns the additional space when the Build Settings dialog is resized to the middle section on the Selection page.
* Set the initial splitter widths on the Selection page to 300/300.
Closes #1551
> Fix Build Settings icon column size issue

- novelwriter/config.py
- novelwriter/core/buildsettings.py
- novelwriter/dialogs/preferences.py
- tests/test_base/test_base_config.py
**Summary:**
This PR solves two issues:
* All strings defined in the build settings core class were sent to the GUI untranslated even when translations exist.
* When no GUI language is set, novelWriter defaults to the system locale. However, if that is not available in novelWriter, the Preferences dialog would just leave the dropbox on the first option, which is currently "Deutch". The config class now only defaults to system locale if there is a translation file for it available. Otherwise it defaults to "British English". The Preferences will also default to "British English" if the language setting in config is invalid or has become unavailable.
Closes #1563
Closes #1564
> Fix i18n issues

- novelwriter/core/tohtml.py
- novelwriter/core/tokenizer.py
- tests/test_core/test_core_tohtml.py
- tests/test_core/test_core_tokenizer.py
**Summary:**
The anchor tags were still generated based on line numbers instead of heading number, so following a link to a heading didn't work in the viewer.
Closes #1566
> Fix viewer navigation

- novelwriter/gui/projtree.py
**Summary:**
Add back in some of the checks for illegal moves on the project tree widget. The flags set on the invisible root item are ignored in at least Qt 5.15.8, although they work in Qt 5.15.2 which is used in most release formats. This change keeps both approaches. This should have no affect on releases with !t 5.15.2 as the checks won't even be reached.
Closes #1569
> Fix illegal drag and drop checks

- novelwriter/gui/projtree.py
**Summary:**
This PR adds an autoscroll feature in the project tree and disables the built in version, which is very buggy in certain Qt releases.
Closes #1561
> Add autoscroll feature

- novelwriter/gui/doceditor.py
- novelwriter/gui/docviewer.py
- novelwriter/gui/noveltree.py
- novelwriter/gui/projtree.py
- novelwriter/gui/sidebar.py
- novelwriter/tools/manussettings.py
**Summary:**
This PR adds a parent item to all `QMenu` constructors. This can help with the positioning issue according to [QTBUG-68636](https://bugreports.qt.io/browse/QTBUG-68636).
The remaining issue is a know issue with Qt5 on Wayland, and is not likely to be fixed. Moving to Qt6 (#1142) is the more likely solution, which will have to wait.
Closes #1536
> Set menu parents

- novelwriter/gui/doceditor.py
- novelwriter/guimain.py
**Summary:**
This PR fixes two issues with refreshing the editor when settings change. One forces a full rehighlight of the editor (unless the document is above the big doc limit) when the syntax theme changes. The mark as dirty feature doesn't seem to work properly for this. The second fix is to re-run the spell checker when the word list has changed.
Closes #1559
Closes #1535
> Fix editor refresh issues

- novelwriter/core/index.py
- novelwriter/gui/doceditor.py
- tests/test_core/test_core_index.py
- tests/test_gui/test_gui_doceditor.py
**Summary:**
This PR adds a custom MetaCompleter class, a context menu that is triggered on lines starting with the `@` character. It has the following features:
* On typing `@`, a list of keyword options appear. The list is shortened when more characters are typed. Typing `@c` will list `@char` and `@custom`. Hitting enter on an option will insert it and a `:`.
* Typing anything after a keyword, like a space, will open a list of up to 15 tags in that category. Any further typing will look for the typed characters in the list and filter it down. The lookup needs to be consecutive characters, but it's not case sensitive. So "an" will match "Jane" and "Jannet", but not "John".
* The auto-completer will treat multiple references separated by a comma. It uses the same evaluation function as …
> Add an auto-completer for editor references

- novelwriter/enum.py
- novelwriter/gui/doceditor.py
- novelwriter/gui/projtree.py
- tests/test_gui/test_gui_doceditor.py
- tests/test_gui/test_gui_guimain.py
**Summary:**
The PR adds a context menu entry to create a new project note from an undefined tag in the editor.
This PR also makes a few fixes to the auto-completer from #1581.
Closes #1580
Related #823
> Add context menu option to create note from tag

- novelwriter/core/buildsettings.py
- novelwriter/tools/manuscript.py
- tests/test_core/test_core_buildsettings.py
**Summary:**
This PR makes build settings definitions drag-and-drop-able in the Manuscript Build window. This required a bit of rewriting in the underlying data class.
Now, all builds are loaded as BuildSettings objects, rather than as Python dicts and unpacked in a BuildSettings object when requested by the user. Preserving them as dicts meant changes in added/deprecated values were not propagated unless they were actively edited, so this approach means they will be cleaned up by the unpack validation. The change was needed in order to save the order field for the numerical order in which each build settings definition appears on the GUI.
Closes #1542
> Make it possible to re-order build settings

- CHANGELOG.md
- novelwriter/__init__.py
- novelwriter/assets/text/release_notes.htm
- sample/nwProject.nwx
**Summary:**
Scheduled for 12 November 2023.
> Bump version to 2.2 Beta 1, and update changelog

- novelwriter/constants.py
- novelwriter/gui/doceditor.py
- tests/test_gui/test_gui_doceditor.py
**Summary:**
This PR:
* Rewrites the Auto Select feature to no longer use Qt's "Text Under Cursor" selector. Instead, it will now iterate backwards and forwards from the cursor position until it finds the first character in either direction that isn't considered a Unicode alphanumeric character as per Python's string implementation. This generates more meaningful selections than the Qt implementation which would select the punctuation if you activated it with the cursor between a word and its immediate punctuation.
* Changes the logic when you toggle a bold, italic or strike through Markdown format. When the cursor is at the end of the word, it will be left after the word + markup when the toggle is complete. If the cursor position was at the beginning or inside the word, the cursor …
> Improve how formatting is applied in the editor

- novelwriter/gui/doceditor.py
- novelwriter/gui/sidebar.py
**Summary:**
This PR:
* Removes the 2 px margin on the sidebar.
* Changes when the editor auto-completer is triggered to only be activated on single keypresses (add or delete) and nothing else. It was triggering on other document change events that were not user-initiated, like during loading of a document when the cursor had last been positioned at a tag/reference line.
* Changes the auto-replace feature to also run on keywords again. It has accidentally been disabled on such lines.
> UI usability fixes

- novelwriter/config.py
- novelwriter/dialogs/preferences.py
- novelwriter/gui/doceditor.py
- tests/reference/baseConfig_novelwriter.conf
- tests/reference/guiPreferences_novelwriter.conf
**Summary:**
This PR adds the "Scroll past end" setting back into Preferences and uses it for the centerOnScoll flag to the QPlainTextEdit.
Closes #1602 
> Bring back the "Scroll past end" setting

- novelwriter/gui/doceditor.py
- novelwriter/guimain.py
- tests/test_gui/test_gui_doceditor.py
**Summary:**
This PR:
* Adds a function to check if the cursor is visible in the editor (scrolled into view).
* Adds a new ensureCursorVisible function that only scrolls the cursor into view, but doesn't centre it like the built-in function does if the centre cursor feature is enabled (which again is needed for the scroll past end feature).
* Use these two functions to restore cursor visibility when switching to and from Focus Mode.
* The same method is applied when the document viewer is opened or closed, since it too can affect the editor width.
Closes #1302
Closes #1478
> Improve cursor visibility features

- novelwriter/common.py
- novelwriter/config.py
- novelwriter/constants.py
- novelwriter/dialogs/updates.py
- novelwriter/gui/docviewer.py
- novelwriter/gui/mainmenu.py
- novelwriter/guimain.py
- novelwriter/tools/dictionaries.py
- novelwriter/tools/manusbuild.py
- tests/conftest.py
- tests/test_gui/test_gui_mainmenu.py
- tests/test_tools/test_tools_dictionaries.py
**Summary:**
This PR adds an "Add Dictionaries" dialog that is available on Windows, or when novelWriter is running in DEBUG mode. The tool will process LibreOffice Extension files (`*.oxt") and Free Office Dictionary files (`*.sox`) and extract the `*.aff` and `*.dic` Hunspell files contained in them, if any exist. These will be copied to the correct location so the spell checker library can pick them up.
This is an alternative implementation to PR #1610 
Closes #982
> Add a tool to download spell check dictionaries, alternative 2

- novelwriter/gui/projtree.py
- tests/test_gui/test_gui_projtree.py
**Summary:**
This PR enables multi-selection for project tree items.
The following features have been added:
* The user can Ctrl-select multiple items, or Shift-select ranges.
* Root items included in a multi-select action are automatically deselected.
* Drag and drop actions on multi-selected items are only allowed if all items selected have the same parent, and are not a root item. Single select works as before.
* In the event a drag is cancelled, the user is notified why it was cancelled.
* The above is to avoid destroying nested folder/document structure as the Qt implementation of drag and drop will insert the dropped items one by one at the same level, so the nested structure is effectively flattened. This may be what the user wanted, but in many cases it may not be. Since it ruins …
> Add multi selection to project tree

- novelwriter/common.py
- novelwriter/core/project.py
- novelwriter/gui/mainmenu.py
- novelwriter/tools/dictionaries.py
- novelwriter/tools/manusbuild.py
- tests/test_base/test_base_common.py
- tests/test_tools/test_tools_manusbuild.py
**Summary:**
This PR adds a button to the Manuscript Build dialog that will open the output folder.
Closes #1554
> Add a button to open manuscript build folder

- i18n/nw_base.ts
- i18n/nw_en_US.ts
- i18n/nw_ja_JP.ts
- i18n/nw_nb_NO.ts
- novelwriter/dialogs/projload.py
- novelwriter/gui/doceditor.py
- novelwriter/gui/docviewerpanel.py
- novelwriter/gui/mainmenu.py
- novelwriter/guimain.py
- tests/test_gui/test_gui_docviewerpanel.py
- tests/test_gui/test_gui_guimain.py
- tests/test_gui/test_gui_mainmenu.py
**Summary:**
This PR:
* Fixes wrong keyboard shortcut for Insert Short Description Comment. It should be `Ctrl+K, H`.
* Sets the correct icon for the Browse button on the open project dialog, and adds annotations to the code.
* Removes the popup warning for Alpha releases, which is no longer needed since they are no longer on the `main` branch.
* Drops the space between `%` and the `Synopsis:` or `Short:` comment format from the Insert menu.
* Changes the label on the viewer panel to "References" from "Backreferences".
* Adds some easy to reach test coverage.
* Fixes column width issue in viewer panel.
* Fixes icons not being updated on theme switch in the viewer panel.
Closes #1627
> Fix various bugs and minor issues

- novelwriter/gui/mainmenu.py
- novelwriter/gui/statusbar.py
**Summary:**
Since the menu is not using tooltips any more, hovering a menu item clears the status bar because it displays an empty message. This PR adds an event filter that block those events, leaving the status bar as is.
> Add an event filter to remove status tip updates

- novelwriter/constants.py
- novelwriter/gui/doceditor.py
- novelwriter/gui/noveltree.py
- novelwriter/guimain.py
- tests/test_gui/test_gui_noveltree.py
**Summary:**
This PR:
* Adds a scroll feature to the Novel View when an item is activated, which is used when a document auto-opens in the editor, like during looped searches.
* Fixes the editor auto select feature to include apostrophe characters (right single quote and straight apostrophe) when selecting a word as long as there is a alphanumeric character on either side.
* Some cleanup in Novel View module.
Closes #1555
Closes #1624
> Fix some minor issues

- novelwriter/core/coretools.py
- novelwriter/core/project.py
- novelwriter/core/projectxml.py
- novelwriter/core/storage.py
- novelwriter/guimain.py
- tests/conftest.py
- tests/test_core/test_core_options.py
- tests/test_core/test_core_project.py
- tests/test_core/test_core_projectxml.py
- tests/test_core/test_core_storage.py
- tests/tools.py
**Summary:**
This PR applies a lot of the changes in the Storage class written for the single project file implementation. It does not include the single file format code itself. I haven't fully decided what to do with that part, but there is a lot of code in that branch that is worth using even without the single file part.
Changes:
* The storage class separates functions for initialising the class when opening a project and when creating a new project, avoiding the interdependent functionality and need for if-checks to decide course of action.
* The lock file is now handled entirely within the Storage class, which hides it behind its interface. This is in any case needed for the single file implementation as the lock file will be handled differently in those cases.
* The opened state of …
> Storage updates

- i18n/nw_base.ts
- novelwriter/gui/docviewerpanel.py
- tests/test_gui/test_gui_docviewerpanel.py
**Summary:**
This PR:
* Adds an importance column to the viewer panel.
* Double click anywhere on an item load other than edit and view buttons opens it in the viewer,
* Adds tooltip text to all list items so they can be viewed even if the column is resized to only show icon.
Closes #1620
> Add viewer panel importance info

- novelwriter/dialogs/about.py
- novelwriter/dialogs/preferences.py
- novelwriter/extensions/configlayout.py
- novelwriter/extensions/pagedsidebar.py
- novelwriter/gui/doceditor.py
- novelwriter/gui/dochighlight.py
- novelwriter/gui/docviewer.py
- novelwriter/gui/statusbar.py
- novelwriter/gui/theme.py
- novelwriter/tools/manussettings.py
- novelwriter/tools/welcome.py
- tests/test_gui/test_gui_guimain.py
- tests/test_gui/test_gui_theme.py
**Summary:**
This PR changes all colours defined in the Theme class to be QColor objects. They are nearly always used as QColor anyway, and this saves a lot of calls the constructor. The few cases where the colour components are used separately can extract them from the object instead.
> Convert theme colours to Qt objects

- novelwriter/gui/projtree.py
**Summary:**
This PR:
* Removes the focus switch call made after creating a new project item.
Closes #1648
> Fix focus switch bug in project tree

- novelwriter/common.py
- novelwriter/guimain.py
- novelwriter/shared.py
**Summary:**
Currently it is possible to open multiple copies of the Manuscript and Writing Statistics tools. This is a regression. This PR adds a check to prevent this.
> Handle non-modal dialogs better

- novelwriter/constants.py
- novelwriter/core/buildsettings.py
- novelwriter/core/docbuild.py
- novelwriter/core/tokenizer.py
- novelwriter/core/toodt.py
- novelwriter/tools/manussettings.py
- tests/reference/coreToOdt_SaveFlat_document.fodt
- tests/reference/coreToOdt_SaveFull_styles.xml
- tests/test_core/test_core_toodt.py
- tests/test_tools/test_tools_manussettings.py
**Summary:**
This PR adds a field in the Manuscript Build Settings tool to customise the page header for ODT documents. It defaults to the current standard format.
Closes #1505
> Add customisation option for ODT build document header

- novelwriter/dialogs/projectsettings.py
- novelwriter/gui/projtree.py
- tests/test_gui/test_gui_projtree.py
**Summary:**
This PR:
* Connects the already existing create document/folder actions in the "Add Item" menu of the Project Tree to a new submenu "Create New ..." in the context menu. No other code is needed, since the actions are already defined.
* Changes the label of the context menu "Transform" submenu to the same format as the other submenus.
* Fixes an issue with switching tab in Project Settings when opening it from the Project Tree context menu.
Closes #1519
> Add a 'Create New' menu for documents in project tree context menu

- novelwriter/core/coretools.py
- tests/test_core/test_core_coretools.py
**Summary:**
This PR completes the feature added to the new Welcome dialog that allows selecting a different project as the source for creating a new project. The missing piece was the implementation in the `ProjectBuilder` class, and this PR adds that.
It takes the path to an existing `nwProject.nwx` file and copies it, and everything under the `content` folder into the destination folder, opens this project, and sets the values defined in the New Project form on the Welcome dialog. Some other counter meta data is set to 0, like `saveCount`, `autoCount`, and `editTime`, and some other settings are reset to defaults. 
Resolves #841
> Allow creating project from other project (copy)

- novelwriter/core/coretools.py
- novelwriter/dialogs/preferences.py
- novelwriter/dialogs/projectsettings.py
- novelwriter/extensions/circularprogress.py
- novelwriter/extensions/modified.py
- novelwriter/extensions/pagedsidebar.py
- novelwriter/extensions/simpleprogress.py
- novelwriter/extensions/statusled.py
- novelwriter/guimain.py
- novelwriter/tools/manussettings.py
- novelwriter/tools/welcome.py
- tests/test_ext/test_ext_modified.py
- tests/test_tools/test_tools_welcome.py
- tests/tools.py
**Summary:**
This PR fixes a bunch of minor details on the Welcome dialog:
* The opacity of the highlight colour for a selected item has been reduced.
* When a project is removed from the list, the first item is selected automatically.
* When a project is requested opened, the dialog hides before the open project signal is emitted, so that it looks like the welcome dialog closes before the project is opened. In reality, it closes after the signal. Previously, when it stayed visible, any dialogs that popped up during the closing of the previous project and opening of the next would open on top of the welcome dialog, which was a bit confusing.
* Adds a modified version of QComboBox, QSpinBox, and QDoubleSpinBox where the mouse scroll wheel is only captured by the widget when the widget has …
> Improvements functionality of various dialogs

- novelwriter/core/coretools.py
- novelwriter/shared.py
- tests/test_core/test_core_coretools.py
- tests/test_dialogs/test_dlg_about.py
- tests/test_dialogs/test_dlg_preferences.py
- tests/test_dialogs/test_dlg_projectsettings.py
- tests/test_dialogs/test_dlg_wordlist.py
- tests/test_gui/test_gui_guimain.py
- tests/test_tools/test_tools_dictionaries.py
- tests/test_tools/test_tools_lipsum.py
- tests/test_tools/test_tools_manuscript.py
- tests/test_tools/test_tools_noveldetails.py
- tests/test_tools/test_tools_writingstats.py
- tests/tools.py
**Summary:**
This PR adds the option to create a new project from a zip file containing a novelWriter project. It also does some minor cleanup in how tests access top level windows, since the shared data class can do this now. This also adds test coverage of that feature in the shared data class.
Related #841 
> Add creating new project from zipped existing project

- docs/source/usage_shortcuts.rst
- novelwriter/core/tokenizer.py
- novelwriter/enum.py
- novelwriter/gui/doceditor.py
- novelwriter/gui/mainmenu.py
- tests/test_core/test_core_tokenizer.py
- tests/test_gui/test_gui_doceditor.py
**Summary:**
This PR adds a new block format, that is a variation of a comment which uses `%~` as a prefix instead of a plain `%`. It only has a minor difference in that it can be used to ignore text paragraphs without having to pollute comments if comments are actively used in the text and draft manuscripts for labelling plot progression and so on. The `%~` will completely ignore the lines when building a manuscript, also when comments are included.
Using it is completely optional, and for those who need this distinction. It has been given the keyboard shortcut `Ctrl+Shift+D` which is related to the strikeout shortcut `Ctrl+D`.
In addition, this PR adds support for applying/toggling formats to more than one paragraph.
Closes #1075
Closes #1042
Closes #1687 …
> Add an ignore text format and allow multi-paragraph formatting

- novelwriter/gui/projtree.py
- tests/test_gui/test_gui_projtree.py
**Summary:**
This is a simple PR that adds a context menu option "Rename to Heading" under the regular "Rename" option, if the selected item is a document, and there is a heading recorded by the index. When triggered, this option pre-populates the text field of the Edit Label pop-up with the heading text rather than the current item label. It uses entirely pre-existing functionality, so the PR simply adds the option and updates the unit test.
Closes #1443
> Add project tree option to rename item to first heading

- novelwriter/common.py
- novelwriter/constants.py
- novelwriter/dialogs/wordlist.py
- novelwriter/guimain.py
- novelwriter/shared.py
- novelwriter/tools/dictionaries.py
- novelwriter/tools/writingstats.py
- tests/test_base/test_base_common.py
**Summary:**
This PR adds a helper function for building file extension filters for file dialogs. Aside from not having to generated this special format in multiple places in the code, it also combines the translation strings for the ones used multiple places into a single lookup dictionary, preventing duplicate translation entries.
> Add formatter helper for file extensions filters

- .github/workflows/syntax.yml
- novelwriter/core/buildsettings.py
- novelwriter/core/coretools.py
- novelwriter/core/docbuild.py
- novelwriter/core/index.py
- novelwriter/core/project.py
- novelwriter/core/sessions.py
- novelwriter/core/spellcheck.py
- novelwriter/core/status.py
- novelwriter/core/toodt.py
- novelwriter/core/tree.py
**Summary:**
Don't allow PEP585 deprecated typing.
> Fix deprecated typing

- setup/win_setup_embed.iss
**Summary:**
This PR:
* Modifies the Windows installer to delete the old novelwriter source before installing the new.
> Post release changes for 2.3b1

- novelwriter/core/tokenizer.py
- tests/test_core/test_core_tokenizer.py
**Summary:**
This PR fixes two issues:
* Scene separators being inserted directly after level one headers.
* Chapter and scene counters not being reset after a new novel title is introduced, including for multiple novel folders.
Closes #1704
> Fix scene separators and chapter and scene counters

- novelwriter/core/tokenizer.py
- tests/test_core/test_core_tokenizer.py
- tests/test_tools/test_tools_manuscript.py
**Summary:**
This PR changes the way scene separators are handled after encountering a text paragraph. Previously, any text would remove the blocker for inserting a scene separator. However, with the changes in #1711, only level 1 and 2 headers should block scene separator insertion. Text paragraphs should not affect it at all. Text inserted after a level 1 or 2 heading, followed by a leve 3 (scene) should flow uninterrupted.
Related #1704
> Remove scene separator insertion after text

- novelwriter/core/project.py
- tests/test_core/test_core_index.py
**Summary:**
This PR adds a call to clear the index when a project is closed so a indexCleared signal is emitted. This clears the reference panel. The panel is anyway rebuilt when a new index is loaded, but *only* if there are any tags defined, which leaves data behind if the next project opened doesn't have any.
Closes #1718
> Emit clear index signal when project is closed

- novelwriter/core/docbuild.py
- novelwriter/core/tokenizer.py
- novelwriter/text/counting.py
- novelwriter/tools/manuscript.py
- tests/test_core/test_core_tohtml.py
- tests/test_core/test_core_tokenizer.py
- tests/test_core/test_core_toodt.py
**Summary:**
With the logic changed in the Tokenizer class, and the headers now always needing to be processed, the header formatting can be merged into the tokenizer function itself.
> Refactor Tokenizer class

- novelwriter/core/tree.py
- novelwriter/gui/doceditor.py
- novelwriter/gui/docviewer.py
- tests/test_core/test_core_tree.py
- tests/test_gui/test_gui_doceditor.py
**Summary:**
This PR makes a few improvements to how the editor processes changes of the document content. The percentage counter in the footer is now showing cursor position percentage, not line percentage, and the logic of how these stats are processed internally has been refactored. Test coverage has also been improved on this and the search functionality.
> Improve editor stats handling and test coverage

- i18n/nw_base.ts
- novelwriter/gui/projtree.py
- tests/test_gui/test_gui_projtree.py
**Summary:**
This fixes an issue with the "Move to Trash" option on multiple selected items in the project tree. With this fix, if all items selected are in trash, the option is "Permanently Delete", and if none of them are in trash the option is "Move to Trash". If it's a mix, neither option is available.
> Fix Trash and Delete entries for multi-select

- setup.cfg
**Summary:**
This entry point has never been in use and is anyway incorrectly configured.
Closes #1732 
> Remove the cli entry

- novelwriter/assets/syntax/cyberpunk_night.conf
- novelwriter/assets/syntax/tango.conf
- novelwriter/assets/themes/cyberpunk_night.conf
- novelwriter/gui/theme.py
- tests/test_gui/test_gui_theme.py
**Summary:**
Adding the Cyberpunk Night GUI and Syntax themes by @alemvigh, and the Tango terminal theme from Linux.
Closes #1730
> Add Cyberbunk Night themes

- novelwriter/core/storage.py
- novelwriter/guimain.py
- tests/test_core/test_core_storage.py
**Summary:**
This PR:
* Changes the error on missing (deleted) projects reported by the storage class to NOT_FOUND instead of UNKNOWN, which produces a more accurate error message for the user.
* Adds a check after the Welcome dialog has returned and an open project request has been processed. The check will pop open the Welcome dialog again if the previous process did not result in an open project. This will not trigger if there already was a project open before the Welcome dialog was opened. Only when the process results in a blank UI.
Closes #1737
> Open Project error handling

- novelwriter/config.py
- novelwriter/dialogs/preferences.py
- novelwriter/extensions/modified.py
- novelwriter/extensions/versioninfo.py
- novelwriter/guimain.py
- novelwriter/tools/manuscript.py
- novelwriter/tools/welcome.py
- tests/test_tools/test_tools_welcome.py
**Summary:**
A second attempt at fixing date formats. This PR sets up the Config class to generate short date and date time formats from GUI locale if selected GUI locale file exists. If not, it will generate these formats from the system locale.
The dates are now used for the Welcome dialog, the About dialog, the Manuscript tool and on the lock file warning. These are the only places using formatted dates at the moment.
A small issue with displaying fallback settings for GUI locale in Preferences has been fixed as well.
Closes #1739
> Prefer GUI locale for date format

- novelwriter/constants.py
- novelwriter/core/buildsettings.py
- novelwriter/core/docbuild.py
- novelwriter/core/toodt.py
- novelwriter/tools/manussettings.py
- tests/reference/coreToOdt_SaveFlat_document.fodt
- tests/reference/mBuildDocBuild_OpenDocument_Lorem_Ipsum.fodt
- tests/test_core/test_core_toodt.py
- tests/test_tools/test_tools_manussettings.py
**Summary:**
This PR simplifies the ODT header format in the Build Settings tool to just fill in the info instead of using placeholders. The `{Page}` placeholder is still needed.
Closes #1757 
> Simplify the ODT header format

- novelwriter/core/index.py
- novelwriter/gui/doceditor.py
- novelwriter/gui/dochighlight.py
- novelwriter/gui/docviewer.py
- novelwriter/gui/editordocument.py
- novelwriter/gui/mainmenu.py
- novelwriter/gui/projtree.py
- novelwriter/guimain.py
- novelwriter/shared.py
- tests/test_core/test_core_index.py
- tests/test_gui/test_gui_doceditor.py
- tests/test_gui/test_gui_docviewer.py
- tests/test_gui/test_gui_guimain.py
**Summary:**
This PR adds a dropdown menu in the header of both the document editor and viewer for quick navigation to any heading defined in it. The PR also cleans refactor a lot of the calls from the editor and viewer to other parts of the GUI to use signals and slots instead of direct calls.
Closes #1059
> Add a document outline dropdown

- novelwriter/core/coretools.py
- novelwriter/core/document.py
- novelwriter/core/index.py
- novelwriter/core/project.py
- novelwriter/core/storage.py
- novelwriter/core/tokenizer.py
- novelwriter/dialogs/docsplit.py
- tests/test_core/test_core_coretools.py
- tests/test_core/test_core_document.py
- tests/test_core/test_core_index.py
- tests/test_core/test_core_storage.py
**Summary:**
This PR adds an alternative and efficient way to read the text of a document when all that is needed is the text content with the meta data stripped. The reader is added as a static method in the NWDocument class, and a wrapper function is added to the NWStorage class.
> Add fast document read

- novelwriter/core/coretools.py
- novelwriter/gui/doceditor.py
- novelwriter/gui/search.py
- novelwriter/guimain.py
- tests/test_core/test_core_coretools.py
- tests/test_gui/test_gui_search.py
**Summary:**
This PR changes the begin search function for the project search panel to use selected text from the editor if the editor has focus when the search is activated.
Closes #1789
> Use selected text for project search

- novelwriter/gui/doceditor.py
- novelwriter/guimain.py
- tests/test_gui/test_gui_doceditor.py
**Summary:**
This PR drops the local caching of the document search options in the search widget class and instead relies on the config settings everywhere they're accessed, and lets the toggle buttons set the configs directly.
Closes #1794
> Improve state persistence of document search buttons

- novelwriter/gui/search.py
**Summary:**
This PR limits the change of background colour on the search panel toolbar to the widget itself. The old stylesheet setting also affected the tooltip labels.
> Fix stylesheet bug

- novelwriter/gui/doceditor.py
- tests/test_core/test_core_tokenizer.py
- tests/test_gui/test_gui_doceditor.py
**Summary:**
Fix auto-deselect (toggle cancelled) when toggling on/off markdown format on selected text.
Closes #1807
> Fix format toggle issue

- novelwriter/text/counting.py
- tests/test_text/test_core_counting.py
**Summary:**
This PR fixes a bug in the part of the word counter that strips alignment codes.
Closes #1816
> Fix index error in word counter

- novelwriter/gui/dochighlight.py
- tests/reference/guiEditor_Main_Final_0000000000011.nwd
- tests/reference/guiEditor_Main_Final_nwProject.nwx
- tests/test_gui/test_gui_guimain.py
**Summary:**
This PR adds a filter that strips shortcodes before the spell checker is run. At the moment, only "sup" and "sub" codes are long enough to get spell checked at all, and in English they pass, but that may not be true for other languages. This PR replaces shortcodes with spaces on the copy of the text that is used for spell checking.
> Fix shortcode spellcheck

- .flake8
- pyproject.toml
- requirements-dev.txt
**Summary:**
This PR:
* Adds an isort config that matches the current practice in the source code. It is not applied yet to the code, so its implementation will be gradual to avoid merge conflicts everywhere.
* Moves the flake8 config into pyproject.toml.
* Adds config for autopep8.
> Add isort and clean up flake8

- .github/workflows/test_linux.yml
- README.md
- novelwriter/__init__.py
- pyproject.toml
- setup/debian/control
- setup/description_pypi.md
- setup/launchpad_setup.cfg
**Summary:**
Since we're no longer supporting Ubuntu 20.04 with native packages from 2.5 release, due to requiring Qt 5.15, we may as well drop Python 3.8 as well as it is causing issues with type annotations. Ubuntu 20.04 uses Python 3.8, but 22.04 has Python 3.10. We could in principle drop Python 3.9 as well, but at the moment it isn't necessary.
> Drop Python 3.8 support

- novelwriter/dialogs/about.py
- novelwriter/extensions/modified.py
- novelwriter/guimain.py
- novelwriter/tools/dictionaries.py
- novelwriter/tools/manuscript.py
- novelwriter/tools/manussettings.py
- novelwriter/tools/noveldetails.py
- novelwriter/tools/writingstats.py
- sample/nwProject.nwx
- tests/test_tools/test_tools_manuscript.py
**Summary:**
This PR:
* Adds dedicated subclasses for non-blocking modal dialogs, and non-modal tools dialog. This collects some common settings into custom classes.
* Cleans up inheritance for the build tool dialogs.
* Fixes a bug when deleting a build when its settings are open.
> Improve dialog handling

- novelwriter/tools/manuscript.py
**Summary:**
This PR fixes a bug that will crash novelWriter if a build settings entry is deleted while its settings dialog is open and the user tries to save the settings again.
> Fix build settings bug

- novelwriter/tools/manusbuild.py
- novelwriter/tools/manuscript.py
- tests/test_tools/test_tools_manuscript.py
**Summary:**
This PR:
* Adds a save document call before generating a build document or a preview.
* Restores the scroll bar position if a build preview is updated.
Closes #1835
Closes #1837
> Updates to the build tool

- novelwriter/shared.py
- tests/test_tools/test_tools_manuscript.py
**Summary:**
This PR adds a check that the Manuscript and Writing Stats dialogs are not left open when a project closes.
> Make sure dialogs close when project closes

- novelwriter/core/buildsettings.py
- novelwriter/core/docbuild.py
- novelwriter/core/tokenizer.py
- novelwriter/core/toodt.py
- novelwriter/tools/manussettings.py
- tests/reference/mBuildDocBuild_OpenDocument_Lorem_Ipsum.fodt
- tests/test_core/test_core_docbuild.py
- tests/test_core/test_core_toodt.py
- tests/test_tools/test_tools_manussettings.py
**Summary:**
This PR:
* Fixes an issue with first line indent after comments.
* Adds settings to customise how the first line indent works,
* Moves the first line indent settings to the Format tab so it can be applied to more than just ODT documents.
Closes #1852
> Improve first line indent

- novelwriter/tools/manuscript.py
**Summary:**
The manuscript tool should only use the document font for the document itself, not the header.
> Fix manuscript tool font issue

- novelwriter/gui/doceditor.py
**Summary:**
Make sure syntax highlighter is initialised when the editor is.
Closes #1865
> Fix syntax highlighter init

- novelwriter/tools/dictionaries.py
- tests/test_tools/test_tools_dictionaries.py
**Summary:**
This PR fixes a bug where the enchant config dir returned by the enchant package does not exist by default, causing a crash when trying to install additional spell check dictionaries.
Closes #1874
> Fix bug in dictionaries install tool

- novelwriter/gui/doceditor.py
- novelwriter/gui/docviewer.py
- novelwriter/gui/theme.py
- novelwriter/tools/manuscript.py
**Summary:**
Due to what appears to be a bug in Qt 5.15.3 when changing document font, this PR reverts the changes of #1842, and instead re-implements the same functionality in a more roundabout but robust way.
Closes #1862
Closes #1875
> Fix how document font is set

- docs/source/more_customise.rst
- novelwriter/assets/themes/cyberpunk_night.conf
- novelwriter/assets/themes/default_dark.conf
- novelwriter/assets/themes/default_light.conf
- novelwriter/assets/themes/dracula.conf
- novelwriter/assets/themes/solarized_dark.conf
- novelwriter/assets/themes/solarized_light.conf
- novelwriter/gui/theme.py
- novelwriter/tools/dictionaries.py
**Summary:**
This PR adds a new error text colour setting to the themes definition. This is used to fix an issue with the dictionary install tool.
> Add error text colur setting to theme

- novelwriter/__init__.py
- novelwriter/common.py
- novelwriter/config.py
- novelwriter/core/buildsettings.py
- novelwriter/core/docbuild.py
- novelwriter/dialogs/preferences.py
- novelwriter/gui/doceditor.py
- novelwriter/gui/dochighlight.py
- novelwriter/gui/docviewer.py
- novelwriter/gui/theme.py
- novelwriter/tools/manuscript.py
- novelwriter/tools/manussettings.py
- tests/conftest.py
- tests/reference/baseConfig_novelwriter.conf
- tests/test_base/test_base_common.py
- tests/test_base/test_base_config.py
- tests/test_dialogs/test_dlg_preferences.py
- tests/test_gui/test_gui_doceditor.py
- tests/test_gui/test_gui_theme.py
- tests/test_tools/test_tools_manussettings.py
**Summary:**
This PR enables the full usage of the font style options for the GUI and document font selection. It saves all available font settings to the config file, but since the full settings include the font size, the old setting has been removed and will be reset to default the first time the app is loaded as 2.5
Closes #1733
> Allow full font style settings for GUI and editor

- novelwriter/dialogs/preferences.py
- pkgutils.py
**Summary:**
This PR:
* Fixes some typos in Preferences
* Adds a check so Debian package files for GitHub release don't include a `~` symbol.
> Post release fixes

- novelwriter/gui/docviewer.py
- novelwriter/gui/mainmenu.py
- novelwriter/guimain.py
- tests/test_gui/test_gui_guimain.py
**Summary:**
This PR updates how documents are loaded in the viewer from the main GUI, and adds some test coverage.
Closes #1884
> Make some improvements to the viewer and test coverage

- novelwriter/extensions/statusled.py
- novelwriter/gui/statusbar.py
- tests/test_gui/test_gui_statusbar.py
**Summary:**
This PR adds the possibility to refresh the StatusLED widget colours when the theme changes,a nd switches to use the trinary enum for values instead of internal integer flags.
Closes #1893
> Refresh StatusLEDs when theme changes

- novelwriter/guimain.py
- requirements-dev.txt
- tests/test_dialogs/test_dlg_projectsettings.py
**Summary:**
This PR moves the project name before the app name in the window title of the main window, as is customary in software, at least on Linux. It makes it clearer what is open in the app when the title is also used by the desktop environment to show open apps.
Closes #1910
> Move project name first in window title

- novelwriter/dialogs/about.py
- novelwriter/dialogs/preferences.py
- novelwriter/dialogs/projectsettings.py
- novelwriter/dialogs/wordlist.py
- novelwriter/extensions/modified.py
- novelwriter/tools/dictionaries.py
- novelwriter/tools/lipsum.py
- novelwriter/tools/noveldetails.py
- tests/test_ext/test_ext_modified.py
- tests/test_tools/test_tools_dictionaries.py
- tests/test_tools/test_tools_lipsum.py
**Summary:**
This PR changes the dialog parent class to overload the virtual `reject()` slot and add a call to `close()` to it. This makes this a usable slot for all dialogs as this is the behaviour we want in novelWriter. It also solves an issue where `close()` is used as a slot, even if it isn't a valid slot.
This also fixes a bug introduced with the `NDialog` class in the 2.5 release cycle.
Closes #1915
> Refactir dialog closing

- novelwriter/guimain.py
- tests/test_tools/test_tools_writingstats.py
**Summary:**
* Fix an issue where multiple Manuscript and Writing Stats dialogs could be opened at once.
* Improve Writing Stats tests.
> Fix multiple tools dialog issue

- novelwriter/common.py
- tests/test_base/test_base_common.py
**Summary:**
File and folder names are currently restricted to mostly alphanumeric characters, plus a few more. This PR changes it so that only non-printable characters are disallowed, plus a handful of other characters primarily disallowed by Windows.
Closes #1917
> Allow more characters to be used in file names

- novelwriter/gui/projtree.py
- novelwriter/shared.py
- novelwriter/tools/manuscript.py
**Summary:**
This PR:
* Adds a method to the shared object that can be called when it is important that the content of the document editor is saved before it is used to perform an action.
* Use this method in the Manuscript tool (replaces the old implementation).
* Adds this to the "Rename to Heading" context menu handler in the project tree.
Closes #1914
> Ensure editor content is saved before using it

- novelwriter/core/tohtml.py
- tests/test_core/test_core_tohtml.py
**Summary:**
This PR rewrites the text formatting method of the HTML converter to ensure format tags aren't opened if they are already open in a paragraph, and always closed at the end of the paragraph. Since shortcodes don't actually ensure tags are closed, unlike the Markdown tag parsing, this is necessary to prevent generating unwanted formatting in the HTML.
Closes #1919
> Ensure HTML tags are properly closed in output documents

- novelwriter/config.py
- novelwriter/constants.py
- novelwriter/core/buildsettings.py
- novelwriter/gui/outline.py
- novelwriter/guimain.py
- novelwriter/tools/manusbuild.py
- novelwriter/tools/welcome.py
- novelwriter/tools/writingstats.py
- tests/conftest.py
- tests/reference/baseConfig_novelwriter.conf
- tests/test_base/test_base_config.py
- tests/test_core/test_core_buildsettings.py
- tests/test_tools/test_tools_manusbuild.py
**Summary:**
This PR rewrites the last path handler to store the last used user path for each tool that uses path lookups, instead of only storing one last path entry for everything. The Welcome dialog new project form now uses this to remember the path the user used last time for creating a project.
Closes #1930
> Remember last used path for each tool individually

- novelwriter/core/coretools.py
- novelwriter/gui/projtree.py
- novelwriter/gui/search.py
- novelwriter/shared.py
- novelwriter/tools/manusbuild.py
- novelwriter/tools/manuscript.py
- tests/test_core/test_core_coretools.py
**Summary:**
This PR:
* Cleans up some save document code in the Shared class, also used by Search.
* Adds a call to refresh the search when changing search options.
* Changes how the search context is generated to include the whole word the search result was found in.
Closes #1830
> Update global search

- .github/workflows/test_linux.yml
- docs/source/more_customise.rst
- novelwriter/assets/themes/cyberpunk_night.conf
- novelwriter/assets/themes/default_dark.conf
- novelwriter/assets/themes/default_light.conf
- novelwriter/assets/themes/dracula.conf
- novelwriter/assets/themes/solarized_dark.conf
- novelwriter/assets/themes/solarized_light.conf
- novelwriter/dialogs/about.py
- novelwriter/dialogs/docmerge.py
- novelwriter/dialogs/docsplit.py
- novelwriter/dialogs/preferences.py
- novelwriter/dialogs/projectsettings.py
- novelwriter/dialogs/wordlist.py
- novelwriter/enum.py
- novelwriter/extensions/configlayout.py
- novelwriter/gui/doceditor.py
- novelwriter/gui/docviewer.py
- novelwriter/gui/mainmenu.py
- novelwriter/gui/outline.py
- novelwriter/gui/theme.py
- novelwriter/guimain.py
- novelwriter/tools/manussettings.py
- novelwriter/tools/noveldetails.py
- tests/test_base/test_base_init.py
- tests/test_gui/test_gui_doceditor.py
- tests/test_gui/test_gui_guimain.py
- tests/test_gui/test_gui_i18n.py
- tests/test_gui/test_gui_noveltree.py
- tests/test_gui/test_gui_projtree.py
**Summary:**
This PR adds hinting about which main app widget has focus, and allows alternating between editor and viewer via keyboard shortcuts again.
Closes #1387
> Add focus widget hinting

- novelwriter/extensions/configlayout.py
**Summary:**
This PR reverts a change from #1940 that uses a font from theme when setting the default font in the custom colour label class. This caused some strange behaviour likely due to a loop somewhere when loading the Preferences dialog, which uses it multiple times.
> Revert font setting in custom class

- novelwriter/dialogs/preferences.py
- novelwriter/extensions/configlayout.py
- novelwriter/gui/doceditor.py
- novelwriter/gui/docviewer.py
- novelwriter/gui/outline.py
- novelwriter/guimain.py
- tests/test_dialogs/test_dlg_preferences.py
**Summary:**
This PR:
* Fixes two issues related to focus/view toggling shortcuts.
* Fixes an issue with some text colours not being updated on theme switch.
* Removes the Apply button in Preferences.
Closes #1949
Closes #1950
Closes #1951
> Fix various minor issues

- novelwriter/core/project.py
**Summary:**
This PR adds path info to the error dialogs that pops up when opening a project path fails.
Closes #1944
> Improve open project error message

- .github/workflows/build_assets.yml
- .github/workflows/build_linux.yml
- .github/workflows/build_win.yml
- .github/workflows/test_linux.yml
- pkgutils.py
- setup/make_pip.sh
- setup/make_release.sh
- setup/win_setup_embed.iss
**Summary:**
This PR:
* Rewrites the `pkgutils.py` file to use `argprase` and `pathlib` everywhere.
* Splits the GitHub Actions build job into one per platform.
* Adds build job for Windows.
* Drops the intermediate zip file for Windows build and build directly from source.
> Rewrite build tools

- novelwriter/core/toqdoc.py
- novelwriter/extensions/statusled.py
**Summary:**
This PR fixes the em unit calculation in the document preview class. It was using font height instead of font ascent as the base unit. This PR also fixes the High DPI scaling of the Status Bar LEDs.
Closes #1961
> Fix preview indent and status bar LEDs

- novelwriter/tools/welcome.py
**Summary:**
This PR adds a new call that switches focus to the required Project Name field when the user activates the New Project Form on the Welcome dialog.
Related #1967
> Add focus switch on welcome dialog

- novelwriter/core/tokenizer.py
- tests/test_core/test_core_tokenizer.py
**Summary:**
This PR fixes an issue where first line text indent state is not preserved between pages.
Closes #1965
> Fix first line indent between pages

- novelwriter/core/project.py
- novelwriter/core/storage.py
- tests/test_core/test_core_storage.py
**Summary:**
This PR removes the automatic lock file writing during project storage initiation and until after project open is completed.
Closes #1977
> Lock project only after successful open

- novelwriter/common.py
- novelwriter/dialogs/preferences.py
- tests/test_base/test_base_common.py
- tests/test_dialogs/test_dlg_preferences.py
**Summary:**
This PR adds a new function that checks free form text box settings in Preferences, and adds constraints to others.
* Narrator break, which can only be one character, has white space stripped,
* Dialog symbol, which can only be one character, has white space stripped.
* Pad before and after symbol box content is now processed so that all white spaces are stripped, and all characters listed are unique. They are also sorted, because the filter uses set, which may return different order on each call.
Closes #1985
> Make sure free form text boxes in Preferences are safe

- novelwriter/guimain.py
- tests/test_gui/test_gui_guimain.py
**Summary:**
This PR fixes an issue where clicking to edit a tag from the reference panel doesn't scroll to the tag position in the text.
Closes #1983
> Improve tag navigation

- novelwriter/core/status.py
- novelwriter/dialogs/projectsettings.py
- novelwriter/gui/docviewerpanel.py
- novelwriter/gui/projtree.py
- novelwriter/guimain.py
- novelwriter/shared.py
- tests/test_dialogs/test_dlg_projectsettings.py
- tests/test_gui/test_gui_docviewerpanel.py
- tests/test_gui/test_gui_projtree.py
- tests/tools.py
**Summary:**
This PR:
* Adds a new signal for updating status or importance labels that is now emitted when the StatusEntry class receives updates.
* Changes the main project tree to also listen to these signals, which calls the method to update item values on all relevant items. This is faster than the previous full tree rebuild.
* The update values function now takes an NWItem as input rather than an item handle. This should be slightly faster in most cases as most callers already have the item ready.
Closes #1992
> Fix updating of importance labels

- pkgutils.py
**Summary:**
Ubuntu 23.10 is obsolete and doesn't accept new uploads, so this has been removed for 2.5.1. Packages for Ubuntu 24.10 pre-release have been added.
> Update Ubuntu releases

- novelwriter/core/tokenizer.py
- novelwriter/gui/docviewer.py
- novelwriter/tools/manuscript.py
- tests/test_core/test_core_tokenizer.py
**Summary:**
This PR fixes a number of bugs with the new document viewer in 2.5:
* Tab stop distances are now properly set after a document is loaded. Loading a new document resets it to default value, and need to be updated.
* The Tokenizer can now properly handle multiple formatting markers that are set on the same character location. Previously, the order of the position-sorted markers would affect whether they came out correctly or not.
* The Tokenizer now only applies dialogue highlighting to plain text paragraphs in novel documents. Previously, the viewer would highlight all quotes as dialog.
Closes #1996
Closes #2011
Closes #2012
Closes #2013
> Fix bugs in the document viewer

- novelwriter/extensions/configlayout.py
- novelwriter/gui/doceditor.py
- novelwriter/gui/docviewer.py
- novelwriter/gui/mainmenu.py
- novelwriter/gui/noveltree.py
- novelwriter/gui/outline.py
- novelwriter/gui/projtree.py
- novelwriter/guimain.py
- novelwriter/shared.py
- novelwriter/tools/welcome.py
- novelwriter/types.py
- tests/conftest.py
- tests/test_base/test_base_shared.py
- tests/test_core/test_core_project.py
- tests/test_dialogs/test_dlg_about.py
- tests/test_dialogs/test_dlg_projectsettings.py
- tests/test_dialogs/test_dlg_wordlist.py
- tests/test_ext/test_ext_eventfilters.py
- tests/test_gui/test_gui_doceditor.py
- tests/test_gui/test_gui_docviewer.py
- tests/test_gui/test_gui_guimain.py
- tests/test_gui/test_gui_i18n.py
- tests/test_gui/test_gui_mainmenu.py
- tests/test_gui/test_gui_noveltree.py
- tests/test_gui/test_gui_outline.py
- tests/test_gui/test_gui_projtree.py
- tests/test_tools/test_tools_lipsum.py
- tests/test_tools/test_tools_manusbuild.py
- tests/test_tools/test_tools_manuscript.py
- tests/test_tools/test_tools_writingstats.py
**Summary:**
This PR cleans up a lot more Qt enums. This is needed for PyQt6 support.
> Clean up Qt enums

- novelwriter/constants.py
- novelwriter/core/coretools.py
- novelwriter/core/tokenizer.py
- novelwriter/gui/dochighlight.py
- novelwriter/gui/editordocument.py
- novelwriter/text/patterns.py
- novelwriter/types.py
- tests/test_core/test_core_coretools.py
- tests/test_text/test_text_patterns.py
**Summary:**
This PR replaces QRegularExpression from Qt with Python's standard library regex module.
There are two reasons for doing this:
* The standard library one is a little bit faster, mostly because there is no need to convert strings when calling it like is needed for the Qt one (I suspect that's the reason anyway).
* The PyQt6 interface th QRegularExpression is broken, at least for Qt 6.4.2. The returned matches are sometimes garbled. Presumably due to UTF-16 to UTF-8 conversion, but I'm not sure. Switching to the Python implementation avoids this problem in the future when we switch to Qt6.
> Replace Qt RegEx with Python RegEx

- novelwriter/core/coretools.py
- novelwriter/core/spellcheck.py
- novelwriter/core/tokenizer.py
- novelwriter/gui/doceditor.py
- novelwriter/gui/dochighlight.py
- tests/test_core/test_core_spellcheck.py
- tests/test_gui/test_gui_doceditor.py
- tests/test_text/test_text_patterns.py
**Summary:**
This PR:
* Improves the spell checker to use the finditer method of pattern object directly. This method allows passing an offset value, which is needed in some places.
* Adds an "Ignore Word" entry to the text editor context menu. This will ignore the word for the duration of the spell checking session, but not save it to the project dictionary.
> Improve spell checking

- novelwriter/core/buildsettings.py
- novelwriter/gui/doceditor.py
- novelwriter/gui/dochighlight.py
- novelwriter/tools/manussettings.py
- tests/test_tools/test_tools_manussettings.py
**Summary:**
This PR moves all the build settings for formatting into a single scrollable page, just like in Preferences.
> Refactor build settings

- novelwriter/core/docbuild.py
- novelwriter/core/toodt.py
- tests/reference/mBuildDocBuild_OpenDocument_Lorem_Ipsum.fodt
- tests/test_core/test_core_docbuild.py
**Summary:**
This PR adds word and character count variables to ODT manuscript files.
Closes #2033
> Add word counts to ODT output

- novelwriter/core/coretools.py
- novelwriter/core/tokenizer.py
- novelwriter/gui/dochighlight.py
- tests/test_text/test_text_patterns.py
**Summary:**
As of Python 3.10, `match` is a reserved keyword, and should not be used as a variable.
> Don't use "match" as a variable

- .github/workflows/test_linux.yml
- pyproject.toml
**Summary:**
Add Python 3.13 to automated tests and to the list of supported versions.
Closes #2040
> Add Python 3.13

- novelwriter/core/docbuild.py
- novelwriter/formats/tohtml.py
- novelwriter/formats/tokenizer.py
- novelwriter/formats/tomarkdown.py
- novelwriter/formats/toodt.py
- novelwriter/formats/toqdoc.py
- novelwriter/formats/toraw.py
- novelwriter/tools/manusbuild.py
- tests/reference/mBuildDocBuild_NWD_Lorem_Ipsum.json
- tests/test_core/test_core_docbuild.py
- tests/test_formats/test_fmt_tohtml.py
- tests/test_formats/test_fmt_tokenizer.py
- tests/test_formats/test_fmt_tomarkdown.py
**Summary:**
This PR refactors the NWBuildDocument class by making the format classes more uniform,a nd thus simplify the loops calling them. It also adds a ToRaw class for writing the dump of the minimally processed text with novelWriter format.
This is a follow-up of MR #2045
> Refaactor document builder

- .github/workflows/test_linux.yml
- docs/source/more_customise.rst
- novelwriter/assets/themes/default_light.conf
- pyproject.toml
- setup/launchpad_setup.cfg
**Summary:**
This MR adds Python 3.13 support for the 2.5 branch and fixes an issue with the default light theme. It also fixes a broken link in the docs.
Closes #2042
Closes #2057
> Add Python 3.13 and fix theme issue

- novelwriter/common.py
- novelwriter/constants.py
- novelwriter/core/buildsettings.py
- novelwriter/core/docbuild.py
- novelwriter/enum.py
- novelwriter/formats/todocx.py
- novelwriter/formats/tohtml.py
- novelwriter/formats/tokenizer.py
- novelwriter/formats/toodt.py
- novelwriter/tools/manussettings.py
- sample/nwProject.nwx
- tests/reference/fmtToDocX_SaveDocument_Content_Types.xml
- tests/reference/fmtToDocX_SaveDocument_app.xml
- tests/reference/fmtToDocX_SaveDocument_core.xml
- tests/reference/fmtToDocX_SaveDocument_document.xml
- tests/reference/fmtToDocX_SaveDocument_document.xml.rels
- tests/reference/fmtToDocX_SaveDocument_footnotes.xml
- tests/reference/fmtToDocX_SaveDocument_header1.xml
- tests/reference/fmtToDocX_SaveDocument_header2.xml
- tests/reference/fmtToDocX_SaveDocument_rels
- tests/reference/fmtToDocX_SaveDocument_settings.xml
- tests/reference/fmtToDocX_SaveDocument_styles.xml
- tests/test_base/test_base_common.py
- tests/test_core/test_core_buildsettings.py
- tests/test_core/test_core_docbuild.py
- tests/test_formats/test_fmt_todocx.py
- tests/test_formats/test_fmt_toodt.py
- tests/test_tools/test_tools_manussettings.py
- tests/tools.py
**Summary:**
This PR adds DocX output to the Manuscript Build tool.
There is a small drop in code coverage from uncovered lines in the DocX class. These lines will be removed in a later MR when some of the code is merged with the ODT class.
Closes #1537 
> Add DocX support

- novelwriter/text/counting.py
- tests/reference/coreIndex_LoadSave_tagsIndex.json
- tests/test_text/test_text_counting.py
**Summary:**
This fixes a small issue where footnote markers aren't stripped before the character count, resulting in it being included in the count.
> Fix counting error

- novelwriter/assets/i18n/project_en_GB.json
- novelwriter/constants.py
- novelwriter/core/buildsettings.py
- novelwriter/core/docbuild.py
- novelwriter/enum.py
- novelwriter/formats/todocx.py
- novelwriter/formats/tohtml.py
- novelwriter/formats/tokenizer.py
- novelwriter/formats/tomarkdown.py
- novelwriter/formats/toodt.py
- novelwriter/formats/toqdoc.py
- novelwriter/gui/doceditor.py
- novelwriter/gui/mainmenu.py
- novelwriter/text/patterns.py
- sample/content/53b69b83cdafc.nwd
- sample/content/ba8a28a246524.nwd
- sample/nwProject.nwx
- tests/reference/mBuildDocBuild_NWD_Lorem_Ipsum.json
- tests/reference/mBuildDocBuild_NWD_Lorem_Ipsum.txt
- tests/test_core/test_core_docbuild.py
- tests/test_formats/test_fmt_todocx.py
- tests/test_formats/test_fmt_tohtml.py
- tests/test_formats/test_fmt_tokenizer.py
- tests/test_formats/test_fmt_tomarkdown.py
- tests/test_formats/test_fmt_toodt.py
- tests/test_gui/test_gui_mainmenu.py
- tests/test_text/test_text_counting.py
- tests/test_text/test_text_patterns.py
**Summary:**
This PR:
* Adds a new shortcode `[br]` that can be used to insert forced line breaks in text paragraphs. They only work in plain text paragraphs that already support line breaks. If they are put anywhere else, they are stripped out when building the document or manuscript. There are other ways to add breaks in headings.
* Move the handling of line breaks in heading to the Tokenizer class so that the format classes can ignore these.
* Fixes a bug in the raw output format that was stripping the alignment and indentation tags.
Closes #1991
> Add forced line breaks feature

- novelwriter/dialogs/preferences.py
- novelwriter/formats/tokenizer.py
- novelwriter/gui/dochighlight.py
- novelwriter/text/patterns.py
- tests/reference/guiEditor_Main_Final_000000000000f.nwd
- tests/reference/guiEditor_Main_Final_nwProject.nwx
- tests/test_formats/test_fmt_tokenizer.py
- tests/test_gui/test_gui_guimain.py
- tests/test_text/test_text_patterns.py
**Summary:**
This PR rewrites the RegEx-based narrator break highlighting for dialogue with a string-split based one that better handles the various use cases.
Closes #2066
> Rewriter narrator break for dialogue highlighting

- novelwriter/constants.py
- novelwriter/core/index.py
- novelwriter/enum.py
- novelwriter/gui/outline.py
- tests/test_core/test_core_index.py
- tests/test_gui/test_gui_outline.py
**Summary:**
This PR adds support for referencing tags in novel documents using the `@story` reference keyword. The tags were already collected by the indexer, so it was as easy as adding the keyword to the valid list, and exposing it on the Outline panel.
This PR also adds the `@mention` references to the Outline details panel, where they were missing.
Closes #1990
> Add support for referencing tags in novel documents

- novelwriter/common.py
- novelwriter/gui/mainmenu.py
- novelwriter/guimain.py
**Summary:**
This PR:
* Moves the linking of menu action objects to the main GUI to where the actions are defined instead of pulling them in a utility function.
* Adds a new `qtLambda` function to be used for Qt signals when passing custom arguments. This strips the original arguments, and properly sets a None return value. For Qt6, the linter will otherwise complain about this. This also solves the problems of generating slots using lambdas in for loops. Python will by default not generate new lambdas for each cycle, so it has to be tricked. Otherwise, all elements in the loop will end up with the last lambda generated.
> Refactor main menu

- novelwriter/core/docbuild.py
- novelwriter/dialogs/preferences.py
- novelwriter/formats/tokenizer.py
- novelwriter/gui/doceditor.py
- novelwriter/gui/dochighlight.py
- novelwriter/gui/docviewer.py
- novelwriter/text/patterns.py
- tests/reference/guiEditor_Main_Final_000000000000f.nwd
- tests/reference/guiEditor_Main_Final_nwProject.nwx
- tests/test_formats/test_fmt_tohtml.py
- tests/test_formats/test_fmt_tokenizer.py
- tests/test_formats/test_fmt_toodt.py
- tests/test_formats/test_fmt_toqdoc.py
- tests/test_gui/test_gui_doceditor.py
- tests/test_gui/test_gui_guimain.py
- tests/test_text/test_text_patterns.py
**Summary:**
This PR attempts to add a new dialogue parser that is more configurable. It also adds auto-replace for four hyphens with a horizontal bar (U+2015).
See #1773
Closes #2070 
> Add a dialogue parser

- novelwriter/assets/i18n/project_en_GB.json
- novelwriter/core/coretools.py
- novelwriter/core/docbuild.py
- novelwriter/core/options.py
- novelwriter/formats/todocx.py
- novelwriter/formats/tohtml.py
- novelwriter/formats/tokenizer.py
- novelwriter/formats/toodt.py
- novelwriter/formats/toqdoc.py
- novelwriter/tools/manuscript.py
- novelwriter/types.py
- tests/reference/coreTools_ProjectBuilderA_Project.md
- tests/reference/coreTools_ProjectBuilderB_Project.md
- tests/test_core/test_core_coretools.py
- tests/test_core/test_core_docbuild.py
- tests/test_tools/test_tools_manuscript.py
**Summary:**
This PR adds markers for page breaks for the Manuscript Build tool preview. It also fixes some inconsistencies in how page breaks are applied.
> Make page breaks visible in manuscript preview

- novelwriter/formats/tokenizer.py
- novelwriter/formats/toraw.py
- tests/reference/mBuildDocBuild_NWD_Lorem_Ipsum.json
- tests/reference/mBuildDocBuild_NWD_Lorem_Ipsum.txt
- tests/test_core/test_core_docbuild.py
- tests/test_formats/test_fmt_tokenizer.py
**Summary:**
This PR simplifies the collection of the "Raw" novelWriter build format which just keeps the original text.
> Simplify collection of raw text

- novelwriter/constants.py
- novelwriter/enum.py
- novelwriter/gui/outline.py
- tests/test_gui/test_gui_outline.py
**Summary:**
This PR adds the status label and icon as a column for the project outline.
Closes #1909
> Add status column to project outline

- novelwriter/gui/docviewer.py
- novelwriter/gui/outline.py
- novelwriter/guimain.py
- pyproject.toml
- tests/test_base/test_base_init.py
- tests/test_gui/test_gui_docviewer.py
- tests/test_gui/test_gui_guimain.py
**Summary:**
This PR:
* Adds an edit button to the viewer, which will open the document in the editor.
* Fixes an issue where the app could no longer be closed if the project was closed first.
* Fixes an issue with saving the Outline view details panel splitter position if the Outline tab has not been activated during a writing session.
Closes #1963
> Various GUI improvements

- novelwriter/assets/icons/typicons_dark/icons.conf
- novelwriter/assets/icons/typicons_dark/nw_toolbar.svg
- novelwriter/assets/icons/typicons_light/icons.conf
- novelwriter/assets/icons/typicons_light/nw_toolbar.svg
- novelwriter/gui/doceditor.py
- novelwriter/gui/theme.py
**Summary:**
This PR replaces the toolbar show/hide icon with a new one that is distinct from the three dots menu icon. The toolbar is not a menu.
> Update editor toolbar icon

- novelwriter/tools/manusbuild.py
- tests/test_tools/test_tools_manusbuild.py
**Summary:**
This PR turns on auto default on all other buttons than "Build" on the Build dialog.
Closes #2101
> Fix default button issue on Build dialog

- novelwriter/gui/projtree.py
**Summary:**
This PR solves two issues in the fallback code that double-checks against a sporadic Qt bug.
In novelWriter, drag and drop is disabled on the project tree root item. However, in several version of Qt 5.15 9at least) this flag is ignored. There is therefore code in place to check that these drops are blocked even when the flag is ignored. (The flag is still useful because it provides visual clues to the drag and drop when it *does* work.)
Fixes:
* If a non-root project item somehow ends up on the project tree root, it could not be deleted because the delete item function assumed that all project items without a parent also had a parent widget in the tree, in which case the parent() call would return None. This fix uses the invisible root item instead now, if this occurs, …
> Fix secondary issues due to Qt tree widget bug

- novelwriter/__init__.py
- tests/test_base/test_base_init.py
**Summary:**
This PR adds colours to the log output when the `--color` flag is provided.
> Add ANSI colours to log output

- novelwriter/__init__.py
- tests/test_base/test_base_init.py
> Rewrite log colouring

- novelwriter/formats/todocx.py
- novelwriter/formats/toodt.py
- tests/reference/fmtToDocX_SaveDocument_document.xml
- tests/reference/fmtToOdt_SaveFlat_document.fodt
- tests/reference/fmtToOdt_SaveFull_styles.xml
- tests/reference/mBuildDocBuild_OpenDocument_Lorem_Ipsum.fodt
- tests/test_formats/test_fmt_todocx.py
**Summary:**
This PR changes how page headers in ODT and DocX documents are aligned. They are now approximately half a line above the top margin for both formats.
Closes #2120
> Align headers to bottom of page margin for ODT and DocX

- novelwriter/gui/doceditor.py
- tests/test_gui/test_gui_doceditor.py
- tests/test_gui/test_gui_guimain.py
**Summary:**
This PR moves auto-replace into its own class. The new implementation is likely a minor improvement in the cases were only some auto-replace features are enabled, and should perform about the same in cases where many or all are in use. Mainly, it is just a refactoring to separate it from the main editor code and move all its associated class attributes.
Related to #2129
> Improve editor auto-replace

- novelwriter/gui/projtree.py
- sample/nwProject.nwx
**Summary:**
This PR fixes a bug where it was not possible to change the status/importance value for folders. The method that applies the change explicitly filtered for files. I don't know how that check snuck in there, because it wasn't there in the old implementation. Probably a bad copy/paste when it was re-implemented for the new tree.
Closes #2145
> Fix project tree status/importance for folders

- docs/source/project_overview.rst
- novelwriter/config.py
- novelwriter/extensions/modified.py
- novelwriter/gui/statusbar.py
- tests/reference/baseConfig_novelwriter.conf
- tests/test_ext/test_ext_modified.py
- tests/test_gui/test_gui_statusbar.py
**Summary:**
This PR makes the status bar timer label clickable, and makes it possible to show or hide it when clicked. When hidden, only the timer icon is visible. Clicking the icon will show the timer label again. The show/hide state persists between sessions.
Closes #1029
> Hide session timer

- novelwriter/dialogs/projectsettings.py
- novelwriter/guimain.py
- tests/test_dialogs/test_dlg_projectsettings.py
**Summary:**
This PR removes the "Apply" button for editing entries in Status and Importance flags, and for Auto-Replace entries. The changes are instead applied immediately.
Closes #2150
> Remove "Apply" buttons in Project Settings

- novelwriter/core/projectdata.py
- novelwriter/core/status.py
- novelwriter/dialogs/projectsettings.py
- novelwriter/dialogs/wordlist.py
- novelwriter/gui/outline.py
- tests/test_core/test_core_status.py
- tests/test_dialogs/test_dlg_projectsettings.py
**Summary:**
This PR adds import and export functionality to status and importance labels in Project Settings. The file format is a simple CSV file with shape, colour and label text.
Closes #1847
> Add Import/export of status labels

- novelwriter/dialogs/projectsettings.py
- tests/test_dialogs/test_dlg_projectsettings.py
**Summary:**
This PR fixes an issue where the changed flag was net set at import, so the changes were ignored when clicking "Save".
> Make sure imported status labels are saved

- novelwriter/gui/doceditor.py
**Summary:**
The selection counter in the editor should take precedence over the scheduled word counter.
Closes #2155
> Fix minor issue with editor word counter

- novelwriter/gui/doceditor.py
**Summary:**
This PR splits the if statement in #2156 as the notify needs to run even if the counter is not updated on the editor footer.
Related #2155
> Fix minor bug from #2156

- novelwriter/gui/search.py
**Summary:**
Drop the widget wrapper that was used in the search panel header. I think it's unnecessary, and it doesn't update properly when theme is changed.
Closes #2162
> Fix search panel theme update bug

- novelwriter/extensions/novelselector.py
**Summary:**
The previous selected item must be stored before clearing the dropdown box in the novel selector widget.
> Fix novel selector bug

- novelwriter/extensions/novelselector.py
- novelwriter/gui/outline.py
**Summary:**
This ensures that all icons are reloaded for the outline view.
Discussion: https://github.com/vkbo/novelWriter/discussions/2175#discussioncomment-11803712
> Fix bug in theme update in outline view

- novelwriter/gui/projtree.py
**Summary:**
This fixes a bug where the project tree selection model is None if no model has ever been loaded.
Closes #2173
> Make sure selection model exists before accessing

- .github/workflows/test_linux.yml
- README.md
- novelwriter/__init__.py
- novelwriter/common.py
- novelwriter/core/itemmodel.py
- novelwriter/core/project.py
- novelwriter/core/status.py
- pyproject.toml
- setup/debian/control
- setup/description_pypi.md
- setup/launchpad_setup.cfg
**Summary:**
This PR drops support for Python 3.9:
* Releases are mainly done with 3.12 anyway.
* Python 3.9 is annoying due to features it's missing.
* Oldest Ubuntu release supported, 22.04, already has Python 3.10.
* Python 3.9 reaches end of life this year anyway (in October).
> Drop Python 3.9

- novelwriter/gui/doceditor.py
- novelwriter/gui/docviewer.py
- novelwriter/gui/itemdetails.py
- novelwriter/gui/projtree.py
- novelwriter/tools/welcome.py
- tests/test_gui/test_gui_doceditor.py
- tests/test_tools/test_tools_welcome.py
**Summary:**
This PR:
* Backports from 2.7 a potential undefined variable error fix in the editor.
* Backports from 2.7 a word wrap fix for long importance/status labels in the item details panel.
* Backports from 2.7 dropping all deleteLater calls for context menus. Something somewhere is causing an occasional segfault when exiting. It seems harmless, but still not good.
* Fixes an issue with the project tree context menu when right-clicking in an empty area of the tree. It opens a menu associated with the selected item, even if that item is a different place in the tree. It's harmless, but misleading.
> Make some minor code and GUI fixes

- novelwriter/common.py
- novelwriter/config.py
- novelwriter/core/project.py
- tests/test_base/test_base_config.py
- tests/test_tools/test_tools_welcome.py
**Summary:**
Add a UUID record to recent projects so that duplicate entries of the same project can be avoided.
Closes #2217
> Track recent projects via UUID

- novelwriter/__init__.py
**Summary:**
This PR adds support for [NO_COLOR](http://no-color.org/) and [FORCE_COLOR](https://force-color.org/) environment variables. It also adds single character switches for these command line flags.
> Add support for log colour env variables

- novelwriter/config.py
- novelwriter/constants.py
- novelwriter/dialogs/preferences.py
- novelwriter/gui/doceditor.py
- tests/reference/baseConfig_novelwriter.conf
- tests/test_dialogs/test_dlg_preferences.py
**Summary:**
This PR:
* Gathers all settings in Preferences related to the Project Tree under a new section.
* Adds a setting for the editor cursor width.
Closes #2219
> Reorganise preferences and add cursor width setting

- i18n/nw_base.ts
- i18n/nw_cs_CZ.ts
- i18n/nw_de_DE.ts
- i18n/nw_en_US.ts
- i18n/nw_es_419.ts
- i18n/nw_fr_FR.ts
- i18n/nw_it_IT.ts
- i18n/nw_ja_JP.ts
- i18n/nw_nb_NO.ts
- i18n/nw_nl_NL.ts
- i18n/nw_pl_PL.ts
- i18n/nw_pt_BR.ts
- i18n/nw_ru_RU.ts
- i18n/nw_zh_CN.ts
- novelwriter/constants.py
- novelwriter/dialogs/projectsettings.py
- novelwriter/gui/itemdetails.py
- novelwriter/gui/mainmenu.py
- novelwriter/gui/outline.py
- novelwriter/tools/manuscript.py
**Summary:**
This PR changes the context name for status label icon shapes from Shapes back to Constants and restores the old translations.
Related #2246
> Change context of shape translation strings

- .github/pull_request_template.md
- .github/workflows/syntax.yml
- .github/workflows/test_linux.yml
- novelwriter/common.py
- novelwriter/core/buildsettings.py
- novelwriter/dialogs/docmerge.py
- novelwriter/dialogs/docsplit.py
- novelwriter/extensions/switch.py
- novelwriter/formats/tokenizer.py
- novelwriter/formats/toodt.py
- novelwriter/gui/dochighlight.py
- novelwriter/tools/manuscript.py
- pyproject.toml
- requirements-dev.txt
- tests/reference/guiEditor_Main_Final_000000000000f.nwd
- tests/reference/guiEditor_Main_Final_nwProject.nwx
- tests/test_gui/test_gui_doceditor.py
- tests/test_gui/test_gui_guimain.py
**Summary:**
This adds a requirement that pyright typechecking must pass on PRs. It also fixes a number of type errors in the code.
> Add Pyright to syntax checking workflow, and fix errors

- utils/build_windows.py
**Summary:**
This PR removes the shebang from the launch script generated for Windows install.
Closes #1284
> Fix Windows launch script for manual usage

- novelwriter/core/tree.py
- novelwriter/gui/projtree.py
- tests/test_core/test_core_tree.py
- tests/test_gui/test_gui_projtree.py
**Summary:**
This PR changes how the location of new documents is picked. It also adds the possibility to create partition documents directly from the menu.
The new logic is such that if you select a child document of another document, like a scene below a chapter, and select to create a new document of a higher level, like another chapter, it will be created as a sibling of the parent instead. This makes more sense when the user has the last scene of a chapter selected and wants to create a new chapter.
The same rules apply to all levels, so also works for partitions. Even if you have section level documents under scenes.
Closes #2260
> Improve placement of new documents

- .github/workflows/build_assets.yml
- docs/source/index.rst
- docs/source/tech_source.rst
- novelwriter/config.py
- pkgutils.py
- utils/assets.py
- utils/docs.py
**Summary:**
This PR:
* Adds compression to the `sample.zip` file.
* Combines all docs PDF build commands in `pkgutils.py`, and renames the localised versions.
* Adds docs HTML build command that outputs to `dist_doc`, and can be used for packaging. See #907 and #2278.
* Fixes asset inclusion in image builds to include PDFs for all languages.
* Makes a few updates in the docs.
Closes #2278
> Update package utils and docs

- novelwriter/config.py
- tests/test_base/test_base_config.py
**Summary:**
There appears to be a datetime truncation issue in PyQt6 where datetime using QLocale are truncated to a QDate somewhere, causing the time part to not be printed. This PR finxes it by explicitly converting the Python datetime to QDate and QDateTime first instead of relying on PyQt6.
Closes #2325
> Fix datetime truncation bug

- novelwriter/core/itemmodel.py
- novelwriter/core/novelmodel.py
- novelwriter/dialogs/docmerge.py
- novelwriter/dialogs/docsplit.py
- novelwriter/dialogs/editlabel.py
- novelwriter/dialogs/preferences.py
- novelwriter/dialogs/projectsettings.py
- novelwriter/extensions/configlayout.py
- novelwriter/extensions/switch.py
- novelwriter/extensions/switchbox.py
- novelwriter/gui/noveltree.py
- novelwriter/gui/projtree.py
- novelwriter/gui/search.py
- novelwriter/tools/lipsum.py
- novelwriter/tools/manussettings.py
- novelwriter/tools/noveldetails.py
- novelwriter/tools/writingstats.py
- tests/test_tools/test_tools_writingstats.py
**Summary:**
This PR:
* Updates the custom switch widget to animate on all forms of user click, not just mouse click.
* Add a highlight colour to the switch when it has focus, making it visible when tabbing through a form.
* Associate all switches with a label, or if not possible, give them an accessibility name.
* Adds an accessibility label to the project and novel trees and improves the read-out for the rows.
* Settings forms now include all text in the various labels associated with a setting in the accessibility text.
Closes #2106
Closes #2107
> Update accessibility for switches, settings and trees

- novelwriter/core/buildsettings.py
- novelwriter/tools/manussettings.py
- tests/test_tools/test_tools_manussettings.py
**Summary:**
This PR fixes a long present issue that some build settings for the manuscript are applied without saving the changes and some are not. It also fixes a bug in the tracking of settings changes that are used to pop a dialog box if the settings dialog is closed with the window X button.
The way this is solved is that the build settings dialog works on a copy of the build settings object rather than the original. Applying changes were always done through emitting the build object, so that did not need to be changed. It now just saves the new object over the old instead.
Closes #2350
> Change behaviour of build settings on close

- novelwriter/guimain.py
- novelwriter/shared.py
**Summary:**
This PR adds a check when resizing the main window to ensure that the size cannot exceed the size of the screen the app is loading on.
Closes #2354
> Block main GUI from getting larger than screen

- novelwriter/constants.py
- novelwriter/core/index.py
- novelwriter/core/item.py
- novelwriter/gui/doceditor.py
- tests/test_core/test_core_index.py
**Summary:**
This PR fixes the following:
* When an item is moved to an inactive type root folder, the item is properly deleted from the index instead of just having is class reference updated.
* When the auto-complete menu is no longer needed, it is properly closed, not only hidden. On Windows. a hidden context menu still kept its focus, making the editor no longer respond to return and arrow keys.
* The `@tag` keyword no longer returns a list of all tags in the auto-complete menu.
Closes #2386
Closes #2387
> Fix tag and auto-complete bugs

- novelwriter/formats/tohtml.py
- tests/reference/mBuildDocBuild_HTML5_Lorem_Ipsum.htm
- tests/test_formats/test_fmt_tohtml.py
**Summary:**
This PR:
* Strips inline color tags from HTML manuscript when CSS styles are off.
* Allows other inline paragraph level styles when CSS styles are off.
* Adds viewport meta tag to head when CSS styles are on.
* Improves test coverage.
Closes #2358
> Make HTML output more consistent

- novelwriter/config.py
- novelwriter/constants.py
- novelwriter/formats/tokenizer.py
- novelwriter/formats/toqdoc.py
- novelwriter/tools/manuscript.py
- novelwriter/tools/manussettings.py
- novelwriter/types.py
- tests/test_formats/test_fmt_tokenizer.py
- tests/test_formats/test_fmt_toqdoc.py
**Summary:**
This PR fixes a bug with page breaks on each line of a multi-line heading in PDFs and previews. Anything generated from a QTextDocument.
Closes #2415
> Fix page breaks in PDFs

- novelwriter/core/index.py
- novelwriter/core/indexdata.py
- novelwriter/gui/noveltree.py
- sample/content/636b6aa9b697b.nwd
- sample/nwProject.nwx
- tests/test_core/test_core_index.py
- tests/test_core/test_core_indexdata.py
**Summary:**
This PR adds the tag to reference data extracted from the index. This was apparently missing in the implementation when the `@story` tag was added in #2072.
Closes #2428
> Fix missing tag display in outline

- pyproject.toml
**Summary:**
Revert the license field in the pyproject.toml file to the older format, which causes less build issues than the newer format.
Closes #2434
> Revert license field

- novelwriter/common.py
- tests/test_dialogs/test_dlg_preferences.py
**Summary:**
This PR fixes an issue where `%` symbols could not be used in string settings field since this symbol by default is used for copying values from other fields in the ConfigParser used by the Config class. This has been broken since day 1, but no one has reported it yet. It actually crashes novelWriter.
This feature is now turned off.
Closes #2455
> Fix ConfigParser interpolation

- novelwriter/common.py
- novelwriter/dialogs/preferences.py
- tests/test_dialogs/test_dlg_preferences.py
**Summary:**
This PR:
* Moves the open ended dialogue switch above the alternate dialogue box so not to confuse them as the setting only applies to quoted dialogue.
* Add a button and menu to add symbols to the dialogue line symbols box as it isn't clear what symbols are allowed in it. It is also difficult to type these symbols on many keyboards.
Closes #2453
Closes #2454
> Improve dialogue highlighting settings

- novelwriter/core/projectxml.py
- novelwriter/core/status.py
- tests/test_core/test_core_status.py
**Summary:**
This PR fixes a bug where the colour was reset to black when switching theme for status and importance labels using a custom colour.
Closes #2452
> Fix colour reset bug for status labels

- novelwriter/gui/mainmenu.py
- novelwriter/guimain.py
**Summary:**
This PR makes `Ctrl+T` and `Ctrl+Shift+T` available also when in Focus Mode. Triggering them will exit Focus Mode and switch the views.
Closes #1294
> Expose tree and outline shortcuts in Focus Mode

- novelwriter/gui/doceditor.py
- tests/test_gui/test_gui_doceditor.py
**Summary:**
This PR extends the auto-replace of quotes to better handle cases where there is Markdown markup wrapping the quoted string. It also adds dedicated tests for the text auto-replacer.
Closes #2488
> Improve auto-replace quotes with markup

- novelwriter/config.py
- novelwriter/dialogs/preferences.py
- novelwriter/gui/dochighlight.py
- tests/reference/baseConfig_novelwriter.conf
- tests/test_dialogs/test_dlg_preferences.py
**Summary:**
This PR changes the highlight multiple spaces feature in the editor to not highlight trailing spaces, which will always blink at the end of the current sentence when the user is writing.
Closes #2501
> Drop highlighting trailing spaces

- novelwriter/common.py
- tests/test_base/test_base_common.py
**Summary:**
This PR fixes an issue where the Qt font matching algorithm gets limited by a style name being set when the font settings value is parsed from the font dialog. Basically, selecting a style in the font dialog populates the style name value and passes it to the `styleName` property of the `QFont` object. This actually goes against the recommendation in the Qt docs on mixing style name with explicit weight/emphasis settings. This PR explicitly sets the `styleName` property to None in the custom `fontMatcher` helper function.
Closes #2502
Related #2110
> Fix font matching style bug

- novelwriter/gui/doceditor.py
- novelwriter/types.py
- tests/test_gui/test_gui_doceditor.py
**Summary:**
Repositions the IME suggestion windows so they don't block the text. Works for Japanese and Chinese at least:
Closes #2267
> Adjust windows for IME conversion suggestions to not cover text
