tests/reference/itemedit_nwProject.nwx, tests/reference/projedit_nwProject.nwx, tests/test_gui.py
Adds tests for word counter, project editor dialog and item editor dialog.
=> Test Coverage - Part II

nw/config.py, nw/gui/doceditor.py, nw/gui/docviewer.py, nw/gui/mainmenu.py, nw/gui/winmain.py, nw/project/project.py, nw/themes/default.css, sample/sampleNovel/nwProject.nwx, tests/reference/gui/1_nwProject.nwx, tests/reference/gui/2_nwProject.nwx, tests/reference/gui/3_nwProject.nwx, tests/reference/novelwriter.conf, tests/reference/proj/1_nwProject.nwx, tests/reference/proj/2_nwProject.nwx, tests/test_config.py, tests/test_gui.py
This PR adds a second split pane in the main windows where documents can be viewed (but not edited).
=> Split Pane Preview

nw/gui/doceditor.py, nw/gui/docviewer.py, nw/gui/mainmenu.py, nw/gui/winmain.py, nw/project/document.py, nw/project/project.py, sample/sampleNovel/nwProject.nwx, tests/reference/gui/0_nwProject.nwx, tests/test_gui.py
Changed the way creating new, and closing projects is done to make it more robust.
Some new rukes:
* A new project cannot be created without first closing the current one.
* A new project has to be assigned a location first.
* The location cannot contain an existing project.
Also added functions to clear the project and document, and clear the GUI.
=> Project Handling

nw/gui/doceditor.py, nw/gui/doctree.py, nw/gui/mainmenu.py, nw/gui/winmain.py
Make sure no menu items crashes the app when there is no project open
=> Menu bugfix

help/en_GB/index.html, nw/config.py, nw/gui/doceditor.py, nw/gui/docviewer.py, nw/gui/mainmenu.py, nw/gui/winmain.py, nw/theme.py, nw/themes/default/styles.css, nw/themes/default/theme.conf
Added a menu entry to open the documentation, and added a lot of information in a html file.
=> Documentation

nw/gui/projecteditor.py, tests/test_gui.py
Makes the auto-replace items in project settings editable.
=> Editable Auto-Replace Items

nw/config.py, nw/gui/configeditor.py, nw/gui/doceditor.py, nw/gui/docviewer.py, nw/gui/winmain.py, tests/reference/novelwriter.conf
Thic PR changes how document margins are handled. This seems to work better, and drops the difference between horizontal and vertical margins in favour of using the QDocument margin setting.
Preferences dialog changed accordingly.
=> Document Margins

nw/theme.py, nw/themes/gui/default_dark/theme.conf
Added support for highlighted and link colour in themes
=> Minor Themes Update

nw/themes/syntax/tomorrow.conf, sample/sampleNovel/nwProject.nwx
One of the tomorrow themes had the wrong set of colours
=> Themes Fix

nw/convert/htmlfile.py, nw/convert/markdownfile.py, nw/convert/textfile.py, nw/convert/tohtml.py, nw/convert/tokenizer.py, nw/convert/tomarkdown.py, nw/gui/export.py
Adds export formats for markdown and html files.
=> Export to Markdown and Html

nw/config.py, nw/constants.py, nw/gui/export.py, nw/gui/timelineview.py, nw/gui/winmain.py, nw/project/index.py, nw/tools/optlaststate.py, sample/sampleNovel/data_6/36b6aa9b697b_main.nwd, sample/sampleNovel/data_b/c0cbd2a407f3_main.nwd, sample/sampleNovel/nwProject.nwx, tests/reference/novelwriter.conf
Added filters to the timeline view GUI.
=> Timeline Update

nw/convert/file/latex.py, nw/convert/text/tolatex.py
This PR addresses issues #75 and #77.
=> LaTeX bug fixes

nw/config.py, nw/gui/configeditor.py, nw/gui/doceditor.py, nw/gui/doctree.py, nw/gui/mainmenu.py, sample/sampleNovel/data_6/36b6aa9b697b_main.nwd, sample/sampleNovel/nwProject.nwx, tests/reference/novelwriter.conf
This PR:
* Adds the option to show tabs/spaces and line endings in the editor. Suggestion #88.
* Cleans up the Preferences GUI a bit.
=> More Gui Tweaks

.codecov.yml, nw/gui/doceditor.py, nw/gui/docviewer.py
This PR adds the ability to follow tags.
Features:
* Pressing `Ctrl+Enter` on a tag name opens the file in the view pane.
* The same happens on a `Ctrl+LeftClick` on a tag.
ToDo:
* Display an overview of other files linking to the tag at the bottom of the view pane.
=> Follow Tags

nw/convert/file/concat.py, nw/convert/file/text.py, nw/gui/export.py, sample/sampleNovel/data_b/8136a5a774a0_main.nwd, sample/sampleNovel/nwProject.nwx
This PR addresses issues #99 and #100.
* The Pandoc export should use the already expanded save path.
* The export should always exclude files in the trash and orphaned folders.
=> Export Fixes

nw/config.py, nw/convert/file/concat.py, nw/convert/tokenizer.py, nw/gui/dialogs/configeditor.py, nw/gui/dialogs/export.py, nw/gui/dialogs/itemeditor.py, nw/gui/dialogs/projecteditor.py, nw/gui/dialogs/sessionlog.py, nw/gui/dialogs/timelineview.py, nw/gui/elements/doceditor.py, nw/gui/elements/doctree.py, nw/gui/elements/docviewer.py, nw/gui/elements/noticebar.py, nw/gui/elements/searchbar.py, nw/gui/elements/viewdetails.py, nw/gui/mainmenu.py, nw/gui/statusbar.py, nw/gui/theme.py, nw/gui/tools/dochighlight.py, nw/guimain.py, nw/project/backup.py, nw/project/index.py, nw/project/item.py, nw/project/status.py, nw/tools/translate.py
=> Code Cleanup

nw/gui/elements/doceditor.py, nw/gui/tools/dochighlight.py, nw/guimain.py
Trying to fix some weird spell checker highlighting issues where and adjusting for Qt's inability to properly select words wrapped in unicode quote characters.
=> Spell Check Fixes

.gitignore, tests/profilestats.py
Added script for plotting profiling data
=> Collecting Profiling Data

nw/gui/elements/doceditor.py, nw/gui/mainmenu.py, nw/gui/statusbar.py, nw/gui/tools/dochighlight.py, nw/tools/spellcheck.py, nw/tools/spellenchant.py, nw/tools/spellsimple.py, sample/sampleNovel/data_6/36b6aa9b697b_main.nwd, sample/sampleNovel/nwProject.nwx, tests/profilestats.py
This should fix issue #144
Also trying to make sure spell check highlighting and context menu are showing the same thing, which isn't quite there yet.
=> Language on Status Bar

novelWriter.py
Since the Travis CI tests were failing in the last PR, I'm trying to make some updates.
* Change build OS to Ubuntu 18.04
* Drop Python 3.5 support, and set minimum Python version to 3.6
* Add test on Python 3.8
=> CI updates

nw/gui/elements/docdetails.py, nw/gui/elements/searchbar.py, nw/gui/mainmenu.py, nw/guimain.py, pytest.ini
* Fixed some minor issues discovered when testing PySide2
=> Various Fixes

docs/source/interface.txt, docs/source/projects.txt, docs/source/started.txt, docs/source/technical.txt
Update Getting Started to point to the correct source archives (.zip and .tar.gz) for 0.4.5 release.
=> Fix some typos

nw/config.py, nw/guimain.py
Add error handling and reporting for the Config class, which is initialised before the GUI. The errors are cached until the GUI is completed.
=> Config Error Handling

nw/guimain.py, nw/project/project.py
Added a counter for the number of saves and autosaves, and added checks to ensure the meta variables exist before trying to load them.
=> Minor tweaks: save counter and meta checks

nw/__init__.py
Some minor changes and cleanup of parsing of command line switches.
=> Command Line Switches

nw/config.py, nw/gui/dialogs/projectload.py, nw/gui/elements/outline.py, nw/guimain.py, nw/tools/optionstate.py, tests/reference/novelwriter.conf
Changes:
* Better handling of the Outline tab when there are no open project, or when one has been closed.
* The open project dialog now accepts double click on the recent items list to open an existing project.
* Resizing of columns is now saved between sessions.
=> Tweaks (Open Project and Outline)

nw/common.py, nw/config.py, nw/constants/constants.py, nw/core/document.py, nw/core/project.py, nw/gui/dialogs/sessionlog.py, nw/guimain.py
* Move some of the code to parse the novel tree into the NWTree class.
* Use meta data to restore the file label of an orphaned file.
=> Minor Refactoring and Restore Orphan File Label

nw/assets/icons/fallback/proj_nwx.svg, nw/gui/dialogs/configeditor.py, nw/gui/dialogs/projectload.py, nw/gui/icons.py, nw/gui/statusbar.py, nw/guimain.py
This PR updates the following:
* Moves the syntax highlighter options to the Editor tab of Preferences.
* Redesigns the open project dialog to be more readable and consistent with other dialogs.
=> Preferences and Open Project changes

CHANGELOG.md, nw/gui/dialogs/docsplit.py, nw/gui/dialogs/itemeditor.py, nw/gui/elements/docdetails.py, nw/gui/elements/doctree.py, nw/gui/statusbar.py
Moved the document stats from the tooltip of the stats label in the status bar to a new column in the details panel below the project tree.
=> GUI Tweaks

README.md, docs/source/export.txt
Added Build Project tool to the documentation, replacing the Export Tool.
=> Updated Docs

assets/installUbuntu.sh
=> Added Ubuntu install script

CHANGELOG.md, nw/gui/build.py
Added font family and size selector to the build novel project tool.
=> Custom Build Font

CHANGELOG.md, nw/core/project.py, nw/gui/__init__.py, nw/gui/additions/qconfiglayout.py, nw/gui/build.py, nw/gui/dialogs/__init__.py, nw/gui/dialogs/projecteditor.py, nw/gui/dialogs/projectsettings.py, nw/gui/elements/docdetails.py, nw/gui/elements/doceditor.py, nw/gui/elements/docviewer.py, nw/guimain.py, tests/reference/gui/0_nwProject.nwx, tests/reference/gui/1_nwProject.nwx, tests/reference/gui/3_nwProject.nwx, tests/reference/proj/1_nwProject.nwx, tests/reference/proj/2_nwProject.nwx, tests/reference/proj/3_nwProject.nwx, tests/test_gui.py
* Fixed some alignment issue for the status icon on the project tree details panel.
* Removed the `Xo` icon for NO_LAYOUT in the project tree details panel.
* Added a details tab to Project Settings to display various meta data about the project, including its path.
=> Minor GUI Fixes

.travis.yml, CHANGELOG.md, nw/core/document.py, sample/data_b/8136a5a774a0_main.nwd, sample/data_e/dca4be2fcaf8_main.nwd, sample/nwProject.nwx
No more document .bak files, .nwd~ works just fine.
=> Get rid of Document .bak files

nw/constants/constants.py, nw/gui/build.py, nw/gui/elements/docdetails.py, nw/gui/elements/doceditor.py, nw/gui/statusbar.py, nw/guimain.py
Minor fixes:
* Word, character and paragraph counts on the project tree details panel are now updated if the selected document is the one being edited.
* The Build Novel project dialog now shows the generated content from last time when it is first opened. The content is cached in the project cache folder as a json file.
* Added two new output formats for the Build Novel project tool. They are HTML and novelWriter Markdown formatted text wrapped in JSON. They are nested in a list entry per file, and then a list entry per line. This should make it very easy to post-process with Python or any other JSON capable tool.
=> Minor Improvements, Changes and Additions

nw/gui/build.py, nw/gui/dialogs/preferences.py, nw/gui/dialogs/projectload.py, nw/gui/dialogs/projectsettings.py, nw/gui/elements/outline.py
Was a bit too quick on PR #274 as there are several QTreeWidgets in novelWriter.
This PR fixes the other trees, and also a few other fixed size settings and icons. This does not seem to fix the scaling of the standard buttons icons the OS provides.
=> Font Sizes – Continued

nw/core/project.py, nw/gui/mainmenu.py, nw/gui/projtree.py
Fixes a few minor issues with the changes to the OptionState class.
=> Fixes for Dev Branch

nw/core/project.py, sample/nwProject.nwx, tests/reference/gui/0_nwProject.nwx, tests/reference/gui/1_nwProject.nwx, tests/reference/gui/2_nwProject.nwx, tests/reference/gui/3_nwProject.nwx, tests/reference/proj/1_nwProject.nwx, tests/reference/proj/2_nwProject.nwx, tests/reference/proj/3_nwProject.nwx, tests/test_gui.py, tests/test_project.py
This PR just moves a few settings around in the project XML file, but retains the ability to load them from the old location so we don't lose the data.
=> Project XML Modifications

tests/reference/gui/3_nwProject.nwx, tests/test_gui.py
This PR increases test coverage of the document editor, including tests for many of the recent additions.
=> Increase Test Coverage

nw/core/options.py, nw/gui/build.py, nw/gui/projsettings.py
Save the window size and replace column width in project settings.
This resolves Issue #322.
=> Project Settings Dimensions

nw/gui/doceditor.py
=> Fixed bug in search replace

nw/gui/sessionlog.py
=> Session Log Fix

docs/source/interface.rst, nw/core/options.py, nw/gui/__init__.py, nw/gui/mainmenu.py, nw/gui/writingstats.py, nw/guimain.py, tests/test_gui.py
The Session Log tool has been renamed to Writing Statistics, as it's been extended quite a bit. It has been moved to the Tools menu, and given a keyboard shortcut `F6`.
=> Writing Stats

nw/core/project.py, nw/gui/doceditor.py
* Fixes the error reporting when converting old project folder structure.
* Added note in search/replace bar tooltip that RegEx search only works from Qt 5.3.
=> Minor Fixes

MANIFEST.in, assets/installDebian.sh, assets/installUbuntu.sh, assets/novelwriter.desktop
Some minor fixes to the install scripts and the manifest file.
=> Build Fixes

nw/gui/doceditor.py
=> Bugfix: RegEx Search/Replace Crash

nw/gui/doceditor.py
Another attempt at fixing issues with search/replace and regEx.
=> Search/Replace Fix

nw/__init__.py, nw/config.py, nw/core/project.py, nw/gui/about.py, nw/gui/mainmenu.py, nw/gui/preferences.py, nw/guimain.py
Mostly code maintenance.
This PR changes:
* how the `__package__` variable is set and used,
* add an exception handler around the main app to catch and report critical errors also to pure GUI users (i.e. when not launching from terminal)
=> Python Package Structure

install.py
The install.py script was a bit out of date, and has now been updated. A fix for issues with some versions of setuptools has also been added.
=> Fix install.py

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/workflows/syntax.yml, .travis.yml, tests/conftest.py, tests/nwdummy.py, tests/nwtools.py, tests/profilestats.py, tests/test_common.py, tests/test_config.py, tests/test_gui.py, tests/test_item.py, tests/test_project.py
Cleaned up the tests and tweaked the flake8 action and the templates.
=> Flake + actions

nw/gui/projsettings.py
Check that the colour returned for a status icon in project settings is valid
=> Issue 395: Check colour return value in Project Settings

nw/gui/doceditor.py
Removed an additional comma in some of the insert menu items that changed the type to tuple
=> Issue #409: Accidental tuple in insert menu

nw/gui/doceditor.py
=> Also capture the return key for the replace box

nw/__init__.py, nw/error.py
This PR upgrades the error handler dialog box to a custom written one with a clickable link to the issue tracker, and a plain text box for the details to include in the ticket.
=> Updated Error Handling

nw/gui/doceditor.py, nw/gui/docviewer.py
=> Issue #433: Move footer if horisontal scroll bar appears

nw/common.py, nw/core/__init__.py, nw/core/document.py, nw/core/index.py, nw/core/options.py, nw/core/project.py, nw/core/spellcheck.py, nw/core/status.py, nw/core/tohtml.py, nw/core/tokenizer.py, nw/core/tree.py, nw/gui/doceditor.py, nw/gui/docviewer.py, nw/gui/projtree.py, tests/test_common.py, tests/test_project.py, tests/test_tools.py
Various bits of code cleanup, improvements, added comments, tweaked logging messages and improved test coverage.
=> Code Improvements

README.md, nw/__init__.py, nw/gui/build.py, nw/gui/doceditor.py, nw/gui/mainmenu.py, nw/gui/preferences.py, nw/gui/writingstats.py, nw/guimain.py, tests/test_dialogs.py, tests/test_gui.py
A few macOS-related fixes and a few minor general fixes.
The README is updated with more detailed install info for macOS.
=> Improvements mainly for macOS

nw/common.py, nw/core/spellcheck.py, nw/gui/doceditor.py, nw/gui/dochighlight.py, nw/gui/statusbar.py, nw/guimain.py, tests/test_project.py
This PR:
* Rewrites the way the word counter thread is managed. This is the more correct way, using a thread pool that can later be used for other features.
* Fixes an issue with aspell dictionaries and checking of words with a hyphen in it.
* Adds a tool tip on the status bar language label that describes what underlying spell check tool is being used.
=> Various Document Editor and Related Improvements

.github/workflows/syntax.yml, nw/core/document.py, nw/core/index.py, nw/core/item.py, nw/core/project.py, nw/core/tohtml.py, nw/core/tools.py, nw/core/tree.py, nw/gui/about.py, nw/gui/build.py, nw/gui/doceditor.py, nw/gui/dochighlight.py, nw/gui/docmerge.py, nw/gui/docsplit.py, nw/gui/outline.py, nw/gui/outlinedetails.py, nw/gui/projsettings.py, nw/gui/projtree.py, nw/gui/statusbar.py, nw/guimain.py, setup.cfg, tests/test_item.py, tests/test_project.py, tests/test_tools.py
Cleanup of various parts of the code. Mostly formatting, comments, docstrings and some renaming of variables.
In addition, some more `f""` strings have been added, and the formatting of the status bar clock has been improved.
=> Code Cleanup and Improvements

nw/gui/outlinedetails.py, nw/guimain.py
=> Clear the outline details panel when closing a project

nw/guimain.py
This PR is related to issues brought up in #494
=> Clarify the dialog messages when closing a project or novelWriter

nw/gui/projtree.py
This PR fixes and closes #521.
=> Issue 521: Move Tree Item Crash

docs/source/index.rst, docs/source/int_interface.rst, docs/source/int_introduction.rst, docs/source/int_started.rst, docs/source/int_typography.rst, docs/source/tech_technical.rst, docs/source/write_export.rst, docs/source/write_notes.rst, docs/source/write_projects.rst, docs/source/write_structure.rst
Read through and brought the documentation up to date with the current functionality of novelWriter. Also rewrapped long text lines and made other minor changes for consistency.
=> Updated Documentation

README.md, docs/source/int_started.rst
Updated installation instructions in README and the docs. They were a little out of date, and have also been made a bit clearer and easier to follow (I hope).
=> Install instructions

nw/assets/themes/gui/default_dark/theme.conf, nw/gui/theme.py, nw/guimain.py, tests/conftest.py, tests/test_gui_theme.py, tests/tools.py
Fixes and issue with the main window title not being cleared when a project is closed, and the new title not set when a new project is created.
This PR also fixes an issue with not clearing all generated files when setting up test projects in tests.
Closes #560
=> Issue #560: Window Title

setup.cfg
Moved `install_requires` into the `options` subsection in `setup.cfg`
=> Issue #570

nw/gui/doceditor.py
=> Issue #574: Show "Add Word to Dictionary" when there are no spell suggestions

nw/gui/theme.py
=> Issue #581: os.path.relpath on Windows

CONTRIBUTING.md, README.md, docs/source/int_started.rst
This PR was triggered by #591 and suggestions by @mgrhm.
The Contributing Guide has been updated to make a few clarifications, and the main Readme updated to implement some of @mgrhm's structure suggestions. It also improves the Installing and Running section based on feedback in issue #586.
=> Update README.md and CONTRIBUTING.md

nw/gui/build.py
This PR adds a saveDocument call before the Build Novel Project runs the build.
=> Issue #610: Save document before build

nw/__init__.py, nw/common.py, nw/config.py, nw/core/index.py, nw/core/item.py, nw/core/options.py, nw/core/project.py, nw/core/spellcheck.py, nw/core/tree.py, nw/error.py, nw/gui/build.py, nw/gui/docviewer.py, nw/gui/theme.py, tests/test_base/test_base_common.py, tests/test_core/test_core_index.py
This PR extends the checking of the loaded index to check that every single variable is valid. It is a lot slower than the previous check, but it still runs within milliseconds.
This PR also adds a logging function for exceptions that replaces the less descriptive `logger.error(str(e))` where `e` is the `Exception`.
=> More thorough index check

README.md, setup.py, setup_windows.bat
This PR adds another command to `setup.py` that will generate a `novelWriter-x.y.z-minimal.zip` file for distributing the code with only the core source files. This should be perfect for for instance Windows users.
=> Minimal Zip Package

nw/core/toodt.py, nw/gui/build.py
This PR adds a document header to the Open Document export formats.
=> Add Header to Open Document export

CHANGELOG.md, docs/source/conf.py, nw/__init__.py, nw/assets/text/release_notes.htm, nw/assets/text/release_notes_1.1.htm, sample/nwProject.nwx
=> Release 1.2 Beta 1

nw/core/options.py, nw/core/spellcheck.py, nw/gui/__init__.py, nw/gui/mainmenu.py, nw/gui/wordlist.py, nw/guimain.py, tests/test_gui/test_gui_dialogs.py, tests/test_gui/test_gui_wordlist.py
This PR adds a simple dialog tool to view and edit the project user dictionary used for spell checking.
=> Tool to Edit User Dictionary

nw/core/index.py, tests/test_core/test_core_index.py
This PR improves the indexing and testing of that indexer, related to #688.
=> Issue #688: Keyword indexing

i18n/nw_en_US.ts, i18n/nw_fr.ts, i18n/nw_nb_NO.ts, i18n/nw_pt.ts, novelWriter.pro, nw/__init__.py, nw/core/project.py, nw/gui/about.py, nw/gui/build.py, nw/gui/doceditor.py, nw/gui/mainmenu.py, nw/gui/preferences.py, tests/test_gui/test_gui_about.py
A translation roundup PR:
* Fixes a few typos and inconsistencies in GUI labels.
* Adds an American English translation, which only changes a few entries here and there.
All the changes to labels were also changed in the translation files, so this PR does not require the translation files to be updated further.
=> Translations Rondup

i18n/nw_en_US.ts, i18n/nw_fr.ts, i18n/nw_nb_NO.ts, i18n/nw_pt.ts, nw/gui/preferences.py
Update the French translation from @jyhelle and fix a bug in Preferences where the settings from the Quotes tab were not being saved.
=> Update French + Bugfix

i18n/nw_en_US.ts, i18n/nw_fr.ts, i18n/nw_nb_NO.ts, i18n/nw_pt.ts
This PR is a second update of the French translation files from @jyhelle. It resets the entries added for the qt_base translation, which aren't needed as Qt provides a translation file for French. I've also committed the updated files for the other languages, but those are only changes to positions in the source.
=> Update french again

setup.py
This PR adds automatic production of sha256 sums of the minimal install packages.
=> SHA 256 Sum for setup files

README.md, docs/source/int_started.rst, setup.py
This PR adds ia8n support to the setup script and adds instructions to the documentation and main README file.
=> I18n Setup

.github/workflows/test_linux_3.6.yml, .github/workflows/test_linux_3.7.yml, docs/source/int_started.rst, docs/source/setup_linux.rst, setup.py, setup/README.md
This PR makes a few modification to the XDG install options for Linux, and adds an additional uninstall option.
=> XDG Setup and Uninstall

docs/source/setup_windows.rst, setup.py, setup/README.md, setup/setup_windows.bat, setup/uninstall_windows.bat
Add a command to `setup.py` to remove icons and registry keys, and add a `uninstall_windows.bat` file that will also run `pip uninstall -r requirements.txt`.
This closes #743
=> Windows Uninstall

nw/core/project.py, nw/core/spellcheck.py, nw/dialogs/projsettings.py, nw/enum.py, nw/gui/doceditor.py, nw/gui/docviewer.py, nw/gui/itemdetails.py, nw/gui/projtree.py, nw/gui/statusbar.py, nw/guimain.py, tests/mock.py, tests/test_gui/test_gui_doceditor.py, tests/test_gui/test_gui_noveltree.py
Makes all properties of the class private and adds a number of signals to propagate changes to other GUI elements.
=> Editor Code Improvements

.gitignore, nw/gui/docviewer.py, nw/gui/itemdetails.py, nw/guimain.py, tests/test_gui/test_gui_docviewer.py, tests/test_gui/test_gui_mainmenu.py, tests/test_gui/test_gui_noveltree.py, tests/test_gui/test_gui_outline.py
Some minor cleanup of variables in the GuiDocViewer and GuiItemDetails classes.
=> GUI Class Cleanup

.gitignore, nw/gui/itemdetails.py
=> Clear handle when tree details panel is cleared

nw/dialogs/docsplit.py
=> Fix split tool dropping last line (#795)

nw/core/project.py, nw/dialogs/docmerge.py, nw/dialogs/docsplit.py, nw/dialogs/preferences.py, nw/dialogs/projsettings.py, nw/dialogs/wordlist.py, nw/gui/doceditor.py, nw/gui/docviewer.py, nw/gui/noveltree.py, nw/gui/projtree.py, nw/gui/theme.py, nw/guimain.py, nw/tools/build.py, nw/tools/writingstats.py, tests/mock.py
* Several calls to makeAlert were missing translation tags.
* Some alerts were sent as tuples rather than string or list. Probably an error from when translations were added.
* Some alerts had hard coded HTML line breaks. There shouldn't be any.
=> Fix translations and refactor makeAlert calls

setup.py
This likely takes care of #805
=> Make the extractVersion function in setup a bit more robust

nw/gui/projtree.py
=> Update project word count when a file is permanently deleted

i18n/nw_en_US.ts, i18n/nw_nb_NO.ts
**Summary:**
Update US English and Norwegian translation files.
**Checklist:**
=> i18n: Update en_US and nb_NO

i18n/nw_fr.ts
**Summary:**
Update French translation.
=> Update French translation

CREDITS.md, README.md
**Summary:**
Add a CREDITS.md file and move over some of the text from README.
=> Add CREDITS file and update README

nw/enum.py, nw/gui/doceditor.py, nw/gui/mainmenu.py, tests/conftest.py, tests/test_base/test_base_error.py, tests/test_dialogs/test_dlg_preferences.py, tests/test_gui/test_gui_mainmenu.py, tests/test_gui/test_gui_theme.py
**Summary:**
This PR adds the new codes for page break and vertical space to the Insert menu.
Last PR for this issue, so closes #835 
=> Add new page and vspace to Insert menu

docs/source/int_introduction.rst, docs/source/usage_export.rst, docs/source/usage_interface.rst, docs/source/usage_projects.rst, docs/source/usage_structure.rst, nw/core/tokenizer.py, nw/enum.py, nw/gui/doceditor.py, nw/gui/mainmenu.py, tests/test_core/test_core_tokenizer.py, tests/test_gui/test_gui_doceditor.py
**Summary:**
This PR updates the documentation for the layout changes and adds the new special title formats to the Format menu.
=> Update docs and add menu entries for special titles

docs/source/setup_linux.rst
**Summary:**
Clarifies a few things in the Setup Linux section of the documentation, and fixes a few errors.
=> Fix a few mistakes in the docs

i18n/nw_en_US.ts, i18n/nw_nb_NO.ts
**Summary:**
Update en_US and nb_NO translations
=> Update en_US and nb_NO translations

setup.py
**Summary:**
Make a shasum for all build packages
=> Make a shasum for all build packages

novelwriter/core/project.py, novelwriter/gui/projtree.py, novelwriter/gui/theme.py
**Summary:**
This PR:
* Fixes an issue with some of the pop-up dialogs having redundant text formatting calls
* Makes the use of internal function mapping for dialog boxes consistent
=> Dialog format error

README.md, docs/source/setup_linux.rst, setup/windows_install.bat, setup/windows_uninstall.bat
**Summary:**
This PR:
* Fixes an issue with reporting missing Python environment when using Windows install scripts.
* Updates a few bits in the main readme and the Linux Setup page in the documentation.
=> Post-release fixes and updates

novelwriter/dialogs/about.py, novelwriter/dialogs/docsplit.py, novelwriter/dialogs/projsettings.py
**Summary:**
Fixes a missing translation and corrects a couple of mistakes in the source,
Resolves #919 
=> Fix missing translation

novelwriter/__init__.py, novelwriter/common.py, novelwriter/core/document.py, novelwriter/core/index.py, novelwriter/core/item.py, novelwriter/core/options.py, novelwriter/core/project.py, novelwriter/core/spellcheck.py, novelwriter/core/tohtml.py, novelwriter/core/tokenizer.py, novelwriter/core/tomd.py, novelwriter/core/toodt.py, novelwriter/error.py, tests/test_core/test_core_document.py, tests/test_core/test_core_index.py, tests/test_core/test_core_project.py, tests/test_core/test_core_tohtml.py, tests/test_core/test_core_tokenizer.py, tests/test_core/test_core_tomd.py, tests/test_core/test_core_toodt.py
**Summary:**
A simple refactoring of the code of core and base classes. There are numerous docstrings that need to be updated, rewritten for consistency, and need spelling and typos fixed.
In addition, there are minor improvements made to the code. Most changes involve replacing minor sections of code with equivalent code that is either simpler, faster, or more Pythonic.
=> Refactor core and base classes

i18n/nw_en_US.ts, i18n/nw_es_419.ts, i18n/nw_fr.ts, i18n/nw_nb_NO.ts, i18n/nw_pt.ts, i18n/nw_zh_CN.ts, sample/nwProject.nwx
**Summary:**
Update all language files.
=> Update language files

docs/source/int_customise.rst, docs/source/int_introduction.rst, docs/source/int_overview.rst, docs/source/int_source.rst, docs/source/int_started.rst
**Summary:**
Corrections to the documentation
=> Make some corrections to the docs introduction section

novelwriter/gui/doceditor.py, novelwriter/gui/docviewer.py, setup/win_setup_embed.iss
**Summary:**
Merge fixes from patches branch.
Resolves #1006
Resolves #1007
=> Merge bugfixes

i18n/nw_es_419.ts
**Summary:**
New ES 419 translation files from Crowdin.
=> Update Latin American Spanish translation

novelwriter/core/item.py, novelwriter/core/tokenizer.py, tests/test_core/test_core_tokenizer.py
**Summary:**
This PR:
* Converts the Tokenizer class into an abstract class. It has no effect on its functionality, this is purely code structure.
* Sets the correct default values for loading type, class and layout for items from the new file format.
=> Minor fixes and updates

novelwriter/core/index.py, novelwriter/guimain.py, tests/test_core/test_core_index.py
**Summary:**
This PR adds automatic indexing of un-indexed files. This replaces the potentially fragile check of comparing all files to the current index. The new implementation is also silent, aside from some info printed to the status bar.
=> Automatic indexing of un-indexed files

novelwriter/assets/icons/typicons_dark/icons.conf, novelwriter/assets/icons/typicons_light/icons.conf, novelwriter/core/project.py, novelwriter/gui/noveltree.py, novelwriter/gui/outline.py, novelwriter/gui/projtree.py, novelwriter/guimain.py, sample/nwProject.nwx, tests/lipsum/nwProject.nwx, tests/minimal/nwProject.nwx, tests/reference/coreProject_NewCustomA_nwProject.nwx, tests/reference/coreProject_NewCustomB_nwProject.nwx, tests/reference/coreProject_NewFileFolder_nwProject.nwx, tests/reference/coreProject_NewMinimal_nwProject.nwx, tests/reference/coreProject_NewRoot_nwProject.nwx, tests/reference/guiEditor_Main_Final_nwProject.nwx, tests/reference/guiEditor_Main_Initial_nwProject.nwx, tests/reference/guiProjSettings_Dialog_nwProject.nwx, tests/test_core/test_core_project.py, tests/test_gui/test_gui_guimain.py, tests/test_gui/test_gui_outline.py
**Summary:**
This PR updates the look of the Outline View to make it consistent with the Novel Tree.
=> Update the Outline View to be consistent with the Novel Tree

novelwriter/core/index.py, novelwriter/dialogs/projdetails.py, tests/test_core/test_core_index.py
**Summary:**
The Project Details dialog now supports multiple-novel projects via a dropdown box like in other views.
Resolves #1078
=> Update Project Details for multi-novel projects

novelwriter/core/__init__.py, novelwriter/core/doctools.py, novelwriter/core/options.py, novelwriter/dialogs/docmerge.py, novelwriter/dialogs/docsplit.py, novelwriter/gui/mainmenu.py, novelwriter/gui/projtree.py, novelwriter/guimain.py, tests/test_core/test_core_doctools.py, tests/test_dialogs/test_dlg_docsplit.py, tests/test_gui/test_gui_guimain.py, tests/test_gui/test_gui_projtree.py
**Summary:**
A complete rewrite of the document split tool.
Resolves #1072
Resolves #1032 as well as it is now moot.
=> Rewrite Split Tool

novelwriter/__init__.py, novelwriter/config.py, novelwriter/core/index.py, novelwriter/core/project.py, novelwriter/core/tree.py, novelwriter/custom.py, novelwriter/dialogs/docsplit.py, novelwriter/dialogs/projload.py, novelwriter/dialogs/projsettings.py, novelwriter/error.py, novelwriter/gui/doceditor.py, novelwriter/gui/docviewer.py, novelwriter/gui/noveltree.py, novelwriter/gui/outline.py, novelwriter/gui/projtree.py, novelwriter/gui/theme.py, novelwriter/guimain.py, novelwriter/tools/projwizard.py, novelwriter/tools/writingstats.py, tests/test_base/test_base_init.py
**Summary:**
The verbose lo logging level no longer serves much of a purpose any more, so this PR converts the remaining verbose log entries to regular debug. The same PR also fixes a few issues discovered by the pylance analyser in the code editor.
Resolves #1186
=> Remove verbose logging

novelwriter/common.py, novelwriter/config.py, novelwriter/constants.py, novelwriter/core/project.py, novelwriter/dialogs/docmerge.py, novelwriter/dialogs/docsplit.py, novelwriter/dialogs/projsettings.py, novelwriter/dialogs/updates.py, novelwriter/dialogs/wordlist.py, novelwriter/error.py, novelwriter/gui/doceditor.py, novelwriter/gui/noveltree.py, novelwriter/gui/outline.py, novelwriter/gui/projtree.py, novelwriter/guimain.py, novelwriter/tools/writingstats.py, tests/mock.py, tests/test_base/test_base_common.py, tests/test_gui/test_gui_guimain.py, tests/test_gui/test_gui_statusbar.py
**Summary:**
This PR fixes a bunch of issues found by pylance in VSCode:
* A bunch of item functions from the Qt framework over items in lists and trees did not have a None check. The functions can return a none, but presumably won't do so when looping over indices between 0 and count(). However, it doesn't hurt to be on the safe side.
* Cleaned up a header check function in the doc editor.
* Fixed an issue where the status bar widget was set to the statusBar attribute in the main GUI. This is actually the name of the method call in the Qt library that returns this widget. The attribute was renamed to mainStatus.
* The data access methods of the subclass of config parser in the common module was written in such a way that the type checking tool could not figure out their return types. …
=> Fix various issues in the code

.github/workflows/test_linux.yml, requirements.txt, setup.cfg
**Summary:**
Add Python 3.11, and set correct Qt framework versions in setup.cfg and requirements.txt
=> Update requirements and add Python 3.11 to CI

novelwriter/gui/doceditor.py
**Summary:**
The editor would only allow looking up tags that were single words. This change uses the same parsing as the syntax highlighter uses and checks that the cursor is on a full valid tag when trying to follow it.
Resolves #1195
=> Allow lookup of tags with spaces

CHANGELOG.md, novelwriter/core/project.py, novelwriter/guimain.py, tests/test_core/test_core_project.py
=> Release 2.0 RC 2

.github/workflows/syntax.yml, .github/workflows/test_linux.yml, .github/workflows/test_mac.yml, .github/workflows/test_win.yml
**Summary:**
Updates:
* Checkout to v3
* Python-Setup to v4
* Codecov to v3
=> Update workflow actions

i18n/nw_base.ts, i18n/nw_de_DE.ts, i18n/nw_en_US.ts, i18n/nw_es_419.ts, i18n/nw_fr_FR.ts, i18n/nw_nb_NO.ts, i18n/nw_nl_NL.ts, i18n/nw_pt_BR.ts, i18n/nw_zh_CN.ts, sample/nwProject.nwx, tests/test_gui/test_gui_i18n.py
=> Update all translation files

CREDITS.md, i18n/nw_base.ts, i18n/nw_zh_CN.ts, novelwriter/assets/text/credits_en.htm, novelwriter/dialogs/about.py, setup.py, tests/test_dialogs/test_dlg_about.py
**Summary:**
This PR:
* Updates the Chinese translation.
* Updates the CREDITS.md file with more links and new contributor credits.
* Replaces the Credits section in the About dialog with a new Credits tab that has the same content as the CREDITS.md file.
=> Update i18n and contributor credits

.github/workflows/build.yml, setup.py, setup/macos/build.sh
**Summary:**
This PR:
* Makes some improvements to the MacOS build.
* Adds a workflow for AppImage builds.
=> Improve build workflows

docs/source/int_started.rst
**Summary:**
Adds MacOS install instructions per  #1362 
Closes #1362
=> Add Macos install instructions to the docs

docs/source/_static/custom.css, docs/source/conf.py, docs/source/index.rst, docs/source/int_howto.rst
**Summary:**
The PR makes some formatting changes to the documentation and adds a HowTo (Tips & Tricks) section.
Closes #1141
Closes #1287
Closes #1288
Closes #1289
=> Update docs and add HowTo

novelwriter/core/item.py, novelwriter/core/tree.py, novelwriter/gui/doceditor.py, novelwriter/gui/itemdetails.py, novelwriter/gui/projtree.py
**Summary:**
Since it is now possible to create root folders relative to existing root folders, the create new root folder function of the project tree now does so if there is an item selected in the tree when the function is called.
Closes #1259
=> New root folder location

CHANGELOG.md, novelwriter/__init__.py, novelwriter/assets/text/release_notes.htm, sample/nwProject.nwx
**Summary:**
Release date 2023-07-30
=> Release 2.1 Beta 1

novelwriter/core/document.py, novelwriter/gui/doceditor.py, novelwriter/shared.py, tests/test_core/test_core_document.py, tests/test_gui/test_gui_mainmenu.py
**Summary:**
This adds the created and updated timestamps to the file info dialog.
Closes #1423
=> Update the file info dialog box

i18n/nw_base.ts, i18n/nw_de_DE.ts, i18n/nw_en_US.ts, i18n/nw_es_419.ts, i18n/nw_fr_FR.ts, i18n/nw_it_IT.ts, i18n/nw_ja_JP.ts, i18n/nw_nb_NO.ts, i18n/nw_nl_NL.ts, i18n/nw_pt_BR.ts, i18n/nw_zh_CN.ts
**Summary:**
Updated translation files from Crowdin
=> Update i18n files

novelwriter/tools/writingstats.py
**Summary:**
Use the same fixed width font for all columns on the Writing Stats tool.
Closes #1442
=> Fix minot font issue

docs/source/int_customise.rst, docs/source/int_glossary.rst, docs/source/int_introduction.rst, docs/source/int_overview.rst, docs/source/usage_breakdown.rst, docs/source/usage_format.rst, docs/source/usage_shortcuts.rst
**Summary:**
Fixed some typos in the docs.
=> Some minor documentation fixes

novelwriter/constants.py, novelwriter/core/tokenizer.py, novelwriter/enum.py, novelwriter/gui/doceditor.py, novelwriter/gui/mainmenu.py
**Summary:**
This PR adds a submenu to the Format menu with all the shortcodes, This PR also cleans up the menu class a little.
=> Add shortcodes to the menu

novelwriter/config.py, novelwriter/gui/projtree.py, tests/test_base/test_base_config.py, tests/test_gui/test_gui_projtree.py
**Summary:**
This PR:
* Removes deprecated config settings from pre 2.0
* Improves test coverage of the project tree
=> Clean up config and improve project tree test coverage

novelwriter/common.py, novelwriter/core/project.py, novelwriter/core/spellcheck.py, novelwriter/extensions/eventfilters.py, novelwriter/gui/doceditor.py, novelwriter/gui/docviewer.py, novelwriter/gui/editordocument.py, novelwriter/gui/mainmenu.py, novelwriter/gui/projtree.py, novelwriter/gui/sidebar.py, novelwriter/shared.py, novelwriter/tools/manuscript.py, novelwriter/tools/projwizard.py, tests/test_base/test_base_common.py, tests/test_base/test_base_shared.py, tests/test_core/test_core_project.py, tests/test_ext/test_ext_eventfilters.py, tests/test_gui/test_gui_mainmenu.py, tests/test_tools/test_tools_dictionaries.py
**Summary:**
This PR:
* Removes the caching of the Alert box in the Shared class and instead stores the last log message.
* Adds the StatusTipFilter to the sidebar menu and also moves it to a new, common event filter module.
* Fixes annotations here and there.
=> Clean up alert boxes and update event filters

docs/source/int_customise.rst
**Summary:**
Replace Misspelling 'Gustom' -> 'Custom' in File 'docs/source/int_customise.rst'
=> Replace Misspelling 'Gustom' -> 'Custom' in File 'docs/source/int_customise.rst'

.github/workflows/build.yml, .github/workflows/syntax.yml, .github/workflows/test_linux.yml, .github/workflows/test_mac.yml, .github/workflows/test_win.yml, docs/source/int_started.rst
**Summary:**
* Updates the docs to remove info on Ubuntu release that no longer exists.
* Update GitHuib actions to latest version.
=> Fix some issues after release 2.2.1

CHANGELOG.md, novelwriter/__init__.py, sample/nwProject.nwx
**Summary:**
Scheduled for 2024-03-26
=> Release 2.4 Beta 1

novelwriter/core/coretools.py, novelwriter/gui/doceditor.py, novelwriter/gui/search.py, novelwriter/guimain.py, tests/test_gui/test_gui_search.py
**Summary:**
This PR adds search refresh when a document is being edited and it is included in an active search result.
=> Add search refresh when document changes

novelwriter/core/toodt.py, tests/test_core/test_core_toodt.py
**Summary:**
This PR refactors and improves various parts of the Open Document writer class.
=> Refactor ODT writer class

.flake8, .github/workflows/syntax.yml, novelwriter/__init__.py, novelwriter/common.py, novelwriter/core/buildsettings.py, novelwriter/core/projectxml.py, novelwriter/core/spellcheck.py, novelwriter/core/tokenizer.py, novelwriter/core/toodt.py, novelwriter/dialogs/preferences.py, novelwriter/error.py, novelwriter/gui/doceditor.py, novelwriter/gui/noveltree.py, novelwriter/gui/outline.py, novelwriter/gui/projtree.py, novelwriter/guimain.py, novelwriter/tools/dictionaries.py, novelwriter/tools/manusbuild.py, novelwriter/tools/manussettings.py, novelwriter/tools/welcome.py, pkgutils.py, requirements-dev.txt
**Summary:**
This PR adds linting of type annotations.
=> Add linting of type annotations

novelwriter/config.py, novelwriter/core/buildsettings.py, novelwriter/dialogs/projectsettings.py, novelwriter/dialogs/wordlist.py, novelwriter/tools/manuscript.py, novelwriter/tools/welcome.py, tests/test_base/test_base_config.py, tests/test_core/test_core_buildsettings.py, tests/test_tools/test_tools_manuscript.py
**Summary:**
This PR:
* Sets the initial chapter and scene count for new projects to 0.
* Adds a project language setting to the Manuscript Build tool as it is quite useful to have it accessible there. 
Closes #1811
Closes #1812
=> Update minor issues

.github/workflows/test_mac.yml, novelwriter/gui/doceditor.py, novelwriter/gui/docviewer.py, novelwriter/tools/manussettings.py, pyproject.toml
**Summary:**
This PR:
* Fixes an issue in the Build Settings dialog that blocks garbage collection when it's closed.
* Fixes an issue where the document font was used for the header and footer in both the editor and viewer.
Closes #1842
=> Fix two minor issues

novelwriter/dialogs/wordlist.py, novelwriter/extensions/modified.py, novelwriter/gui/doceditor.py, novelwriter/gui/mainmenu.py, novelwriter/gui/noveltree.py, novelwriter/gui/projtree.py, novelwriter/gui/search.py, novelwriter/gui/sidebar.py, novelwriter/gui/statusbar.py, novelwriter/guimain.py, novelwriter/shared.py, novelwriter/tools/manusbuild.py, novelwriter/tools/manuscript.py, novelwriter/tools/manussettings.py, novelwriter/tools/writingstats.py, sample/nwProject.nwx, tests/test_gui/test_gui_guimain.py
**Summary:**
This is a refactor/cleanup PR that restructures how various components interact with the Main GUI. Mostly through signals where possible. It also changes how document cursor position is saved. It is now saved even if the document is unchanged.
=> Improve project handling, cursor position, and Main GUI inheritance

i18n/nw_base.ts, i18n/nw_de_DE.ts, i18n/nw_en_US.ts, i18n/nw_es_419.ts, i18n/nw_fr_FR.ts, i18n/nw_it_IT.ts, i18n/nw_ja_JP.ts, i18n/nw_nb_NO.ts
**Summary:**
* Cleanup of deprecated translation entries.
=> Update translation files for 2.4.1

novelwriter/extensions/modified.py, novelwriter/tools/manuscript.py, novelwriter/tools/manussettings.py
**Summary:**
This PR backports the critical part of the deleteLater fix from #1899.
Closes #1903
=> Remove deleteLater calls from Manuscript tools

novelwriter/constants.py, novelwriter/core/tokenizer.py, novelwriter/dialogs/preferences.py, novelwriter/gui/doceditor.py, novelwriter/gui/mainmenu.py, novelwriter/gui/statusbar.py, novelwriter/types.py, tests/test_dialogs/test_dlg_preferences.py, tests/test_gui/test_gui_docviewer.py, tests/test_gui/test_gui_mainmenu.py, tests/test_gui/test_gui_projtree.py
**Summary:**
This PR fixes deletion of the Preferences dialog on close, and fixes a few variable names.
=> Improve memory handling and fix a few variables

novelwriter/core/toqdoc.py
**Summary:**
This PR applies the line height setting also to the manuscript preview.
Closes #1920
=> Support line height in build tool

pkgutils.py
**Summary:**
This PR makes some minor changes to the pkgutils after last PR.
=> Minor changes to pkgutils

docs/source/usage_writing.rst
**Summary:**
Some improvements to documentation based on user questions.
=> Improve documentation

novelwriter/gui/doceditor.py, novelwriter/gui/mainmenu.py, novelwriter/gui/noveltree.py, novelwriter/gui/projtree.py, novelwriter/guimain.py, novelwriter/shared.py, tests/conftest.py, tests/test_base/test_base_error.py, tests/test_base/test_base_shared.py, tests/test_gui/test_gui_guimain.py, tests/test_gui/test_gui_mainmenu.py
**Summary:**
This PR includes various improvements to how documents are handled in the editor and main GUI:
* The editor now has a signal emitted when documents are closed and opened.
* The novel view now listens to this signal when highlighting the current document.
* This feature has also been added to the project tree,
* The opening and closing procedure for editor documents have been refactored a little.
* The editor now uses the PyQt6 compliant wrapper for passing signals to non-slot functions.
Closes #1981
=> Improve document editing

novelwriter/common.py, novelwriter/core/options.py, novelwriter/dialogs/projectsettings.py, novelwriter/gui/docviewer.py, novelwriter/gui/itemdetails.py, novelwriter/gui/noveltree.py, novelwriter/gui/outline.py, novelwriter/gui/projtree.py, novelwriter/gui/sidebar.py, novelwriter/tools/manussettings.py, novelwriter/tools/writingstats.py, tests/test_gui/test_gui_docviewer.py, tests/test_gui/test_gui_outline.py, tests/test_gui/test_gui_projtree.py
**Summary:**
This PR cleans up code in a lot of GUI elements, makes some Qt6 preparations, and makes the details panel in Outline view resizeable.
=> Refactor and clean up GUi code

novelwriter/config.py, novelwriter/dialogs/preferences.py, novelwriter/text/patterns.py, tests/reference/baseConfig_novelwriter.conf, tests/test_dialogs/test_dlg_preferences.py, tests/test_text/test_text_patterns.py
**Summary:**
This PR continues the work from #2079, after feedback in the issues thread.
Related #1773
=> Update dialogue handling again

novelwriter/formats/tokenizer.py, novelwriter/text/patterns.py, tests/test_text/test_text_patterns.py
**Summary:**
This PR makes a couple of minor changes to the dialogue highlighting feature, and adds auto-replacement of horizontal bar with em-dash in the tokenizer.
Related #1773
=> Improve dialogue highlighting after feedback

.github/workflows/build_mac.yml, setup/macos/build.sh
**Summary:**
Previous build now fails.
=> Update MacOS DMG build

i18n/nw_base.ts, i18n/nw_de_DE.ts, i18n/nw_en_US.ts, i18n/nw_es_419.ts, i18n/nw_fr_FR.ts, i18n/nw_it_IT.ts, i18n/nw_ja_JP.ts, i18n/nw_nb_NO.ts, i18n/nw_nl_NL.ts, i18n/nw_pl_PL.ts, i18n/nw_pt_BR.ts, i18n/nw_ru_RU.ts, i18n/nw_zh_CN.ts, novelwriter/constants.py, novelwriter/dialogs/preferences.py, novelwriter/formats/tokenizer.py, novelwriter/gui/itemdetails.py, novelwriter/gui/outline.py, novelwriter/tools/manuscript.py
**Summary:**
This PR fixes a few issues with the translation files, including separating Character (people) from Characters (text).
=> Fix i18n sources

novelwriter/tools/dictionaries.py
**Summary:**
This PR removes a broken link on the Add Dictionary tool.
=> Fix add dicitonary tool

novelwriter/core/buildsettings.py, novelwriter/dialogs/about.py, novelwriter/dialogs/docmerge.py, novelwriter/dialogs/docsplit.py, novelwriter/dialogs/preferences.py, novelwriter/dialogs/projectsettings.py, novelwriter/dialogs/wordlist.py, novelwriter/extensions/configlayout.py, novelwriter/extensions/progressbars.py, novelwriter/gui/doceditor.py, novelwriter/gui/docviewer.py, novelwriter/gui/itemdetails.py, novelwriter/gui/outline.py, novelwriter/gui/projtree.py, novelwriter/gui/theme.py, novelwriter/guimain.py, novelwriter/tools/manuscript.py, novelwriter/tools/manussettings.py, novelwriter/tools/noveldetails.py, novelwriter/tools/welcome.py, tests/test_ext/test_ext_progressbars.py, tests/test_gui/test_gui_doceditor.py, tests/test_gui/test_gui_theme.py, tests/test_tools/test_tools_welcome.py
**Summary:**
A small PR to clean up a few redundancies, fix some minor issues, and general code cleanup. Mostly focuses on the editor.
=> Editor code cleanup, and a few other places

novelwriter/config.py, novelwriter/dialogs/preferences.py, novelwriter/guimain.py, tests/reference/baseConfig_novelwriter.conf, tests/test_dialogs/test_dlg_preferences.py
**Summary:**
This PR adds a setting in Preferences where the dialog box that asks if you want to exit can be turned off.
Closes #2209
=> Disable ask on exit

CONTRIBUTING.md
=> Grammar improvement

novelwriter/core/index.py, novelwriter/gui/editordocument.py, pyproject.toml
**Summary:**
Various tweaks to linting settings.
=> Update linting settings

novelwriter/assets/i18n/project_en_GB.json, novelwriter/core/index.py, novelwriter/core/indexdata.py, novelwriter/formats/tokenizer.py, novelwriter/text/comments.py, sample/content/636b6aa9b697b.nwd, sample/nwProject.nwx, tests/test_core/test_core_index.py, tests/test_core/test_core_indexdata.py, tests/test_core/test_core_novelmodel.py, tests/test_formats/test_fmt_tokenizer.py
**Summary:**
This PR adds parsing of story structure comments. These comments are an advanced feature for tracking the structure of a story through the usage of annotated comments. This PR implements the syntax highlighting and indexing of these comments.
Part of #1784
Closes #2288
=> Add story structure comment parsing

.github/workflows/build_assets.yml, .gitignore, setup/macos/build.sh
**Summary:**
Patch submitted by @Ryex to update MacOS build for Qt6.
Closes #2195
=> Update MacOS build for Qt6

.github/workflows/build_assets.yml, .github/workflows/build_linux.yml, .github/workflows/build_mac.yml, .github/workflows/build_win.yml, .github/workflows/i18n.yml, .github/workflows/test_mac.yml, .github/workflows/test_win.yml, pkgutils.py, utils/build_appimage.py
**Summary:**
This PR:
* Updates all pipelines and builds to run on Python 3.13.
* Fixes the AppImage build script.
Closes #2193
=> Update builds and CI/CD

CHANGELOG.md, setup/make_pip.sh
**Summary:**
This PR fixes:
* Incorrect info in the changelog.
* The pip build script.
=> Fix minor issues after release

tests/test_core/test_core_itemmodel.py, tests/test_core/test_core_novelmodel.py
**Summary:**
This PR adds two tests using the Qt model tester class to check that the novel model and project model are complete.
=> Add tests using the Qt model tester

novelwriter/config.py, novelwriter/core/coretools.py, novelwriter/core/project.py, novelwriter/tools/welcome.py, tests/reference/baseConfig_novelwriter.conf, tests/reference/coreProject_NewFileFolder_nwProject.nwx, tests/reference/coreProject_NewRoot_nwProject.nwx, tests/reference/coreTools_DocDuplicator_nwProject.nwx, tests/reference/coreTools_ProjectBuilderA_Project.md, tests/reference/coreTools_ProjectBuilderA_nwProject.nwx, tests/reference/coreTools_ProjectBuilderB_Project.md, tests/reference/coreTools_ProjectBuilderB_nwProject.nwx, tests/reference/guiEditor_Main_Final_nwProject.nwx, tests/reference/guiEditor_Main_Initial_nwProject.nwx, tests/test_base/test_base_config.py, tests/test_dialogs/test_dlg_projectsettings.py
**Summary:**
This PR:
* Adds shapes and not just colours to default status and importance labels.
* Assigns a new id to projects created from sample files.
* Improve how the title page is generated for new projects.
* The new project form now remembers last used author name and auto-populates the field.
* Project name and author is now also applied to sample projects.
Closes #2332
=> Fix minor issues and make improvements for 2.7 RC 1

novelwriter/assets/themes/snazzy.conf
**Summary:**
This PR adds a GUI theme "Snazzy Light" that matches the existing syntax theme.
=> Add a Snazzy Light GUI theme

novelwriter/core/index.py, novelwriter/core/item.py, novelwriter/gui/outline.py, tests/test_core/test_core_index.py
**Summary:**
This PR fixes two bugs:
* Moving a note between root folders does not update the class associated with its tags in the index.
* Exporting story structure to a CSV file sorts the column headers, but not the data rows, so the values do not match the column they're in.
Closes #2330
Closes #2313
=> Fix auto-complete bug and outline export bug

novelwriter/config.py, novelwriter/core/coretools.py, tests/conftest.py, tests/reference/baseConfig_novelwriter.conf, tests/test_dialogs/test_dlg_preferences.py
**Summary:**
This PR changes a few default settings in config, automatically rebuilds the index in new project creation, and makes a few fixes to tests.
=> Change some defaults and fix index of new projects

novelwriter/gui/docviewer.py
**Summary:**
The document viewer isn't showing story structure comments and notes, so this PR enables that when comments are visible in general.
=> Fix comments visibility

CREDITS.md, novelwriter/assets/text/credits_en.htm
**Summary:**
This PR updates the credits text and license info related to icon themes.
=> Update icon credits info

CREDITS.md, novelwriter/assets/text/credits_en.htm, novelwriter/assets/themes/horizon_dark.conf, novelwriter/assets/themes/horizon_light.conf, novelwriter/assets/themes/otium_dark.conf, novelwriter/assets/themes/otium_light.conf, novelwriter/assets/themes/paragon.conf, novelwriter/assets/themes/selenium_dark.conf, novelwriter/assets/themes/selenium_light.conf, novelwriter/assets/themes/sepia_dark.conf, novelwriter/assets/themes/sepia_light.conf, novelwriter/assets/themes/sultana_light.conf, novelwriter/assets/themes/sultana_night.conf, novelwriter/assets/themes/vivid_black_green.conf, novelwriter/assets/themes/vivid_black_red.conf, novelwriter/assets/themes/vivid_white_green.conf, novelwriter/assets/themes/vivid_white_red.conf, novelwriter/assets/themes/warpgate.conf, novelwriter/assets/themes/waterlily_dark.conf, novelwriter/assets/themes/waterlily_light.conf
**Summary:** This pull request adds the following themes. Sources where specified, otherwise put together by me:
- **Horizon**
bright + dark, from https://github.com/jolaleye/horizon-theme-vscode
- **Otium**
Light + Dark
- **Paragon**
dark, adapted from the Diablo III game rarity colours
- **Selenium**
Light + Dark
- **Sepia**
Light + Dark
- **Sultana**
Day + Night
- **Vivid**
Black + White / Green + Red
- **Warpgate**
dark, adapted from the PlanetSide 2 game UI
- **Waterlily**
Light + Dark
**Related Issue(s):** n/a
=> Add new themes

novelwriter/common.py, novelwriter/core/index.py, novelwriter/guimain.py, tests/reference/coreIndex_LoadSave_tagsIndex.json, tests/test_base/test_base_common.py, tests/test_core/test_core_index.py, tests/test_gui/test_gui_guimain.py, tests/test_gui/test_gui_statusbar.py, tests/tools.py
**Summary:**
This PR ignores the broken index dialog if the index doesn't load the first time a project is loaded in a new version of novelWriter since these cases mostly are due to changes in the index file format.
Closes #2513
=> Index rebuild
